### ISSUE TITLE
Requirements on results for verbs

### ISSUE THREAD

**Issue by andyjohnson** [AICC/CMI-5_Spec_Current#100]
Just to clarify, any Statement with the verbs "completed, passed, waived, failed, or abandoned" (the IRIs, not just the words of course) MUST use completion and success.  The verb will dictate the allowed value of each.

**Comment by MrBillMcDonald** [comment]
Addressed in Sections 9.5.2 Success & 9.5.3 Completion per Feb 13 meeting discussion
