### ISSUE TITLE
Removal of AICC domains and replace with ADL

### ISSUE THREAD

**Issue by andyjohnson** [AICC/CMI-5_Spec_Current#101]
ADL will need to provide a URL structure for verbs and activities.  Once this is done, the spec should be updated so that there is more certainty of the definitions resolving.

**Comment by MrBillMcDonald** [comment]
Agree pending structure - per Feb 13 meeting -

**Comment by garemoko** [comment]
Assuming this is going to use existing identifiers where possible.

**Comment by garemoko** [comment]
Any idea on a date when the new structure will be complete? 

I've got an adopter who wants to use ```http://www.aicc.org/cmi5/extensions/result/progress```

Whilst I appreciate this is a draft spec and not ready to implement, I'm not sure what else to tell her. Creating a competing extension doesn't seem like a good answer, and neither does "use ```http://www.aicc.org/cmi5/extensions/result/progress``` for now and change it later". 

```http://adlnet.gov/expapi/extensions/result/progress``` would be my preference.

**Comment by andyjohnson** [comment]
With adoption of current web standards, it really seems we should have verbs following persistent URLs.  This would mean moving verbs under www.adlnet.gov/ns as a base IRI.  We would also then take this opportunity to change expapi to xapi.  The overlapping verbs would be at http://www.adlnet.gov/ns/xapi/verbs/completed and new CMI5 verbs (or extensions) would go to http://www.adlnet.gov/ns/verbs/completed (or www.adlnet.gov/ns/cmi5/extensions/result/progress)  That isn't definitive and clearly the adopted verbs would have workarounds (redirecting those URLs, for one).

**Comment by garemoko** [comment]
I'm very much in favour of not changing the ADL verb IRIs again, as I was against changing them the first time and will be against another change whenever somebody suggests it in future. 

If IRIs are different to what adopters are using today, systems that adopt CMI5 will be less interoperable than those that don't; that's a terrible selling point for an interoperability specification. Redirecting URLs would be a good idea, but won't help much as very few (if any) adopters actually resolve the IRIs. 

Just out of interest, how does adding "/ns" into the IRI make the URL more persistent anyway?

**Comment by andyjohnson** [comment]
@garemoko , it isn't really something I "get" yet and I absolutely hear you on maintaining interoperability.  Jason is working this issue, but would be good to discuss next week.  Consider me in the same camp as you and Ben in this issue, but I'm open to moving on it if other experts can prove the benefits outweigh the cost.
