### ISSUE TITLE
XML Attributes

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#108]
Hi all,
first of all: Thank you for being inclusive and helpful at your Work Group Meetings. This causes me to continue being "the new guy" and therefore I'm going to ask some stupid questions while reading the specifications. Please stop me, if it is annoying or just close my issues!;-)

To get started I read the course structure specification. And one thing that I noticed, is that there aren't any XML attributes used although if I look at it from a programmers perspective, they would be vey useful for some reason:

- Some of the child elements are unique, like courseId, objectiveId, moveOn, url, etc. Defining them as attribute would enforce the uniqueness in a more implicit and natural manner.
- Additionally it is a lot easier to crawl the XML when you search an element with an specific attribute.
- And finally, imho it's what people expect, if you look at html for example
- If I would convert the XML structure into an object oriented representation there would be an object "courseId" or "moveOn", whereas they should be simple properties of the parent object.

Here are two different examples:

```xml
<course>
<courseId>http://www.yoursite.com/identifiers/course/005430bf-b3ba-45e6-b47b-d629603d83d2</courseId>
</course>
```
vs 
```xml
<course id="http://www.yoursite.com/identifiers/course/005430bf-b3ba-45e6-b47b-d629603d83d2"
</course>
```

**Comment by MrBillMcDonald** [comment]
Attributes added per April 10th meeting.
