### ISSUE TITLE
Defining / Outlining LMS Reporting Requirements

### ISSUE THREAD

**Issue by SpaceCaseChris** [AICC/CMI-5_Spec_Current#111]
In **9.3 Verbs**, we specify: 
>LMS system must record and provide reporting for all statements regardless of which verbs AU’s use in statement.

This statement works well as a general outline for LMS accountability, but doesn't go very far into specifying the actual reporting requirement / use case for the LMS.

###### (apologies, *tl;dr* - if your eyes are starting to water, please skip to the [questions](#questions), below)
In my work, we offer course products as well as an LMS, and also often deal with content integration for third-party LMSes. Custom reporting and non-standard metrics support has become a common request for clients, and while we can take care of this in our LMS, currently, a content provider has little to no control over how the data (especially non-standard data such as values stored in suspend data) can be reported on in a third party system.

We're finding more and more that the LMS administrators that we support are often:
- Less technical than we would desire (it's rare to find one that can tell us which version of scorm their LMS supports)
- Less likely to interact with complex systems in their own LMS, or:
- Very interested in the reporting side of things but frustrated by:
  - Lack of granularity in the data (especially for single-sco content)
  - Lack of a reasonable reporting / report generation process
  - Lack of capability for their LMS' standard reporting to match our LMS' custom tailored reports
- More likely to point the finger at the content when the LMS fails to support a reporting feature (scorm 1.2's non-mandatory objectives and interactions, for example, and especially 1.2's lack of interactions.n.description, which I'm sure we've all grappled with when reporting on interactions).
- More likely to ask the content provider for LMS investigation and support than contacting their LMS provider (as LMS vendors often provide per-hour support fees, while content providers will usually go further to ensure that their content is perceived as functional, even if the LMS partially or fully at fault)

XPAPI/TinCan alleviate many (or as some might say, too many) of these restrictions. With CMI-5 defining the 'standard' verb/activity types, but with the goal of allowing the use of non-standard objects wherever required, I am very excited from both a content provider and LMS provider standpoint to see what kinds of data we can start making available to our clients. All the data in the world, however, won't help those clients if they can't make effective use of it for any of the reasons above (especially if we as content providers do not have any control over the LMS itself).

###### A.K.A. What are you trying to say, Chris?
- **What is the most basic requirement for a reporting mechanism?** We've talked about searching / filtering using the IRI / contextActivity. Is the LMS reporting requirement stopping at this level, or are we thinking that the reports should be more formalized, specifically purposed things that exist as named entities on the LMS (i.e. "WHMIS User Completion Report with session time and interaction results"?
- **Is the LMS required to provide automatic reporting / full visibility around all statements/verbs used by a course/AU, or is specific input required from the LMS admin to tailor a custom report per course/AU?**
- **Does prescribing a base-level reporting mechanic go too far into implementation?**
- From a content provider perspective: **Wouldn't it be great to be able to have a mechanism to suggest to the LMS how best it might report on the course data?** (Especially non-standard data that a course might make use of?)

Thanks Team! (Sorry for the wall of text! I guess I'm a bit of a reporting nerd! :sweat_smile:)

**Comment by MrBillMcDonald** [comment]
Chris, 

Thank you very much for raising this issue !

I would very much like you to join our weekly teleconferences if at all possible.  See details below

   Registration URL: https://attendee.gotowebinar.com/register/1993062001035414786
   Webinar ID: 104-365-515

I am definitely a "kindred spirit"  -  I am a content vendor also and not requiring the LMS's to fully support ALL of the data collection (and reporting it out) this time around would be completely insane. 

Personally, I want to ensure that compliance with CMI-5 means that ANY data recorded by the content MUST be viewable/retrievable in some form.  Given that some data will be unstructured it will be hard to be too specific, but I believe that a conforming CMI-5 LMS/LRS must be able to "barf up" EVERYTHING recorded by content .

(how it looks does not have be standardized - that can be a "quality of implementation" issue for the LMS vendors to use to differentiate themselves with.)

**Comment by SpaceCaseChris** [comment]
Bill - thanks for the response! I forgot to mention that I'm the Canadian Chris from the workgroup.

It's my hope that we might be able to help "hold the LMS' hair back" while it barfs up that data, providing a meaningful way to group the data. For the standard CMI data I don't suspect that LMSes will have too much trouble, but for data outside the spec, or for alternate aggregations of standard and non-standard data, I wonder if we can assist the LMS to organize or contextualize those verbs and activities in some way.. Thoughts?

**Comment by davidpesce** [comment]
Are these meetings open to additional participants? I'm a content vendor as well as a LMS/LRS provider (open source) and am looking to get more involved with this. I'm also trying to make it for the meeting  this month in VA.

**Comment by MrBillMcDonald** [comment]
David,

Absolutely !!  It is open to anyone.  We are NEVER concerned about having "too many participants".
(in my 20+ years experience in standards work there is always room for more people)

I look forward to meeting you in person at the meeting (and in the teleconferences)

(Please) Register for the weekly telecons here:

      Registration URL: https://attendee.gotowebinar.com/register/1993062001035414786
      Webinar ID: 104-365-515

**Comment by davidpesce** [comment]
Excellent! I look forward to meeting you as well!

**Comment by andyjohnson** [comment]
Per our 4/15/15 Working Group meeting, the following will be added:

"Any product (or product bundle) implementing CMI5 MUST implement an xAPI conforming LRS.“
“Any product (or product bundle) implementing CMI5 MUST include the ability to retrieve and show all Statements (including attachments and extensions) to a user (with the understanding of scaling permissions/authorization).”
“Any product (or product bundle) implementing CMI5 MUST decode the attachment and make it available as a file with the original MIME type.”

**Comment by MrBillMcDonald** [comment]
added to runtime spec
