### ISSUE TITLE
Course Structure Testing Repository

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#112]
Hi,

while trying to change the course structure schema I realized that it might be useful to have example files and a repository to test things:

https://github.com/svrnm/CMI5-CourseStructure-Testing

Maybe this repository should be moved to the organization, making it easier for other people to contribute?

**Comment by MrBillMcDonald** [comment]
For now we will just leave it where it is.  I will refer others to it should they need more examples
