### ISSUE TITLE
New ActivityType: Audio

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#115]
I would like to propose another possible activity type for 9.4.3 in the runtime specification:

http://www.aicc.org/cmi5/activitytypes/audio

Reason: This is an alternative to the "video" activity type, e.g. if there is only a audio recording of a certain lesson, like an interview with an expert or a listening comprehension in a language course.

**Comment by bscSCORM** [comment]
See resolution of #116
