### ISSUE TITLE
'module' activity type

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#116]
I was looking in CMI5 to see if you'd defined anything more granular than 'module' and realised that you don't even include ```http://adlnet.gov/expapi/activities/module/```

Should this be included? How about ```http://adlnet.gov/expapi/activities/topic/```? (this one does not currently exist)

**Comment by bscSCORM** [comment]
We have the types defined here:


    http://www.aicc.org/cmi5/activitytypes/assessment
    http://www.aicc.org/cmi5/activitytypes/tutorial
    http://www.aicc.org/cmi5/activitytypes/simulation
    http://www.aicc.org/cmi5/activitytypes/reference
    http://www.aicc.org/cmi5/activitytypes/jobaid
    http://www.aicc.org/cmi5/activitytypes/video

And it seems rather more granular than module, were you looking at that?

**Comment by MrBillMcDonald** [comment]
Per the April 15th meeting.  It was agreed that the Activity Types will be removed so any activity type can be used.  CMI-5 will not have any entities of a lower level activity than AU.

**Comment by svrnm** [comment]
Hi,

i thought I put this in its own issue, but it was part of my issue collection regarding the course structure. I don't know if this is invalid due the agreed changes in your meeting:

The runtime reference states that the object of an xAPI statement is the AU and that this object has an activity type like "assessment", "tutorial", ..., "video". As far as I understand this definition this type is fixed, so it might be useful to an LMS to have this information already within the course structure:

```xml
<au activityType="video" ...>
...
</au>
<au activityType="assessment" ...>
```

This might allow to show icons for the assessment type or making it possible to search for certain activity types.

**Comment by bscSCORM** [comment]
Per April 15th meeting, we will include activity type in the course structure as an optional attribute, and we will not limit the value space of that attribute since we are not defining activity types.
