### ISSUE TITLE
[Idea] Course Configuration

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#117]
Hi,
the following is just an idea floating trough my mind. It is not yet fully thought-out and maybe not even reasonable: 

I would like to have a way to provide some configuration options to the LMS trough the course structure, like: 

- Whats your desired mastery score?
- Whats your desired progress percentage to set the au "completed"
- Given this course has 10 questions, how many of these have to be answered correctly to pass the course.
- How often is the user allowed to fail at the test, before it is not redoable.
- Is the user allowed to reset his learning history?

These are all questions / settings / configrations which may differ from company to company: I know some companies that have a strict 70%-rule, so each course is completed, if 70% are viewed. If the content designer made a different choice, you have to ask him to fix this or you have to change the content yourself. Even if there is a "masteryScore" in your cmi5.xml, this is hard for a non technical user. And even if the content designer changed this value for you, the next company might have a 90% rule or something very different. Some content provider solve this problem by providing a web page where you can pre-configure your SCORM package and they provide you the correct file. But thats not a solution: If you change your rules, you have to go back and re-download the content.

I'm not yet a 100% sure if this is easy to realize or if this will create more issues than advantages. But maybe the following is possible:

```xml
<configuration>
    <option name="requiredMasteryScore" value="decimal" minValue="0.4" maxValue="1.0" default="0.7">
        <question>Whats your desired mastery score</question>
    </option>
</configuration>
```

Within the learning management system the administrator sees these questions when he integrates the course and can change these values. I propose this approach, because its not yet predictable which questions will come up. For example you can even go a step further and make it easy for corporate identity lovers to customize their courses:

```xml
<option name="corporateLogo" value="anyURI" default="path/to/a/default/logo.png">
<question>
Please provide a fully qualified URL to a logo of your company
</question>
</option>
```

**Comment by svrnm** [comment]
After our last meeting, I know understand, that "launchParameters" are actually a kind of configuration for a given assignable unit. So this is maybe not required.

**Comment by MrBillMcDonald** [comment]
As discussed in the April 15th meeting this is out of scope.
