### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by bscSCORM** [AICC/CMI-5_Spec_Current#120]
OAuth looks under-specified. We need to go over it to make sure there is enough information available to actually launch using OAuth. Also, OAuth 1.0a is not a popular choice in xApi, but it doesn't seem reasonable to switch to 2.0 ahead of xAPI itself. We might consider removing OAuth for the first version until we get some more feedback.

**Comment by fugu13** [comment]
Heh, yep, one of my "to hits" in my quickly-made list of notes I'll be turning into issues. Concur on removal or a good deal more work to specify behavior.

**Comment by garemoko** [comment]
+1 to general principal of smaller scope and better.

**Comment by MrBillMcDonald** [comment]
As per April 15th meeting - remove references to OAuth in  Sandstone Runtime & Course Structure.  Due to issues with OAuth, moving forward with just Basic Auth/Fetch URL should be the first starting point and we will adjust as indicated by developer feedback

**Comment by cawerkenthin** [comment]
Do we want to leave authenticationMethod in course structure to allow for expansion, or remove entirely?

**Comment by bscSCORM** [comment]
see #128

**Comment by MrBillMcDonald** [comment]
added
