### ISSUE TITLE
Possible formatting / data inclusion in cmi5_coursestructure.md (7.1.2 Block Meta Data)

### ISSUE THREAD

**Issue by SpaceCaseChris** [AICC/CMI-5_Spec_Current#122]
There is what looks to be extraneous / unformatted text under the Sample Values for both title and description in 7.1.2 Block Meta Data. I think these may be artifacts from previous example/sample content that are no longer relevant.. @MrBillMcDonald, can you confirm? I've updated my fork and created a pull request ( https://github.com/AICC/CMI-5_Spec_Current/pull/121 ) for this issue as well. Thanks!

Under Title:
Removed "Day 1 – Overview of Systems"

Under Description:
Removed "Day 1 – Overview of Systems. In this part of the course you will get a complete overview"

**Comment by MrBillMcDonald** [comment]
Fixed due to langstring
