### ISSUE TITLE
Do the results of rollup need to be represented anywhere?

### ISSUE THREAD

**Issue by bscSCORM** [AICC/CMI-5_Spec_Current#124]
In the course structure document we have the text:

>If all member AU's and Blocks are satisfied, then the course is considered satisfied for prerequisites or credit in relation to other courses or curricula.

This is a sort of rollup, but we have no requirements about what it _means_ that the course is considered satisfied. Should the LMS make statements about satisfied courses or blocks? Or something else?

**Comment by MrBillMcDonald** [comment]
Per the April 15th meeting we plan to add LMS generated statements to the LRS to indicate course completion/satisfaction and block completion/satisfaction.
