### ISSUE TITLE
No concept of attempts

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#125]
Just looking at the duration section, it covers duration for completed attempts and for sessions, but what about a partially complete attempt? 

Lets say you've got a learner doing an e-learning course. On their first session they complete the experience and get half way through a second attempt.  How does the LMS know their current attempt duration for the second attempt?

**Comment by garemoko** [comment]
Consensus at Apr 16th meeting that CMI5 does not have a concept of attempt and this is out of scope. 

Shall I close this?

**Comment by bscSCORM** [comment]
We need to track the larger issue of "We don't have a concept of attempts", you could just rename this.

**Comment by MrBillMcDonald** [comment]
As per April 16th Meeting - we will treat "multiple passed" statements using am method similar to "master score" method.  A combination of State API and course structure metadata.

**Comment by MrBillMcDonald** [comment]
added to runtime and course structure specs
