### ISSUE TITLE
Feature Proposal: LMS Requirement for Course Equivalency?

### ISSUE THREAD

**Issue by SpaceCaseChris** [AICC/CMI-5_Spec_Current#131]
I've seen LMSes that have capabilities to signify that one course is equivalent to another. This seems to have merit in several use cases -> Language specific content, courses with the same certification but different requirements (for example a supervisor specific and employee specific version of the same course, or courses with specific location based sections), updated versions of content for yearly courses that have multi-year expirations, etc.

Is this something we would like to support as an LMS requirement, or would this be something that would be a vendor-specific feature to implement if desired? Would this be a boon or a benefit

**Comment by SpaceCaseChris** [comment]
Forgot to finish the issue.. Should have said "Would this be a boon or a benefit for those with regulatory concerns?"

**Comment by MrBillMcDonald** [comment]
Out of scope for CMI-5
