### ISSUE TITLE
Feature Proposal: LMS requirement for "Certification" other than course completion

### ISSUE THREAD

**Issue by SpaceCaseChris** [AICC/CMI-5_Spec_Current#133]
Many of our clients ask for us to include a printable 'certificate of completion' for courses. While this is useful for certain cases, course-side printable certificates are fallible in several ways, and they are not documented anywhere in the LMS as an accessible object for regulatory use.

Would it be useful to standardize on an LMS-level concept of "certication" (not necessarily a printed certificate, per-se [that could be left to the LMS vendor]). What I would propose is that it might be useful for the LMS to attach a certification to a registration; that is - if the certification has an LMS-specified expiry date, that it might trigger a time-based 'voiding' of the active registration, and potentially re-registering the user for training again.

While the description above may be too specific in regard to implementation, is a version of this feature something that would assist those concerned with regulation / compliance?

**Comment by MrBillMcDonald** [comment]
Outside the scope of the CMI-5
