### ISSUE TITLE
Replace AICC license agreement and disclaimers with ADL versions.

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#139]
The CMI-5 project originally was originally developed by AICC.  It has since been formally transferred to the ADL and needs to get ADL specific license agreements and disclaimers.  This should be done prior to the "Sandstone" release.

**Comment by garemoko** [comment]
Will it be Apache 2 like xAPI?

**Comment by svrnm** [comment]
This is followed by #160 and solved by #165
