### ISSUE TITLE
AU Timestamp - Require UTC

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#141]
I had a thought as the meeting closed. Can we require UTC for the timestamp? I think this will eliminate confusion between systems.

re: "cmi5 Runtime All Statements will require a timestamp (Created by the AU). This will be used to deal with potential timing issues with LRS recording of statements. The (AU provided) timestamps will be used to determine the sequence of the statements."

**Comment by garemoko** [comment]
+1 We're already recommending UTC in xAPI.

**Comment by MrBillMcDonald** [comment]
This is outside the scope of cmi5 and should be addressed in the xAPI specification.
