### ISSUE TITLE
Editorial - CMI5 vs CMI-5

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#149]
CMI-5 and CMI5 are both used throughout the documents. Should one be settled on? I believe it's CMI5, but wanted to make sure.

**Comment by MrBillMcDonald** [comment]
The proper brand is "cmi5" and should be replaced globally

**Comment by davidpesce** [comment]
Fixed in editorial PRs.

**Comment by svrnm** [comment]
Since @davidpesce PRs were not mergeable, there were still some un-replaced "CMI-5"s. I proposed the three PRs to avoid another larger merging issue.
