### ISSUE TITLE
Revision History - update for sandstone release

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#150]
Will need someone to add the appropriate text for the sandstone release in the revision history.

**Comment by MrBillMcDonald** [comment]
Initial Version -  For Developer release.  Subject to change

**Comment by davidpesce** [comment]
Fixed in editorial PRs.

Note: this may require a date change. I set it as todays date.

**Comment by davidpesce** [comment]
Fixed in PR #175
