### ISSUE TITLE
Learning Activity vs AU

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#151]
These seem to be used interchangeably within the documents. Is there a preferred?

**Comment by MrBillMcDonald** [comment]
AU

**Comment by davidpesce** [comment]
Fixed in latest editorial PR.

**Comment by svrnm** [comment]
I created a new pull request for this, too. Actually I found one line which should not be changed:

> An Learning Activity Provider maps to a single AU.
