### ISSUE TITLE
Editorial - CourseStructure - modifying course structures via LMS

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#152]
I believe these two items were to be deleted, but wanted to confirm:

* "The LMS MUST implement a means to export course structures as defined in Section 6.1."
* "The LMS MUST implement a means to create and maintain course structures."

**Comment by MrBillMcDonald** [comment]
Change to Should (keep for now)

**Comment by MrBillMcDonald** [comment]
Ok for Sandstone.  We will revisit prior to next release (after vendor feedback).

**Comment by davidpesce** [comment]
Fixed in latest editorial PR.
