### ISSUE TITLE
Editorial - AU Designer vs Course Designer

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#153]
Is there a preferred way to refer to the "course" designer?

Various instances were found where "AU designer" was used and the "course designer."

Search for "Values are defined by the" to find instances.

**Comment by MrBillMcDonald** [comment]
Change all to "course designer".

**Comment by davidpesce** [comment]
Fixed in editorial PRs.

**Comment by svrnm** [comment]
Also for this issue there were changes from @davidpesce which were lost due the merge conflict. I created PR #170 to re-add the fix.
