### ISSUE TITLE
Webinar ID?

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#158]
Hi all, since the old webinar ID is not valid anymore and I'm not allowed to write to the mailinglist: is there a working group meeting today and what's the webinar ID?

**Comment by MrBillMcDonald** [comment]
Hey Everyone, sorry I didn't realize the old meeting expired.  Please use this new link to sign up:

http://adlnet.us10.list-manage.com/track/click?u=ac72b49bde8d7924b47c823fb&id=d1a59ec01f&e=9d9ba3628e
