### ISSUE TITLE
Course Structure Specification needs to make allowances for "extensions"

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#161]
It appears that the course structure specification is missing "MAY" language for the vendor-specific meta data or "extensions" to be placed in the course structure XML.

It also seems like the XSD is missing an "extensions" section - maybe I am misreading the schema.

This concept is important as many LMS's have feature sets in their course definitions (outside of cmi5 defined data) that is important to preserve.  The ability to "add your own stuff" to the course structure was a most important feature of the AICC course structure specification.

**Comment by svrnm** [comment]
I added the "extensions" section to the XSD.
