### ISSUE TITLE
Add Credits for both Spec

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#174]
review for full list contributors

**Comment by svrnm** [comment]
Hi,
I created a list of all +100 contributors from all meetings (also prior to June, 6th 2014). I'm not sure if I found all duplicates and if all names are written correctly, so maybe this list is not really useful:

http://www.svrnm.de/up/22559/contributors.txt

**Comment by MrBillMcDonald** [comment]
Defer to Andy Johnson's solicitation of credit.  This list contains pre-xAPI participation.
