### ISSUE TITLE
Runtime (9.3 Verbs) contains adl.gov links rather than purl.org

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#199]
Should these all be PURL links?

**Comment by svrnm** [comment]
As far as I remember are those words with adlnet.gov not cmi5 but xAPI specific. So they already exist and shouldn't be changed, i.e. they are working links like http://adlnet.gov/expapi/verbs/launched

**Comment by davidpesce** [comment]
Ohh, yeah, I think you're right! I glossed right over that fact.
