### ISSUE TITLE
Weekly meeting - "add to calendar"

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#210]
Small issue, nothing urgent. 

The "Add to Calendar" option now only shows Outlook. Any chance this can be changed to what it was before? I was able to auto-save it to Google Calendar in the past.

**Comment by andyjohnson** [comment]
Hey David, not sure.  GoToMeeting has been changing options all over in the last 6 months.  I can help troubleshoot if you want, but I'm just throwing out the registration link it gives me.
