### ISSUE TITLE
Context activities

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#212]
It looks like the context activities section needs some attention: https://github.com/AICC/CMI-5_Spec_Current/blob/master/cmi5_runtime.md#962--contextactivities

I'm not totally clear what it all means but it seems to imply "category" (or "grouping"? not clear) Context Activities with activity ids that are simple strings rather than IRIs. The LRS will reject such statements.

**Comment by MrBillMcDonald** [comment]
Per the June 12th meeting, the following language was proposed to resolve this issue.


9.6.2 contextActivities

The purpose of this property is to facilitate searches of the LRS by the LMS or other reporting systems. contextActivities contain category objects whose entries can be used as wildcard searches.  Each category is tagged with name value pairs of "id" and an IRI.

All cmi5 Statements MUST have a category with an "id" of "http://purl.org/xapi/cmi5/context/categories/cmi5" as the IRI.

Statements with a results object (Section 9.5) that include either "success” or "completion” properties MUST have a category with an "id" of "http://purl.org/xapi/cmi5/context/categories/moveon".  Other statements MUST NOT include the this  property.

**Comment by MrBillMcDonald** [comment]
Language added to Quartz per June 26th Meeting
