### ISSUE TITLE
Defining a "best practice" for extensions

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#215]
Our short talk about the "test question data model" of HR OS and that it should not be part of cmi5 itself but an extension, made me think about the whole subject of extensibility of cmi5:

First of all I prefer to move this data model into an extension myself. There are some reasons for that: 
- It is not the only additional feature that could be included into cmi5. I can think about something like more meta data (LOM-style), configuration (cmp #117), sequencing (!), .... I would love to have all these features with cmi5 but this might be the "breach in the dike" (does this phrase existing in the english language?)
- Having this or any other mentioned feature in the core of cmi5 would make cmi5 a lot more complicated to implement for LMS providers!
- Finally some of these and especially the test question data model might be first class xAPI profiles themselves!  

Based on that reasons, here are my suggestions:
- We keep cmi5 as simple as possible to make it easy to implement! Because as @cawerkenthin wrote "SCORM is complicated" (--> http://risc-inc.com/blog/introduction-to-the-xapi/)
- As part of the course structure specification or as standalone document we specify some best practice rules for cmi5 extensions, like "check if your extensions could be a xAPI profile itself" or "an content using your extension should preferable have a fallback if the LMS does not support your extensions", "to become an official(?) cmi5 extension you should use a compatible free/open license", etc.
- We take one (simple) example and define a model extension people can look up if they like to extend cmi5.

Enjoy your weekend!:-)

**Comment by MrBillMcDonald** [comment]
Per July 31st Meeting - will look for best practices use cases for Course Structure extensions.
(Runtime extensions should already be covered)

**Comment by svrnm** [comment]
I created an example course structure extension providing the possibility to add keywords (or tags) to a course, au, or block:

XSD: https://github.com/svrnm/CMI5-CourseStructure-Testing/blob/master/KeywordExtension.xsd
XML: https://github.com/svrnm/CMI5-CourseStructure-Testing/blob/master/extension/cmi5.xml

It is a really simple example, but maybe it fits, so we can use it for demonstration?

**Comment by MrBillMcDonald** [comment]
Closed per PR - Additions to "Vendor Specific Metadata" #246
