### ISSUE TITLE
There's no such thing as an actor object

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#216]
8.1.1 says that the launch url should contain an actor object as defined by xAPI. The term actor object is also used in 9.2, which is also referenced by 8.1.1. 

In xAPI, there's no such thing as an actor object, only an agent object or a group object, both of which can be the values of the actor property. 

I guess it's possible that cmi5 could define an actor object, but I think that'd be confusing and even if it does, 8.1.1 needs to be tidied up.

**Comment by liveaspankaj** [comment]
> In xAPI, there's no such thing as an actor object, only an agent object or a group object, both of which can be the values of the actor property.

xAPI Spec defines the type of "Actor" as "Object"  https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#details 

So, I think calling an JSON Actor Object as Actor Object would make perfect sense as long as its refers to both agent as well as group objects. However, if group is acceptable, the descriptions might need to be modified accordingly specially at places that refer to "agent"

**Comment by garemoko** [comment]
That type column refers to the value of the property rather than the property itself. I'm not sure how that can be made clearer.

@andyjohnson - the distinction between properties and the objects used as their values might be something to cover in the JSON section of the introduction as it is a common area of confusion?

**Comment by MrBillMcDonald** [comment]
Per the July 24 meeting discussion, we will refer to it as "Actor" vs."Actor Object" where appropriate.
