### ISSUE TITLE
Why can't the actor be a group?

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#217]
cmi5 section 9.2 says that the "actor object" (see #216) must have a type of agent. 

Why can't it be a group? 

For a man with a use case, see @frasern in https://github.com/RusticiSoftware/TinCanJS/issues/111

**Comment by MrBillMcDonald** [comment]
It is a core requirement of cmi5 the that actor is a individual learner.  The cmi5 use case is specifically for a individual learner using a single system.
