### ISSUE TITLE
Can an objective or sub-activity inside an AU send its own initialized/passed/failed/completed statements?

### ISSUE THREAD

**Issue by liveaspankaj** [AICC/CMI-5_Spec_Current#218]
AU is the only launch-able item in the course. And, based on my understanding an AU may contain multiple trackable sub activities. e.g. A Video and a quiz, or may be even multiple quizzes. 

In such cases, can each activity sent its own statements initialized/passed/failed/completed verbs (with their own activity id)?

The current cmi5 spec says: "The AU MUST NOT issue multiple statements with "Completed" for the same AU within a given AU session or course registration for a given learner"

If this means that initialized, completed, passed and failed can be used only once in an AU. It can be a challenge. 

At the moment, I am particularly looking at if an "Initialized" and "Completed" verb is used by Videos, will it conflict with the cmi5 spec, and I found that it can be an issue unless 
1. cmi5 either explicitly allows sub-activities inside AU to have their own initialized/passed/failed/completed statements with their own activity id's. OR,
2. cmi5 mentions that it doesn't care about statements sent by sub-activities with thier own activitiy id. 

Thoughts?

**Comment by liveaspankaj** [comment]
To some extent indirectly related to #96

**Comment by liveaspankaj** [comment]
@andyjohnson

**Comment by liveaspankaj** [comment]
Here is an example demo of an Articulate course with two quiz in one content. It sends passed/failed statement for each quiz. And at the end, it sends passed/failed for the entire course which is currently based on second quiz alone. There will be no way to use such content on cmi5 if there were restrictions of sending statements like passed/failed/completed. 

http://demo.nextsoftwaresolutions.com/gb_xapi_content/articulate-double-quiz-demo/

You can see the statements on the LRS here:
http://demo.nextsoftwaresolutions.com/grassblade-lrs/Reports
Username: user@nextsoftwaresolutions.com
Password: user

**Comment by MrBillMcDonald** [comment]
This is being addressed by the Non-cmi5 statements issue
