### ISSUE TITLE
Can langstring values be used that are not listed within languages?

### ISSUE THREAD

**Issue by jamie-burns** [AICC/CMI-5_Spec_Current#223]
In Course Structure, the description of the 'languages' element says that 'all of the languages list MUST be present in a langstring for each title or description element'.

What about the other way around?  Is it valid to have a langstring value for a language not listed?

For example, if we have -

```xml
<languages>
  en-US
  es-MX
</languages>
```

Is it valid to have a title of -

```xml
<title>
  <langstring lang="en-US">Title in EN</langstring>
  <langstring lang="es-MX">Title in ES</langstring>
  <langstring lang="fr-FR">Title in FR</langstring>
</title>
```

I am assuming it is valid, since the 'languages' list is optional anyway, but I just thought I'd check that I had understood it correctly.

Would the LMS still be expected to display the language specific titles/descriptions for languages that are not listed in the 'languages' list?

**Comment by MrBillMcDonald** [comment]
Since this data can be derived from AU metadata, this section (7.1.1) will be removed. (Per July 24 meeting)
