### ISSUE TITLE
Course Structure Example

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#225]
As discussed with @nphoenix  at #214 and at one of the last meetings we are looking for a simple and a complex "real-world" example. Since we use rocks to name our versions (sandstone, quarz), I propose geology as example:

**Simple**:
https://github.com/svrnm/CMI5-CourseStructure-Testing/blob/master/simple/cmi5.xml

**Complex**:
https://github.com/svrnm/CMI5-CourseStructure-Testing/blob/master/complex/cmi5.xml

The complex example is not yet finish, since I'd like to discuss and agree upon this proposal.

**Comment by MrBillMcDonald** [comment]
Course structure examples should be placed in the back of the spec for better reading continuity.

These examples will be further refined and reviewed...

**Comment by svrnm** [comment]
I created a pull request, so I close this issue.
