### ISSUE TITLE
progress extension IRI only give in example

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#231]
Section 9.5.5.1 would be clearer if it listed what the extension IRI was. Currently the reader has to scroll up and look at the example at the start of section 9.5

**Comment by MrBillMcDonald** [comment]
At the Aug 7 meeting the group proposed the following language to address this issue:
===========================================

9.5.5 Extensions

9.5.5.1 Progress

An integer value indicating the completion of the AU as a percentage. The AU may set 

this value in statements to indicate level of completion between 0 and 100 percent.

Progress is defined in extensions using the following IRI:

      http://purl.org/xapi/cmi5/result/extensions/progress
