### ISSUE TITLE
moveOn Criteria for non-success verbs

### ISSUE THREAD

**Issue by SpaceCaseChris** [AICC/CMI-5_Spec_Current#232]
Under 7.1.4 AU Metadata in the CourseStructure.md, we specify moveOn criteria for successful states, specifically: "Passed", "Completed", "CompletedAndPassed", "CompletedOrPassed", "NotApplicable".

If we're hoping to keep AU's as close to atomic as possible (single activity per AU, etc.) instead of building a lot of "single AU" courses, is it worth adding moveOn criteria for unsuccessful states as well? 

For example, I can see a variety of use cases where an AU might want to report a "failed" verb, but allow the user to continue to progress throughout the rest of the course. (Especially in cases where we do not want users to be able to perform more than one attempt at the AU, or for cases where failure is not a course-ending condition, such as a "Knowledge Check" - think completion_status="completed" and success_status="failed" in scorm 2004).

Or - am I looking at this incorrectly.. Would the AU itself contain another activity which would issue "failed" verbs, but the AU itself still issue "completed" verbs?

This raises another question/concern - if we do want to add additional moveOn verb cases, we currently would have to change the spec to allow for more. This is fairly inflexible, and would necessitate LMS changes to support more if the spec was changed. More on this in the next issue.

**Comment by MrBillMcDonald** [comment]
This issue (use case) is addressed by using a moveOn criteria of "Completed" and issuing "Completed" and "Failed" Statements.

**Comment by SpaceCaseChris** [comment]
Thanks Mr Bill - this makes good sense. I keep getting stuck in 'scorm 12 land' and forgetting that multiple status statements won't conflict (other than the passed then failed case we specifically handle)
