### ISSUE TITLE
moveOn flexibility concerns (attribute vs. child)

### ISSUE THREAD

**Issue by SpaceCaseChris** [AICC/CMI-5_Spec_Current#233]
If we want to add additional moveOn verb cases in future releases of the spec, we currently would have to each specific value/case for moveOn directly to the spec.This is fairly inflexible, and would necessitate LMS changes to support more if the spec was changed. We have the potential to make moveOn much more robust and flexible here. This would add a little more work up-front for LMS vendors, but would reduce re-work due to spec changes down the road (which is more painful in many cases).

We could accomplish this by making moveOn a child-node of the AU rather than an attribute, and making each possible moveOn verb a child-node of that moveOn node. In doing so, we could also avoid the unnecessary merging of verbs and creation of special combined cases on the LMS for situations like "CompletedAndPassed" or "CompletedOrPassed". The lack of a moveOn node would signify to the LMS the "NotApplicable" state.

This would essentially allow the developer to use any verb (cmi5 or their own) as an acceptable moveOn value, which is nice and flexible (maybe too flexible? Are we giving them too much rope?) We would also need to provide the moveOn node with a means of specifying the and/or relationship between verbs, as follows:

Example:
```
<courseStructure>
  <course>
    <title><langstring lang="en-US">Course with flexible moveOn mechanism</langstring</title>
    <description><langstring lang="en-US">This course structure shows a possible new mechanism for signifying moveOn criteria.</langstring></description>
    ...
  </course>
  <au>
    <title><langstring lang="en-US">AU with flexible moveOn</langstring</title>
    <description><langstring lang="en-US">This AU will be considered satisfied upon issuing a Passed, Completed, or Failed verb.</langstring></description>
   <moveOn relationship="OR">
        <verb>Passed</verb>
        <verb>Completed</verb>
        <verb>Failed</verb>
   </moveOn>
   ...
  </au>
  <au>
    <title><langstring lang="en-US">An AU with non cmi-5 moveOn</langstring</title>
    <description><langstring lang="en-US">This AU uses a custom verb for moveOn.</langstring></description>
    <moveOn relationship="OR">
        <verb>MyCustomMoveOnVerb</verb>
    </moveOn>
   ...
  </au>
  <au>
    <title><langstring lang="en-US">An AU with no moveOn criteria / not applicable</langstring</title>
    <description><langstring lang="en-US">The lack of a moveOn node in this AU signifies to the LMS that it should be considered satisfied from the start (as would have been the case for moveOn="NotApplicable" previously.</langstring></description>
   ...
  </au>
</courseStructure>
```

If more complex logic were to become desired, we could even take this a step further to allow for groups of verbs within the moveOn node, such as:
```
 <au>
    <title><langstring lang="en-US">AU with flexible moveOn</langstring</title>
    <description><langstring lang="en-US">This AU will be considered satisfied upon issuing both Passed AND Completed verbs, or a singular Failed verb.</langstring></description>
    <moveOn relationship="OR">
       <verbGroup relationship="AND">
           <verb>Passed</verb>
           <verb>Completed</verb>
       </verbGroup>
       <verb>Failed</verb>
    </moveOn>
   ...
  </au>
```

Thoughts? I know we want to avoid the "[NOT SO] simple sequencing / flow control" of 2004, but I think is still fairly straightforward for developers / vendors to implement, and I like the removal of non-verb cases such as "CompletedAndPassed" / "NotApplicable".

**Comment by MrBillMcDonald** [comment]
Per Aug 14 meeting.  Existing Vocabulary for moveOn will stay in place (to keep with our "simple" goal for course structures).

**Comment by SpaceCaseChris** [comment]
There was a great quote that came out of the Aug 14th meeting, regarding both "simplicity" and "reducing interpretation" as goals of the spec. The interpretation piece really resonates with me - can/should we expand this statement in the proposed "vision" additions to the readme.md?
