### ISSUE TITLE
When LMS writes Abandoned, should it also write Terminated?

### ISSUE THREAD

**Issue by cawerkenthin** [AICC/CMI-5_Spec_Current#236]
For session management, if the LMS writes the Abandoned statement, should it also send a Terminated statement?

**Comment by MrBillMcDonald** [comment]
Art,  

In my opinion, I think that would be unnecessary and maybe even a bad idea as "Terminated" should indicate a "normal exit" by the AU and "Abandoned" indicates that the LMS has determined that the AU has abnormally exited.

What is rationale for the LMS writing a "Terminated" statement ?

Sincerely,

Bill McDonald

**Comment by cawerkenthin** [comment]
My guys have begun writing the cmi5 engine for our LMS.  I am having them read the spec to develop the engine, rather than relying on me, to verify the clarity.  This was one of their questions.  Maybe we should modify the runtime document to indicate that Abandoned should be the last statement for a session and no other statements should follow, as we did for terminated.

**Comment by MrBillMcDonald** [comment]
Excellent idea !  i will draft a pull request.
