### ISSUE TITLE
RFC 2396 vs RFC 3986 vs RFC 3987

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#237]
The "References" section for both documents points at RFC 2396, but the definitions section doesn't mention URIs and instead provides a definition for IRI which talks about RFC 3987. Should bring these things inline, I'm assuming towards RFC 3987.

**Comment by brianjmiller** [comment]
Perhaps add IRI/IRL to "Abbreviations and Acronyms". That section also talks about "XAPI" but probably ought to include it as "xAPI".

**Comment by MrBillMcDonald** [comment]
Fixed per PR  - Add Error Value descriptions #250
