### ISSUE TITLE
If the auth-token is not found, what is the return code?

### ISSUE THREAD

**Issue by cawerkenthin** [AICC/CMI-5_Spec_Current#239]
If the authorization token is not found on the call to fetchUrl, should the error code be a 3 (General Application Error)?  I am thinking about when the AU calls the fetchUrl with invalid parameters.

**Comment by MrBillMcDonald** [comment]
Drafting a response based on Aug 28 meeting agreement

**Comment by MrBillMcDonald** [comment]
Fixed per PR - Add Error Value descriptions #250
