### ISSUE TITLE
Inverted lang strings in example

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#244]
I found the below in the course structure examples. The languages are the wrong way round. 

<langstring lang="en-US">Das Archaikum Es erstreckt sich von ca. 4.000 bis ca. 2.500
            Millionen Jahren vor heute.
          </langstring>
          <langstring lang="de-DE">The Archean Eon is a geologic eon before the Proterozoic Eon,
            before 2.5 Ga (billion years), or 2,500 million years ago.
          </langstring>

**Comment by svrnm** [comment]
oh yes! Thank you. I provided a PR.
