### ISSUE TITLE
How to guarantee consistency for shared sections

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#257]
Scrolling trough both documents I discovered that the shared sections are not consistent (i.e. equal). There are minor issues like  different structure (#252) or changes only done once (#255), but if you compare especially "Section 6", you'll see that these are quiet different, since changes were only made to the runtime specification. There are different ways to solve this issue, here are some I can think about:

- Creating a common "master" document referenced by both specifications.
- Trying to reduce shared sections and find an approach to change both documents if a change affects both
- ...

**Comment by MrBillMcDonald** [comment]
combined both runtime and course structure into one spec document.
