### ISSUE TITLE
Bibliography vs. References

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#258]
What is the difference between the bibliography section and references section? As far as I understand these document, the section "References" includes important documents like the xAPI specification and bibliography includes documents that are related but maybe not required to be read, e.g. the SCORM specification or the document about mime types. 
If this is the case, we need to clean up: The bibliography of the ***runtime specification*** cites all the documents also included in the reference section.

**Comment by MrBillMcDonald** [comment]
Will remove Bibliography.  And add MIME to References (Both Documents(

**Comment by MrBillMcDonald** [comment]
bye bye biblio....
