### ISSUE TITLE
Multiple Statements with Results (Score)

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#263]
What happens when the AU sends multiple statements with a score in results (during a single AU session)  ?   Is the last score the final ?  Does it matter which verb is used ?  (Completed, Passed, etc) 

Would Passed verb be the final score ?

**Comment by liveaspankaj** [comment]
Based on what I understand score sent by only "completed", "passed" or "failed" should matter. 

Depending on the use cases, instructors might be interested in:
first score
last score
highest score
last/latest passed score
average score

Depends on what of these make most sense with the use cases we have here?

**Comment by garemoko** [comment]
Sending multiple statements with the same result data (score, completion, success) within the same attempt would work badly with [existing reports in Watershed LRS](https://watershedlrs.zendesk.com/hc/en-us/articles/205944550-Statement-Design-Guide#activity-detail). The data would potentially be double-counted. 

For that reason, I'd like cmi5 to restrict use of each result property to a particular verb (or exclusive verb group e.g. passed/failed). I think score belongs best with pass/fail.
