### ISSUE TITLE
Demographic data

### ISSUE THREAD

**Issue by johnkleeman** [AICC/CMI-5_Spec_Current#28]
We need to find a way to allow the launched content to be able to request demographic data from the LMS. This is a current capability of AICC HACP, and useful for any content that needs context or extended information about the learner/agent.

The LMS passes the content the agent ID. The content asks the LMS for extended information on the agent. For example location, organization, department and so on. 

Could we discuss with the group. There seem two issues

1. How do we structure the data, we might use HR-XML or we might have name/value pairs

2. What technical method should be used? We potentially might extend one of the existing xAPI APIs, e.g. extend Agent Profile API probably best or modify Document API https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#docapis

**Comment by MrBillMcDonald** [comment]
Learner profiles are currently outside of the scope of CMI-5.  (See #46)
