### ISSUE TITLE
Other Launch Environments?

### ISSUE THREAD

**Issue by svrnm** [AICC/CMI-5_Spec_Current#281]
Maybe I have a wrong understanding, but for what reason is there a separation between an "Web (Browser) Environment" and "Other Launch Environments": Any environment has to be able to send HTTP requests to support xAPI, so they could use the launch mechanism for web browser environments easily. 

Additionally, from a perspective of a software developer it is not useful, maybe even harmful to define separate mechanism per operating system, i.e. there should be only one properly defined API to launch an AU.

**Comment by MrBillMcDonald** [comment]
Per Oct 2 meeting - we will remove 

"8.1 Web (Browser) Environment"  and rename "8.1.1 Launch Method" to "8.1 Launch Method"
given that the URL method of launch is not necessarily browser dependent.  We will consider other launch environments later if the URL does not work in all of them.
