### ISSUE TITLE
Slack registration (email address) rejects email

### ISSUE THREAD

**Issue by davidpesce** [AICC/CMI-5_Spec_Current#288]
Here's what I receive back:

"We're writing to let you know that the group you tried to contact (cmi5wg) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at http://support.google.com/a/adlnet.gov/bin/topic.py?topic=25838.

Thanks,

adlnet.gov admins"

**Comment by brianjmiller** [comment]
+1

**Comment by MrBillMcDonald** [comment]
Remove slack registration link.   Per Jan 15th meeting.
