### ISSUE TITLE
Use case for multiple "attempts" within an AU session

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#294]
Chris,

I am restating your issue here so that I can document my responses in the issues section.  

In Oct 16th meeting we did discuss your statement below and determined that the rationale for restricting the duplication of (cmi5 defined) verbs in a single AU session needs to be better explained.  We also believe that, thru the extensible cmi5 features and best practices, the goal of recording multiple attempts in an AU session can be easily achieved. 

Here are my responses to some of your points.  We will discuss this more and document the use cases.

**Issue/question 1:**
>I might be completely out of left field here, but if I am, I have a feeling other implementers and content creators might be too, so let's fully outline use cases / expectations here to avoid future confusion.

**My Response 1:**
_Totally agree that we need to fully define the use cases. The fact that this issue has come up multiple times highlights the need for creating a (non-spec) document to explain the rationale AND the use cases._

**Issue/question 2:** 
>Is this restriction only for the AU itself, or does it apply to objects within, such as quizzes, as well?

**My Response 2:**
_The restriction is for an AU.  (Or more specifically an AU session)_

**Issue/question 3:** 
>Would a quiz ever be the entirety of an AU? If so, does this restriction become cumbersome and something to 'work around'?

**My Response 3:** 
_AU could definitely be a Quiz.  Multiple "Attempts" could be recorded with "cmi5 allowed" statements during the AU session.  The "final result" would be recorded prior to exiting the AU session using a "cmi5 defined" statement with the restriction._

-----
#### Original Pull Request Comment from Chris
-----
>Bill et al,
>
>Apologies for missing our session - I'm on vacation presently with access only to email.
>
>Maybe I'm beating a dead horse here, but I really feel that if we're going to restrict AU behavior this far, there is a need for a verb to define a status of 'attempted but not satisfied'  beyond failed.
>
>I might be completely out of left field here, but if I am, I have a feeling other implementers and content creators might be too, so let's fully outline use cases / expectations here to avoid future confusion.
>
>Is this restriction only for the AU itself, or does it apply to objects within, such as quizzes, as well? We talk about the 'AU session' but it doesn't read like this is restricted to the structure level object only. Or are we still intending the AU to be as granular as possible.. Would a quiz ever be the entirety of an AU? If so, does this restriction become cumbersome and something to 'work around'?
>
>I worry that placing too many seemingly arbitrary restrictions in the spec might deter adoption. If we can really hammer out the what and why of restrictions like this I think it will help our case.
>
>The language reads to me that an AU cannot be failed, reattempted, and then passed within a single session, but it does not prescribe an expected behavior for the course to take in order for this flow to be achieved. Do we close and immediately open the window, or, somehow terminate the existing session and begin a new one at runtime, etc.
>
>I don't see forcing a new AU launch upon the user for each quiz attempt (as an example) being good user experience, and I could see it being perceived as an issue/bug by many of our users (those less tech savvy, for example).
>
>I can see a standard verb for attempted being very useful, as almost every client that wants quizzing from us wants to know how many attempts at a given quiz a learner made before passing. It may also help in cases such as this. Where until a maximum number of attempts has been reached, an AU is not considered failed, but merely attempted.
>
>Maybe I'm not understanding what a restriction around multiple failures or a passed following a failed in a single session does for the spec, but I know that forcing a relaunch for each reattempt of the AU would create a large number of complaints from our existing user base.
>
>I'll be away next session as well, but can we work through this the week following?
>
>Thanks Team,
>Chris

----

**Comment by SpaceCaseChris** [comment]
Thanks for the clarifications here Bill - it seems that where things get
confusing surrounds the 'per AU session' wording. I think I'm understanding
the vision, but this is a very implication-heavy part of the spec, so I
look forward to working on use cases and proposed methodologies here.

A question, surrounding the "au session" verbiage (and apologies if this
has already been addressed in the weeklies): Would it be acceptable, as an
example, to fail an AU, end the session, start a new session, and pass the
AU? And the inverse? Or are the restrictions around passing and then
failing outside of the per AU session scope?

Look forward to chatting this Friday - thanks team!
