### ISSUE TITLE
What is "course registration"  

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#298]
The concept of "course registration" is used a few times but it's never explained what it means. I seems like this could be similar to the concept of an attempt? 

Does the LMS have to use an id representing the course registration as the value of context.registration?

**Comment by MrBillMcDonald** [comment]
Andrew,

This is a great question.  Here are my responses...

**Q1. The concept of "course registration" is used a few times but it's never explained what it means. I seems like this could be similar to the concept of an attempt?**

A1. _In cmi5, a "registration" is a learner's enrollment in a specific "course" course instance.  In cmi5, a "course" is a defined collection of one or more AUs(Assignable Units).  All cmi5 statements must include this registration id in the context.  This registration id is provided to the AU via the URL launch line by the LMS._

_On reviewing the references to "registration" in the cmi5 specification, I can see why you have this question.  The term "registration" and "course registration" mean the same thing in the cmi5 specification. We should only use one term and add and entry for "registration" to the definitions section._

See the following excerpt from _10.0 xAPI State Data Model_ 

>**State API PUT Properties:**
>
>* activityId: Activity ID for the AU (from the course structure)
>* agent: agent representing the LMS learner being enrolled. This MUST match the actor property generated by LMS at AU launch time.
>* **_registration: Registration ID representing the LMS learner enrollment in the course. This MUST match Registration ID used by the LMS at AU launch time._**
>* stateId: LMS.LaunchData


**Q2. Does the LMS have to use an id representing the course registration as the value of context.registration?**

A2. _Yes it does (as mentioned in A1).  Also see this section_

>9.6.1 registration
>
>The value for the registration property used in the context object MUST be the value provided by the LMS. The LMS MUST generate this value and pass it to the AU via the launch line.
