### ISSUE TITLE
Specified version of xAPI?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#303]
The references section points at:

    "Experience API", current specification, ADL, 2012-2013
    https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md

Do we need to point to a particular version, and/or the year probably ought to be updated otherwise it looks stale as of 2013. Maybe we drop the year completely?

Comment from @bscSCORM:

> yes, but I think we should leave this as an issue until we're close to ready to do a "1.0" release of cmi5, and lock in whatever the latest point release of xAPI is at that point (though I suppose we could just as well reference "1.x.x" ?)

**Comment by MrBillMcDonald** [comment]
Will use xAPI version 1.0.x  - (subject to change just prior to release)

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
