### ISSUE TITLE
IRI Definition Change

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#304]
The IRI definition appears to have copied nearly verbatim language from the xAPI specification in 1.0.2 (or similar) version but that language has changed pretty significantly for 1.0.3, should this be updated here and/or just reference an outside document?

Comment from @bscSCORM:

> We should use the 1.0.3 xAPI language.

Which is (for the moment):

> IRIs always include a scheme. This is not a requirement of this standard, but part of the definition of IRIs, per RFC 3987. What are sometimes called 'relative IRIs' are not IRIs.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
