### ISSUE TITLE
Repeated Course Structure Requirements

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#305]
Ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#60-lms-requirements

There is:

    The LMS MUST support Course Structures as defined in cmi5 Course Structure.

Which probably should point to a section, perhaps 6.1? Which contains:

    The LMS MUST implement the import of the Course Structure defined in Section 13 and Section 14.

Which seems redundant to what was already said above:

    The LMS MUST implement a means to import course structures as defined in Section 6.1.

Similarly there is both:

    The LMS SHOULD implement a means to export course structures as defined in Section 6.1.

And in 6.1:

    The LMS SHOULD implement the export of the course data structure defined in Section 13 and Section 14.

Also it says:

    The LMS MUST support course structures conforming to the XSD schema defined in Section 13.2.

But one of the requirements in Section 13 is:

    All course structures created for LMS import functionality and created by the LMS for export MUST conform to this XSD ...

Condensing these types of requirements would be good to avoid redundancy and potential for edit mishaps (not that these major ones would likely suffer that).

**Comment by MrBillMcDonald** [comment]
Propose specific wording...

**Comment by MrBillMcDonald** [comment]
Change 6.0 and 6.3 as follows:
(Pull Request to be reviewed at next meeting..

6.0 LMS Requirements
LMS requirements to conform to this specification are as follows:
•	Implement an LRS as defined in the xAPI specification.
•	Implement additional "State API" requirements to initialize the AU state as defined in Section 10.
•	Implement the runtime launch interface as defined in Section 8.0 – Content Launch Mechanisms.
•	Implement additional xAPI "Statement API" requirements as defined in Section 9.
•	Implement additional xAPI "Agent Profile API" requirements as defined in Section 11.
•	Implement course structures as defined in Section 6.1.
6.3 LMS Statement API Requirements
The LMS MUST NOT provide permissions/credentials which allow the AU to issue voiding Statements.
The LMS SHOULD reject statements that conflict with the "Statement API" requirements as defined in Section 9.
The LMS MUST Void statements that are NOT rejected AND conflict with the "Statement API" requirements as defined in Section 9.
