### ISSUE TITLE
Relying on conventions for URL

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#307]
Ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#url

"the remaining portion of the URL MUST conform to HTTP/S conventions, such as named value pair parameters"

Relying on "conventions" in a specification like this is likely to cause problems, in particular because conventions allow for non-named pair parameters and several popular web application frameworks leverage them. Need to be more explicit.

Comment from @bscSCORM:

> We should probably just reference the RFC in question here. The intent was more like "this MUST continue to be a valid URL even if whatever scheme was actually used was replaced with http or https"

**Comment by MrBillMcDonald** [comment]
Will reference RFC1738 per November 20th Meeting.
