### ISSUE TITLE
Section 7.0 repeated/confusing requirements

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#309]
Ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#70-au-requirements

In top of 7.0 3rd bullet mentions Statement API which appears to be section 7.2. 4th bullet mentions Agent Profile API, which is then again mentioned (3rd bullet) in section 7.1 which appears to be specifically about the State API which also mentions the Statement API (first bullet).

**Comment by bscSCORM** [comment]
Discussed on today's call, @MrBillMcDonald has the text we discussed and is planning to PR.

**Comment by MrBillMcDonald** [comment]
Will consodilate and remove MUST's per November 20 meeting
