### ISSUE TITLE
Section 8.3 Other Launch Environments

### ISSUE THREAD

**Issue by NickWashburn** [AICC/CMI-5_Spec_Current#31]
We (Jhorlin and Nick at Riptide) met about this a few times this week...

Can we get some input? 
In defining the purpose of launch in other environments. In the web environment launch tells the LMS that the content from the LMS has been delivered to the learner.

In the context of an OS do we want to place strict rules stating that the binary (executable) and the content have to be delivered from the LMS to the learner? Is it sufficient to state that the binary can reside within the OS but the content must be downloaded from the LMS?

Thoughts?

**Comment by MrBillMcDonald** [comment]
This has been discussed and the Browser/URL launch mechanism appears to work in mobile environments so the initial version of CMI-5 will only use the browser environment.  (Later versions may address other operating environments)
