### ISSUE TITLE
HTTP status codes should be specified for success and failure

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#311]
For instance fetch URL returns JSON, Content-Type is specified, but `200` probably should be as well. Errors probably need to be looked at more closely, but being as explicit as possible helps developers and prevents funky things (unless they should be allowed) such as 3xxs.

**Comment by brianjmiller** [comment]
See #342 as well.

**Comment by MrBillMcDonald** [comment]
Closed per  #342
