### ISSUE TITLE
Issues from 2015-10-30 meeting

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#312]
I was going to open an issue that was already covered by a call, but it seems like issues ought to be opened when the meeting minutes are confirmed so that they don't get forgotten. So this is a placeholder for the specified meeting. See https://github.com/AICC/CMI-5_Spec_Current/wiki/CMI-5-Working-Group-Meeting-Minutes-%E2%80%93-October-30th,-2015 in particular the "proposed changes" section.

**Comment by MrBillMcDonald** [comment]
Pull requested applied
