### ISSUE TITLE
Abandoned Statement Duration

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#313]
"The duration property SHOULD be included in "Abandoned" statements. The duration property SHOULD be set as the total session time, calculated as the time between the “Launched” statement and the last statement issued by the AU."

Should this be last request? Should this be specified as a particular type of 'cmi5' statement, or any statement including that registration, etc.?

Comment from @bscSCORM:

> I don't want to get into requiring the LRS to keep track of read accesses and taking them into account here (and for the sake of having systems always behaving the same way, I don't want to leave that as an option either). So I like the time frame being calculated between two statements that were sent to the LRS. Now because it's the session time, I think any statement with the session id included (https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_runtime.md#721-placement-of-session-id-in-statements) should count.

**Comment by MrBillMcDonald** [comment]
Per Nov 13th Meeting - Change

**9.5.4.2 LMS statements that include duration**
Abandoned Statement

>The duration property MUST be included in "Abandoned" statements. The duration property MUST, at a minimum, be set as the total session time, calculated as the time between the "Launched" statement and the last statement (of any kind) issued by the AU. The LMS SHOULD also use other (LMS specific) methods (if available) to determine if the total session time was longer.

**Comment by MrBillMcDonald** [comment]
Pull request applied
