### ISSUE TITLE
Waived verb with reason extension

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#314]
Under 9.3.7 Waived under LMS Obligations it says: 'A statement containing a "Waived" verb MUST include a "reason" in the extension property of the Statement Result.'

But under 9.6 Context it shows this extension in `context.extensions`.

Comment from @bscSCORM:

> result is better, 9.6 should be updated accordingly.

**Comment by brianjmiller** [comment]
9.6.3.2 should be updated as well (probably moved?)

See https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#9632-reason

**Comment by MrBillMcDonald** [comment]
Will move to 9.5 results (per Nov 20 meeting)

**Comment by MrBillMcDonald** [comment]
Proposed changes:
(Pull request to be reviewed at next meeting)

Move 9.6.3.2 to 9.5.5.2 
Update Example to have “reason” in 9.5  (and Remove from 9.6)

**Comment by MrBillMcDonald** [comment]
Per Jan 15th Meeting - fix conflict
