### ISSUE TITLE
9.6.2 - Talks about key/value pairs where it means Activities

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#315]
Ref https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#962--contextactivities

This should be re-worded to capture the fact that what is actually going in the list in `contextActivities.category` is Activities, not just objects with an id value, but see comment below.

Comment from @bscSCORM:

> yes, but carefully. we had language there that talked about activities at one point, but it was confusing because we're really using activities there as a "thing that has an ID we can tag".

**Comment by MrBillMcDonald** [comment]
Remove  the following sentence from "9.6.2 contextActivities":

Each category is tagged with name value pairs of "id" and an IRI.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
