### ISSUE TITLE
Example launch URL should be URL encoded?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#317]
The example here https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#811-launch-method is not URL encoded, for good but not necessarily obvious reason.

Comment from @bscSCORM:

> That's going to get rather hard to read, I'd rather just note that we're not doing so, eg:

`Each value for the associated names MUST be URL-encoded. (not done in this example for readability)`

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
