### ISSUE TITLE
Mastery score/move on in launchdata marked as required

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#318]
But it should only be required when included in the course structure. Look at `launchParameters` for an example of this wording. For `moveOn`, there is a default value suggested in course structure, should that default value be returned in launch data when not provided in the course structure?

Comment from @bscSCORM:

> Yeah, the wording should be changed to match launchParameters. But, for moveOn I do like the AU not having to know the default value, but even so that wording should change to indicate that if no value is specified the default value should be sent.

**Comment by MrBillMcDonald** [comment]
Modify the following  in 10.0 xAPI State Data Model


LMS Required:

If the masteryScore is defined by the course designer in the Course Structure, the LMS MUST include the masteryScore in the State API document.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
