### ISSUE TITLE
Need to update Course Structure refs

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#320]
The ones I noticed were pointing to "Course Structure 7.1.4". There are some that are 7.1.4 AU which are probably the newer ones, essentially all cross document references should be checked to make sure they are still accurate. Probably need some additional anchors to make these cross references easier to use.

**Comment by MrBillMcDonald** [comment]
Search and Replace Course structure section numbers using Section 13 (replace from 7)

**Comment by MrBillMcDonald** [comment]
This issue is address by pull request #385

**Comment by MrBillMcDonald** [comment]
Fixed per PR #385
