### ISSUE TITLE
cmi5 Learner Preferences Empty/Unknown/Unset Value

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#323]
What should an "empty" value be for learner preferences, undefined on the property, `null`?

**Comment by cawerkenthin** [comment]
On other properties, we had decided to simply leave the property out of the JSON.

**Comment by MrBillMcDonald** [comment]
See Section:

4.3 Optional JSON Values
If JSON properties are indicated as "optional", you MAY leave such properties out of the JSON structure being described. All JSON properties included with non-null values MUST be recorded in the LRS.

If something is NOT optional but can be empty – all required elements have a vocabulary and/or default value.
