### ISSUE TITLE
Why is "masteryScore" mentioned in "Passed"/"Failed"?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#326]
Both the "Passed" and "Failed" verb sections include the following:

> The LMS MUST record "MasteryScore" data in the state API (if present in the course structure) for the AU prior to initial AU launch. (See Section 10)

That seems very out of place and is probably covered by either the state API requirements or AU metadata requirements.

**Comment by andyjohnson** [comment]
Per the 12/11/15 call, @brianjmiller  has a PR in (#359).  We discussed the value of MasteryScore = 0 being allowed.  While this is a workaround for broken content, there is a lot of broken content, so it is worth allowing.  Bad content being completely score-focused is a very real thing.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
