### ISSUE TITLE
Should "Failed" have "LMS Obligations"?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#327]
Under "Failed" it is mentioning "Passed"?

> The LMS MUST use either "Passed" or "Completed" statements (or both) for determining course completion (or course collateral credit) criteria for the AU.

This requirement is already listed under "Passed".

**Comment by andyjohnson** [comment]
Per the 12/11/15 call, It is redundant.  We are agreeing to get rid of it.  This fine because there is no action for the LMS to take on a failed.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
