### ISSUE TITLE
Conflicting language around multiple "passed"/"failed"

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#328]
The requirement that:

> More than one of the set of {"Passed","Failed"} verbs MUST NOT be used (in cmi5 defined statements)

Seems to conflict with the language in the individual verb sections reading:

(Passed)
> The AU MUST NOT issue multiple statements with "Passed" for the same AU within a given AU session or course registration for a given learner.

(Failed)
> A "Failed" statement MUST NOT be issued after a "Passed" statement has been issued.

The latter two without the first implies you could do "Failed", "Failed", "Failed", ... "Passed"

**Comment by bscSCORM** [comment]
We decided to remove this language in the pass/fail verbs themselves, leaving the general statement in place.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
