### ISSUE TITLE
"Abandoned" shouldn't indicate pass/fail

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#330]
Ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#952-success

Having "Abandoned" set `result.success` to `false` is at odds with the possible pre-existence of a "Passed" statement. And eliminates the possibility of being "passed but not completed".

**Comment by andyjohnson** [comment]
Per the 12/11/15 call: Remove language indicating that Abandoned verbs should indicate failure.  Discussed whether or not certain results(for non-extension properties) should be prohibited from cmi5-definted Statements where the LRS wouldn’t react to them. Agreed that:  A cmi5 defined Statement MUST NOT use result properties not specified for that particular Verb except in the case of extensions.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
