### ISSUE TITLE
"Failed" shouldn't indicate completion

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#331]
Ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#953-completion

Having "Failed" set `result.completion` to `false` is at odds with the possible pre- or post-existence of a "Completed" statement and eliminates the possibility of "failed but completed".

**Comment by andyjohnson** [comment]
Per the 12/11/15 call, Agree that completed is not relevant to a failed Statement.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
