### ISSUE TITLE
Need to get ADL to host the CourseStructure.xsd

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#337]
http://www.adlnet.gov/cmi5/CourseStructure.xsd doesn't resolve.

**Comment by svrnm** [comment]
Side note: XML does not require that the url used for xmlns does exist. Quote from [Wikipedia](https://en.wikipedia.org/wiki/XML_namespace#Namespace_names):

> The Namespaces specification does not say what should happen if such a URL is dereferenced (that is, if software attempts to retrieve a document from this location)

But of course, it would be better to have it.

**Comment by jhaag75** [comment]
If someone can provide me with the schema I will set it up to resolve  from the ADL server.

**Comment by andyjohnson** [comment]
The IRI should be w3id instead, and get that up as fast as possible.  The resolution of that IRI can be at ADL.

**Comment by jhaag75** [comment]
Sure, but does coursestructure.xsd even exist?

**Comment by brianjmiller** [comment]
@jhaag75 kind of, right now it exists in the `cmi5_spec.md` directly and has to be copied out, pending resolution of #346.

**Comment by brianjmiller** [comment]
ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#course_structure_xsd

**Comment by jhaag75** [comment]
10-4 thanks Brian. Is the schema finalized? If not, would you all like me
to go ahead and set this up?

-------------------------------------------------------
+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by brianjmiller** [comment]
Not finalized, I have a change I'm about to PR that changes it.

**Comment by jhaag75** [comment]
I uploaded the current version of the file to the ADL vocab server. When you guys have an updated version let me know and I'll replace the .xsd currently on the server. In the meantime, I set up two redirects:

A text/html GET on the base course schema namespace IRI (https://w3id.org/xapi/profiles/cmi5/CourseStructure) without the extension redirects user to the project page:
https://github.com/AICC/CMI-5_Spec_Current

An application/xml GET request on the schema namespace returns the schema:
https://w3id.org/xapi/profiles/cmi5/CourseStructure.xsd

The targeted URL for redirect can be updated by anyone in the cmi-5 community that forks the w3id repo & pull request. https://github.com/perma-id/w3id.org

**Comment by MrBillMcDonald** [comment]
Per Jan 22nd meeting.  

The following actions are needed:

#1 - XSD Files need to be uploaded to the cmi5 github REPO.  
#2 - The specification needs to be changed to reference the XSD 
#3 - XSD should be removed and externally referenced (and the separate files should be packaged in any distribution).

**Comment by MrBillMcDonald** [comment]
Change the location: 

From 

https://w3id.org/xapi/profiles/cmi5/CourseStructure.xsd


To 

https://w3id.org/xapi/profiles/cmi5/v1/CourseStructure.xsd


Per Feb 26 meeeting

**Comment by jhaag75** [comment]
Thanks! Traveling today but will update this ASAP.

**Comment by MrBillMcDonald** [comment]
Closed per March 11 meeting
