### ISSUE TITLE
AU "authenticationMethod" items

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#341]
Under the AU "authenticationMethod" item the Usage includes:

> Based on the value of authenticationMethod, the LMS will place a parameter in the AU launch interface to indicate to the AU which authentication method to use (in accordance with the cmi5 Runtime Specification)

* Presumably should remove "Runtime Specification" if no other changes are made
* What parameter corresponds to this requirement, is `fetch` enough to cover this? My understanding would be that `fetch` would still be used even if additional authentication methods were added in the future. So the alternative seems to be to remove this language, and *potentially* add a property to the response to the POST fetch request that includes the type of token being returned (for now the only acceptable value being "Basic").

In the same block for the second bullet point there is an "If the LMS indicates..." but there is no secondary clause indicating otherwise (since there isn't really an "otherwise"). Just need to adjust the language.

Finally this issue prompted an internal discussion with @bscSCORM about whether `authenticationMethod` should stay in the Course Structure at all, and what that means as far as whether or not the AU is dictating the type of authentication that it *must* use and/or expects to use, and how the LMS must treat that in the case that it doesn't support said authentication method presuming there are ever optional authentication methods. Which also led to a discussion of whether or not the course structure needs to include a version string to allow for future expansion or perhaps this is covered by reference to the xsd which itself should be versioned?

**Comment by andyjohnson** [comment]
The proposed changes are agreed upon.  Then decided that we would be in favor of removing authenticationMethod from the Course Structure.

**Comment by MrBillMcDonald** [comment]
Closed per Jan 15th Meeting
