### ISSUE TITLE
8.2.3 Errors needs HTTP status code specification

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#342]
Ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#823-errors

Is the LMS open to use any normally acceptable HTTP status code for response to errors? The JSON payload itself indicates errors so I could see some wanting to return a `200` as the status code because the request was otherwise acceptable and there is a "valid for cmi5" response, while I'd lean towards using a combination of 400 and 401 depending on the condition generating the error.

**Comment by MrBillMcDonald** [comment]
Change to  per Nov 13th meeting: 


>The LMS MUST place the value for auth-token in a JSON structure, as shown in Section 8.2.1, in its response to a fetch URL request. The response MUST have a Content-Type of "application/json".  The HTTP status code MUST be “200” for a valid request (including one that generates error as described in section 8.2.3).

**Comment by MrBillMcDonald** [comment]
Pull request applied
