### ISSUE TITLE
.Zip Application Note

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#345]
Should `https://www.pkware.com/support/zip-app-note` be included in the https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#references?

**Comment by cawerkenthin** [comment]
:+1:

**Comment by andyjohnson** [comment]
Group on 1/7/2016 :+1:

**Comment by MrBillMcDonald** [comment]
Per Jan 22 meeting - will add ISO reference to 2.0 References

ISO/IEC 21320-1:2015(en) Information technology — Document Container File — Part 1: Core (Commonly called ZIP file format:

https://www.iso.org/obp/ui/#iso:std:iso-iec:21320:-1:ed-1:v1:en
