### ISSUE TITLE
Examples and xsd moved to separate files and linked?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#346]
During implementation and for hosting purposes seems like the xsd file contents themselves should exist as a separate file. Implementers could then just copy it into place.

Moving the examples out into separate files would also allow implementers of import to use them as test files to make sure their implementation is at least conformant with the examples (knowing that they don't launch).

These changes also make the specification more easily printable.

**Comment by svrnm** [comment]
100% agree. I created a repository holding those files for my private use: https://github.com/svrnm/CMI5-CourseStructure-Testing ... the big advantage is, that you can directly write and validate files.

**Comment by andyjohnson** [comment]
Per the 1/7/2016 call, will keep versions in this GitHub for PRs (these will be the authoritative versions) ids will continue to be ADL and be hosted there.

**Comment by MrBillMcDonald** [comment]
Per Jan 22nd meeting - See Issue #337

**Comment by brianjmiller** [comment]
This was as much about the examples as the xsd. I've opened PR for the xsd but I'd like this re-opened to address the examples too. I'll try to get to that but it is less priority at the moment.
