### ISSUE TITLE
Should the precision of the `masteryScore` be explicit?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#358]
Presumably we take a page from the xAPI specification here? Best I could find:

> The LRS MUST process and store numbers with at least the precision of IEEE 754 32-bit floating point numbers.

(ref: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#lrs-requirements-3)

**Comment by andyjohnson** [comment]
Per the 1/6/2016 call, an LRS will NOT be required to support decimal places beyond 3 decimal places (thousandths) for mastery score.  The group thought keeping a strange threshold to a score is not likely enough for the interoperability headaches.

**Comment by MrBillMcDonald** [comment]
Per Jan 22 Meeting change definition of masteryScore as follows :

**9.6.3.2 masteryScore**  and **13.1.4 AU Metadata**

Value space:	Decimal value between 0 and 1.  With 3 decimal places of precision.


\
