### ISSUE TITLE
Specify AU must be unique in course structure

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#360]
There are a number of current requirements around sending statements (such as "completed") that restrict it to one per AU per course registration, which effectively means an AU should be unique in a course structure.

**Comment by cawerkenthin** [comment]
Agree.  I cannot think of a good reason to have the same AU appear more than once in a course.

**Comment by andyjohnson** [comment]
Per the 1/7/2016 call, all :+1:

**Comment by MrBillMcDonald** [comment]
Per Jan 22 Meeting:


**13.1.4 AU Metadata**

Data type: IRI	Description: A globally unique IRI that the AU uses to identify itself to the LMS in xAPI requests to the LRS.  The id MUST be unique within a course structure.
