### ISSUE TITLE
LaunchMode captured in Launched Statement

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#361]
There is (AFAICT) no way to currently determine the launch mode used for a given session. The only requirements on the AU are to send "initialized" and "terminated" statements for each session which means there is no way to differentiate two sessions as occurring in different modes.

I propose adding a context extension to the "launched" statement that includes the launchMode value. (And will PR as such in the nearish future.)

**Comment by andyjohnson** [comment]
Per the 1/07/2016 call, see some value putting this in.  Better to put it in now than later.  Makes sense in that a stream of Statements could benefit from knowing the mode the user is in.

**Comment by brianjmiller** [comment]
Seems `masteryScore` and any other overridden launch data might need similar inclusion.

**Comment by brianjmiller** [comment]
Seems `masteryScore` and other overridden launch data should be included as well.
