### ISSUE TITLE
New GitHub label for "PR'd"?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#372]
We have "consensus needing PR" but no way to label that a PR has been submitted, should we? Would it be helpful to someone managing the repo to have that without the ability of the PR submitter to be able to set it?

**Comment by andyjohnson** [comment]
I think we'll be okay once we get Bill back or I take over merging PRs.  Art pointed out that we'd then need to tag all issues once they are PRed.  If we aren't doing a good job with PRs, I don't think we will with tagging either :)

**Comment by brianjmiller** [comment]
Fair enough, I really wish GitHub itself would take care of this for us.
