### ISSUE TITLE
Question: easiest way to get a batch of example statements?

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#381]
Hi,
Is there an easy way for me to get a batch of example cmi5 statements? Any prototypes or anything like that?

Andrew

**Comment by brianjmiller** [comment]
I can email you a set or two. Will that work?

**Comment by garemoko** [comment]
Yep, that'd be great. Or I can give you an endpoint to fire them at. Whichever is easiest for you.

**Comment by brianjmiller** [comment]
These were sent offline, @garemoko are you good now?

**Comment by MrBillMcDonald** [comment]
Will followup is necessary

**Comment by garemoko** [comment]
All good. Thanks!
