### ISSUE TITLE
Session id language should just be "cmi5 defined statements"

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#382]
Ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#9631-session-id

> The LMS MUST also provide the session ID in the context as an extension for all Statements (with cmi5 defined verbs) it makes directly in the LRS.

And

> An AU MUST include the session ID provided by the LMS in the context as an extension for all Statements (with cmi5 defined verbs) it makes directly in the LRS.

I think this should just be listed as "cmi5 defined statements" because elsewhere we've said the AU can use the same verbs as defined statements for allowed statements (unless I've read that wrong).

**Comment by cawerkenthin** [comment]
@brianjmiller I disagree.  If I want to fetch all statements (allowed and defined), I can use sessionId as a filter.  An AU may re-use verbs during a session as long as they are not cmi5 defined, which means they drop the cmi5 context activity, not the sessionId.

**Comment by brianjmiller** [comment]
There was a fair amount of discussion on the call today (01/29) about this. To clarify a bit:

The key distinction here is that the spec effectively says the AU must include the session id in *all* statements that use a verb within the defined set of cmi5 verbs, as opposed to saying that the session id must be included in statements that will include the cmi5 category ("cmi5 defined" statements).

So, my initial thinking is that we intend to make it so that all of the cmi5 defined statements get the session id, but not place a restriction on the AU for non-cmi5 defined statements *but* with a defined verb. If we want to go so far as to say *every* statement generated by the AU (defined, allowed, or other) includes the session id then, while I wouldn't be in favor of it, I could understand it. But I don't see what limiting the requirement to only those verbs we've already mentioned but *aren't* the actual cmi5 defined statement gives us.

@bscSCORM's recommendation just before I had to sign off the call I rather liked, which was essentially have a MUST that the session id is included in "cmi5 defined statements" and a SHOULD that it be included in other statements (or perhaps "cmi5 allowed" statements?). If we go down anything more strict then this then we start to limit the capabilities of the AU, for instance is it allowed to send statements about a different actor? Obviously they wouldn't be relevant for scoring, or the session, can't be "cmi5 defined", etc. but I don't think we should go so far as to limit *all* statements.

**Comment by davidpesce** [comment]
> 
...have a MUST that the session id is included in "cmi5 defined statements" and a SHOULD that it be included in other statements (or perhaps "cmi5 allowed" statements?).
> 

Agreed.

**Comment by brianjmiller** [comment]
This also may have an exceptional case see #392.

**Comment by MrBillMcDonald** [comment]
Close per FEb 26 meeting
