### ISSUE TITLE
masteryScore is missing from example json in 9.6

### ISSUE THREAD

**Issue by cawerkenthin** [AICC/CMI-5_Spec_Current#388]
The masteryScore was added for passed and failed statements in 9.6, but was not added to the sample json.

**Comment by brianjmiller** [comment]
Should an optional value be included in the samples, I guess some of them already are?

**Comment by cawerkenthin** [comment]
Reason is already included.

**Comment by MrBillMcDonald** [comment]
Add MasterySCore & Launch Mode to 9.6 example - per Feb 26th meeting
