### ISSUE TITLE
Can score be sent in multiple statements? If so, what does that mean?

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#390]
I have similar questions to #389 but for score. I can see that score is optionally included with passed/failed but can it be included in other cmi5 statements? Is there any direction for non-cmi5 statements?

In fact, this is a duplicate of this closed issue: https://github.com/AICC/CMI-5_Spec_Current/issues/263 I can't see how #263 was resolved and what the answer was. The PR that closed #263 doesn't make this clear to me. 

I'd like cmi5 to say something along the lines of: "If multiple scores are sent for a session, then the score in the statement with the latest timestamp is considered the final score. AUs sending score data in multiple statements are encouraged to provide accurate timestamps to ensure the correct statement order, and not to provide multiple differing scores for a session in two or more statements that share a timestamp."

**Comment by brianjmiller** [comment]
Hopefully with my various PRs resolved there should only ever be one score sent *per session* for *cmi5 defined* statements. Non-cmi5 defined statements can send a score but can't affect the overall scoring for the session. With the wording saying that additional properties can't be included in the result (aka 'score') unless specified, and with the statement that there may only be one passed or failed statement then this should now be covered. I've not gone back through post PR merge for an additional review, so it  should certainly be confirmed.

**Comment by brianjmiller** [comment]
See #374.

**Comment by garemoko** [comment]
@brianjmiller thanks for directing me to that, that's helpful. Is there a reason why the cmi5 defined progress extension shouldn't be covered by the same rules? Shouldn't it be properties not covered by cmi5 rather than extensions?

Back to score, what's the best way to filter cmi5 defined and non-cmi5 defined statements; I guess in this case I should look to filter for either passed or failed and take the score from that statement?

**Comment by brianjmiller** [comment]
@garemoko I didn't follow your first question, can you elaborate or reword?

"cmi5 defined" statements have a specific `context.contextActivities.category` with id "https://w3id.org/xapi/cmi5/context/categories/cmi5" (see https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#714-types-of-statements) so filter first on that id, then for "passed"/"failed" for a given `object.id` and `registration`.

**Comment by brianjmiller** [comment]
Note I slipped a wording change in there, "passed"/"failed" are supposed to be per AU per *registration* not per session.

**Comment by garemoko** [comment]
Thanks @brianjmiller.

To clarify my question, the new text in #374 says "A "cmi5 defined" statement MUST NOT use result properties not specified for that particular verb except in the case of result extensions." 

Why is it except in the case of result extensions, rather than except in the case of properties (extensions or otherwise) not covered by cmi5? Progress is a cmi5 defined result extension and it seems to me that it shouldn't be excluded.

**Comment by brianjmiller** [comment]
The intention is that the properties of Result may not be included unless they've been specified by the cmi5 spec, IOW it is saying you can't include `completion` unless it is with a verb that allows for that property. The exception being that you can include `extensions` (progress or others) whenever you like. So "MUST NOT" include *result* properties unless allowed, except (always allow) "extensions".

Is that not how you read it? I still don't think I'm following.

**Comment by garemoko** [comment]
Yes, that's how I read it. But in addition to that progress is an extension that's defined by cmi5. Why shouldn't that be restricted?

**Comment by brianjmiller** [comment]
Restricted how? Per #389?

**Comment by garemoko** [comment]
So that it would only be sent with certain statements, like result properties. Maybe it doesn't need to be, i'm not up on the details of cmi5, but it seems weird to restrict score but not progress.

**Comment by brianjmiller** [comment]
Okay, yes, that I think is covered in #389 and needs to be discussed.

**Comment by MrBillMcDonald** [comment]
Per March 11 meeting, score usage is covered in the following section (and only Passed and Failed cmi-5 defined verbs can use it.  cmi-5 allowed statements can also use score)

(The other issue with the progress extension is resolved)

9.5 Result

Result may be present in a statement depending on the cmi5 verb used. A "cmi5 defined" statement MUST NOT use result properties not specified for that particular verb except in the case of result extensions.
