### ISSUE TITLE
"Waived" uses session language what does that look like?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#392]
Under the "LMS Obligations" cell for the "Waived" verb there is the following:

> The LMS MUST NOT issue multiple statements with "Waived" for the same AU within a given AU session or course registration for a given learner.

Presumably this is copy paste error because "Waived" can occur outside of a session? Can an AU do something that triggers the "waiver" within a session? If waiver occurs only because of LMS initiated actions does the "Waived" statement include a session id?

In general I think the requirements for handling "Waived" need to be looked at closely.

**Comment by MrBillMcDonald** [comment]
Change Section 9.3.7 Waived as follows: (Per Feb 25th meeting)

**LMS Obligations**	

The LMS MUST use this verb in a statement recorded in the LRS when it determines that the AU may be waived. A statement containing a "Waived" verb MUST include a "reason" in the extension property of the Statement Result. (See Section 9.5.5.2) The LMS MUST generate a unique session id for the statement containing a "Waived" verb and MUST NOT issue any other statements using that session id.  The LMS MUST NOT issue multiple statements with "Waived" for the same AU within a course registration.

**Comment by MrBillMcDonald** [comment]
#414 merged and smart quotes separately fixed.  

Approved Per March 4th Meeting
