### ISSUE TITLE
Is "Satisfied" recorded for AU's with a "NotApplicable" "moveOn"?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#394]
Under https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#moveon for "NotApplicable" the requirements read:

> The LMS will consider the AU satisfied.

Does this trigger recording of a "Satisfied" statement for containing blocks/courseStructures? When does that statement get recorded? Should there be a "Launched" possible "moveOn" value such that the satisfied condition gets met on launch of the AU? Should AUs themselves get a "Satisfied" statement?

**Comment by MrBillMcDonald** [comment]
Per the March 11 Meeting the the group determined that the real questions is "what events trigger the LMS to evaluate the MoveOn rules ?"   This will require further discussion to clarify MoveOn usage in the specification.

**Comment by MrBillMcDonald** [comment]
Per the March 25th meeting the following section will be change to address this issue:

**9.6.1 registration**

> The value for the registration property used in the context object MUST be the value provided by the LMS. The LMS MUST generate this value and pass it to the AU via the launch URL.  At the time of registration, the LMS MUST evaluate MoveOn criteria in the course structure.  For example, Blocks with MoveOn criteria of “Not Applicable” in the course structure would be evaluated and could generate Satisfied statements at this time.
