### ISSUE TITLE
"LaunchMode" requirement needs to be more strict?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#397]
The `LaunchMode` requirements are currently fairly loose on the LMS side only indicating that:

> The launch mode determined by the LMS.

And what it indicates to the AU (that it *shouldn't* be sending certain types of statements, etc.) However that "SHOULD" is really at odds with the requirements around not storing multiple pass/fail/complete statements. We discussed internally adding a requirement that is effectively:

> The LMS MUST use "Review" mode when pass/fail and completion have already been determined.

This would only be at odds with allowing "Browse" in that case, because "Normal" need not be used because results shouldn't be submitted (and can't be stored) anyways. If we want to allow the "Browse" case then it could be softened to:

> The LMS MUST NOT use "Normal" mode when pass/fail and completion have already been determined.

**Comment by bscSCORM** [comment]
"Browse" doesn't seem to make sense for passed/failed/completed AUs, but if we did want to allow it the second requirement makes sense. I prefer the first suggested requirement, because "Review" is the only mode that seems to make sense for passed/failed/completed content.

**Comment by cawerkenthin** [comment]
@brianjmiller I assume this is within the same registration only?

**Comment by brianjmiller** [comment]
@cawerkenthin yes, well, assuming that is how the language around pass/fail and complete works. I didn't check that. My suggestion is just that LaunchMode determination depends on them, hopefully (read: I didn't check) we already have indicated they are per registration, and consequently this would be too.

**Comment by MrBillMcDonald** [comment]
Per April 8th, meeting.  We may need information language but no normative language.  No action required
