### ISSUE TITLE
Define Activity Type for Blocks and Course Structure

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#408]
I think it'd be wise for us to define an Activity Type xAPI term for use in Satisfied statements' `object` Activity Definition. For AUs this is AU dependent, but for blocks and the course structure it is effectively cmi5 scoped.

It may be that `http://adlnet.gov/expapi/activities/course` and `http://adlnet.gov/expapi/activities/module` are already sufficient. If they are then we should specify that they be included, if not then we should add new terms.

**Comment by brianjmiller** [comment]
To be clear, AUs specify their Activity Type via the metadata in the Course Structure file. I would use `http://adlnet.gov/expapi/activities/module` for blocks as the definition indicates that it is for "aggregations that are not a course" and then naturally "http://adlnet.gov/expapi/activities/course" for the course.

**Comment by MrBillMcDonald** [comment]
Per April 8th Meeting - Define cmi5 activity types for "Course" and "Block" and require them in LMS statements for Satisfied.

**Comment by cawerkenthin** [comment]
This issue should be closed as the pull request is merged into the spec already.

**Comment by brianjmiller** [comment]
I think it was being left open as a placeholder so that we know that Jason H (or someone with authority) has setup the metadata.

**Comment by brianjmiller** [comment]
The two new terms were:

https://w3id.org/xapi/cmi5/activitytype/block
https://w3id.org/xapi/cmi5/activitytype/course

**Comment by cawerkenthin** [comment]
Makes sense, thanks @brianjmiller

**Comment by brianjmiller** [comment]
Closing in favor of #473
