### ISSUE TITLE
Complex course structure example has blank objective

### ISSUE THREAD

**Issue by cawerkenthin** [AICC/CMI-5_Spec_Current#410]
In the complex course structure example, is it intentional that the objective  "http://courses.example.edu/identifiers/objectives/" has blank values for all elements?

**Comment by MrBillMcDonald** [comment]
Per April 18th Meeting

Remove as not referenced (and incorrectly empty)


 <objective id="http://courses.example.edu/identifiers/objectives/">
      <title>
        <langstring></langstring>
      </title>
      <description>
        <langstring></langstring>
      </description>
    </objective>
  </objectives>
