### ISSUE TITLE
Explicitly allow the LMS to override the masteryScore, LaunchParameters, and moveOn

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#424]
(Because the LMS has the ability to edit course structure...)

The Spec need to explicitly specify that the LMS can override the masteryScore, LaunchParameters, and moveOn.  And that the AU must provide the values (as they were at Launch Time) for the properties in the context of Launched Statements.

**Comment by MrBillMcDonald** [comment]
Change per May 6th Meeting as follows:

> **10.0 xAPI State Data Model**
> **masteryScore**
> LMS Usage:	If a "masteryScore" is present in the course structure the LMS must provide a masteryScore in the state API document. The masteryScore value written in the State API Document MAY change (e.g. based on administrative rules defined by the LMS.)

**Comment by MrBillMcDonald** [comment]
Per May 20th Meeting,  Will add the following to this pull request to resolve outstanding issues raised:

>**10.0 xAPI State Data Model**
>
> **masteryScore**
> 
> **LMS Usage:**	
> 
> If a masteryScore is present in the course structure the LMS MUST provide a masteryScore in the State API document. The masteryScore value written in the State API Document MAY be different than the one in the course structure (e.g. based on administrative rules defined by the LMS).

> **moveOn**
> 
> **LMS Usage:**	
> 
> The LMS must provide a moveOn value in the state API document. The moveOn value written in the State API Document MAY be different than the one in the course structure (e.g. based on administrative rules defined by the LMS)


> **launchParameters**
> **LMS Usage:**	
> The LMS MUST provide a launchParameters value in the state API document. The launchParameters value written in the State API Document MAY be different than the one in the course structure (e.g. based on administrative rules defined by the LMS).

> **9.6.3.2 masteryScore**
> **Description:**
> "masteryScore" as provided in the LMS Launch Data for AU plus registration used to determine the pass/fail result based on score.
>

**Comment by brianjmiller** [comment]
#470 has been updated per the changes from meeting on 05/20.

**Comment by MrBillMcDonald** [comment]
Merged #470 per May 20th meeting...
