### ISSUE TITLE
Duration Calculation (abandoned session) - June 7th Meeting

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#43]
Duration
•	Normal Calculation of Duration – Time between “Started” and “Exited” statements
•	Calculation for Duration in an “abandoned session” – Time between the “Started” statement and the last statement issued by the AU.

**Comment by MrBillMcDonald** [comment]
Issue resolved

**Comment by andyjohnson** [comment]
Just need to add in the abandoned language
