### ISSUE TITLE
publisherId should be a Context Activity

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#431]
One of the key benefits of including a "publisher id" as a solution to #378 was that it would be possible to filter the statement stream based on that id so that statements could be retrieved that were relevant even across LMSs that generated their own different identifiers. By making it an extension we (likely) inadvertently removed this ability or at least made it significantly more difficult to do (can't be done at the LRS level) and therefore less usable.

Suggestion is to switch the "publisher id" extension value (the id) to be a full Activity and store it in the `context.contextActivities.grouping` list. This has the added benefit that the LMS can record a full Definition object based on the contents of the course structure which allows comparison to what the LMS has altered those values to.

**Comment by bscSCORM** [comment]
:+1:

**Comment by MrBillMcDonald** [comment]
Per April 8th Meeting publisher id will be moved to context activities.
