### ISSUE TITLE
Multiple Passed/Failed, Completed within a Registration for an AU and MoveOn

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#432]
Figured out why the discussion on Friday (April 8) bothered me so much, I think we ended up with an unintended change to the handling of passed/failed and completed which has possible implications on MoveOn handling.

I've been under the impression (right or wrong which is really the key point of discussion) that Passed/Failed and Completed could only be captured a single time per AU *per registration*. On Friday it was indicated that this wasn't the case and that those were *per session*. This seems to be the case *at the moment* for Passed/Failed but not Completed.

So based on my research it seems the following occurred:

1. On 2015/10/23 the language for the set of Passed/Failed was added for Session ordering rules, but at that time the wording was already in the specification under Passed and Failed that indicates: "The AU MUST NOT issue multiple statements with "Passed" for the same AU within a given AU session or course registration for a given learner."
2. On 2016/01/15 PR #373 was merged which removed the supposedly redundant language listed in 1 above, but the problem is that changed requirements as the language that was supposedly redundant was referencing a session not a registration. This leads to the ability to have multiple passed/failed statements within a single registration which then impacts MoveOn determination and leaves in question Satisfied statement handling.
3. Currently Completed must be unique at the registration level, see 9.3.3 "The AU MUST NOT issue multiple statements with "Completed" for the same AU within a given AU session or course registration for a given learner."

So, some questions that need to be resolved:

1. What is our actual intention, are Passed/Failed intended to be unique at the *session* or *registration* level?
2. Depending on the answer to the above is Completed intended to be unique at the *session* or *registration* level? Presumably it has to match that of Passed/Failed to properly handle the CompletedAndPassed MoveOn value.
3. If multiple Passed/Failed statements are possible for a registration, do we define how MoveOn is affected when an AU moves from Passed to Failed? If Satisfied statements have already been recorded at the Block and/or Course level what happens? This could necessitate hardening the rules around the LaunchMode that we left soft on this Friday call. Is there a reason to restrict them at all within a session if not at the registration level?

**Comment by brianjmiller** [comment]
Note related language in "Satisfied" statement section: "The LMS MUST NOT issue multiple statements with "Satisfied" for the same AU within a given AU session or course registration for a given learner."

**Comment by MrBillMcDonald** [comment]
Good questions !  Here is my take....

**Q1. What is our actual intention, are Passed/Failed intended to be unique at the session or registration level?**
A1.  It appears that it is intended to be at session level.   We may need to re-assess if should be at registration level.

**Q2. Depending on the answer to the above is Completed intended to be unique at the session or registration level? Presumably it has to match that of Passed/Failed to properly handle the CompletedAndPassed MoveOn value.**

A2.  Session Level. Although the Completed and Passed verbs could span different sessions (for the same learner) in the same registration.  The LMS would make the the moveon determination after both conditions transition to true.

**Q3. If multiple Passed/Failed statements are possible for a registration, do we define how MoveOn is affected when an AU moves from Passed to Failed? If Satisfied statements have already been recorded at the Block and/or Course level what happens? **

A3.  I think that the moveOn initiated satisfied should not "reverse" itself.  The LMS (not the AU) should be the final authority of whether the learner has mastered/completed the course/registration. 

**Q4. This could necessitate hardening the rules around the LaunchMode that we left soft on this Friday call. Is there a reason to restrict them at all within a session if not at the registration level?**

A4. Not sure I understand this question.  Launch mode is a directive by the LMS to the AU telling it what types of CMI5 verbs to use for given situation.  It is up to the LMS to determine what launch mode it issues based on its UI.  The LMS is "running the show" when it comes to navigation between AUs and directives to the AU.

**Comment by MrBillMcDonald** [comment]
Per April 15th meeting:

(All are MUSTs) 

1. Passed & completed are **Registration** specific.  (only one completed & passed per registration allowed)

2. Failed is **session specific** (because its up to the LMS to determine how many times you can fail)

3. (AU) Failed is not allowed after Passed (registration specific)

Violations are either Rejected or Voided.

**Comment by cawerkenthin** [comment]
Pull request posted #458

**Comment by MrBillMcDonald** [comment]
Closed per May 6th meeting

**Comment by MrBillMcDonald** [comment]
See pull request #458
