### ISSUE TITLE
Section 9.4 the Object of a Satisfied statement is not the AU

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#434]
Section 9.4 includes:

> The Object in a cmi5 defined statement represents the AU.

In Satisfied statements the `object` represents a Block or the Course.

**Comment by cawerkenthin** [comment]
Agree.  The satisfied statement's object should be either a block or a course.

**Comment by MrBillMcDonald** [comment]
Per April 22nd meeting, remove 9.4,1, 9.4.2, and change 9.4 as follows:

> **9.4 Object**
>
> An Object MUST be present, as specified in this section, in all statements with cmi5 defined verbs.  
> Except for Statements with the Satisfied verb, the Object in a cmi5 defined statement represents the AU.  In Satisfied Statements, the Object represents a Block or Course.
> The value of the Object's "id" property for a given AU MUST match the AU ID (activityId) defined in the launch URL except for Satisfied statements.  (See Section 9.3.9)
>

**Comment by cawerkenthin** [comment]
#445

**Comment by cawerkenthin** [comment]
This can be closed as #445 was merged.
