### ISSUE TITLE
Section 9.4.1 should use "cmi5 defined statements" rather than "cmi5 verbs"

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#435]
> The objectType property of an Object in statements with a cmi5 verb MUST be set to "Activity".

Although it is unlikely, it is at least allowable by the verb itself (and xAPI) that the same verb be used in a statement that does not include the cmi5 category Activity (a cmi5 allowed statement) and use an "object" that is not an "Activity".

Having said that, it *could* be intentional that we want to restrict cmi5 allowed statements using a verb from the cmi5 defined set to always require an "Activity". (Key point being "intentional" here. And I consider this issue being resolved as documenting that intention.)

**Comment by MrBillMcDonald** [comment]
Per April 22nd meeting change the following section:

> **9.4.1 objectType**
>
> The objectType property of an Object in cmi5 defined statements MUST be set to "Activity".
