### ISSUE TITLE
9.6 Context Sample JSON isn't possible

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#439]
The sample JSON at the top of [section 9.6 Context](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#context) isn't possible as it stands. It is a MoveOn based statement (so Passed/Failed/Completed, etc.) but contains the "launchMode" extension. Perhaps it would be best to just remove the "launchMode" from the example and add informative language about what kind of sample it is. Having said that, I think it begs the question again of whether any of the samples are that helpful, and if it might be better to generate a set of sample statements to be included as examples outside the specification itself?  (See #381)

**Comment by MrBillMcDonald** [comment]
Per April 22nd meeting :

Remove examples  (Json and State API).  Create an examples document for the cmi5 repo.

Simple Sample course structure with different sessions scenarios per AU

Complete set of statements for each session type:
•	Sample statements for Launched, Terminated Session
•	Launched, Abandoned Session
•	Normal, Scored session
•	Completed Session Then passed Session
o	Satisfied example
•	Waived Example

Associated StateAPI Document Examples

Show examples in Sequence

**Comment by MrBillMcDonald** [comment]
May 27th Meeting

Closed per Pull Request #481
