### ISSUE TITLE
launchParameters Data Type/Value Space should be "String"

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#440]
Right now in section 10 State API under `launchParameters` the Data Type and Value Space are set as:

> Defined by the course designer.

Which doesn't really work from an implementation view point. Essentially it most likely just needs to be "String" or potentially "String, whose format is up to the course designer". Ultimately this value comes from the XML course structure which makes it difficult to recognize it as anything but a string, to do so it would have needed to be encoded as a string in that document and then we'd need a content type to go along with it, and beyond that it would need to be serializable to JSON for both state and the statement extension.

The Sample Value in that same table shows an example of JSON itself (outside of a string enclosure) which is why I recognized this problem in the first place. If we want to continue to keep it as an example value it should be quoted (assuming we decide it must be a string) to show that it is just a string.

**Comment by MrBillMcDonald** [comment]
Per April 22nd meeting - change value space to "string" and remove example
