### ISSUE TITLE
Satisfied session id in case of NotApplicable moveOn

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#443]
Under session id we have:

> The LMS MUST also provide the session ID in the context as an extension for all "cmi5 defined" and "cmi5 allowed" statements it makes directly in the LRS.

Which therefore includes Satisfied statements, however in the case of automatic satisfaction of moveOn for AUs with NotApplicable occurring at registration creation time per #422, there is no active session. Should the LMS create a session id in that case similar to what it does for Waived?

**Comment by MrBillMcDonald** [comment]
Per the April 29 the meeting change as follows:

> **9.6.1 registration**
> The value for the registration property used in the context object MUST be the value provided by the LMS. The LMS MUST generate this value and pass it to the AU via the launch URL. At the time of registration, the LMS MUST evaluate MoveOn criteria in the course structure. For example, Blocks with MoveOn criteria of "Not Applicable" in the course structure would be evaluated and could generate Satisfied statements at this time.
> For all Satisfied statements triggered outside of an AU launch session, the LMS MUST generate a unique session id and use it for all of those statements.
>

**Comment by MrBillMcDonald** [comment]
Per the May 13th Meeting, the group agreed to add the following change to address the concern over AU launch triggered moveOn:

> 
> **9.3.9 Satisfied**
> 
> **LMS Obligations** 
> 
> For all “Satisfied” statements triggered as a result of an AU launch session, the LMS MUST use the session id from the AU launch and use it in the statements

.
