### ISSUE TITLE
LaunchMethod not included in AU metadata in samples, includes default in course structure

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#444]
The AU `launchMethod` metadata section (see [13.1.4](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#au_meta_data)) indicates that it is required but the course structure schema provides for a default value of 'AnyWindow' (see [line 79](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/v1/CourseStructure.xsd#L79)). If it is determined that the `launchMethod` is required to be in the course structure file then the samples need to be updated to include it and the schema should be adjusted. If it is determined that it isn't required and there is a default value provided then the spec section should be updated in similar fashion to the `moveOn` section which also includes a default value.

**Comment by MrBillMcDonald** [comment]
Per April 29 meeting change as follows

> **13.1.4 AU Metadata**
> **LaunchMethod**
> Required: No
> Data type: string 
> Default Value:"AnyWindow"
