### ISSUE TITLE
<url> elements in complex example include newlines in value

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#446]
A strict interpretation of this means the whitespace should be encoded in the URL and probably leads to non-loadable content. Two options likely here:

1. Maintain the strict interpretation and update the example files, expecting LMSs not to correct for this,
2. Specify how (and when) trimming whitespace is allowed and/or expected

It may also make sense to re-visit why the launch URL is an XML element instead of an attribute in general, but that could be a side bar, and simply making it an attribute doesn't appear to solve the overall issue.

**Comment by MrBillMcDonald** [comment]
Remove leading/training whitespace for URL's in the example.

> **13.1 Course Structure Data Model**
> All leading/trailing whitespace MUST be removed by the LMS on import of the course structure for all of the data elements defined in this section

**Comment by MrBillMcDonald** [comment]
This issue resolved by pull request  #456
