### ISSUE TITLE
Launch URL should be recorded in Launched statement

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#447]
For similar reasoning as to #424 the launch URL should be captured in the Launched statement so that downstream users can verify what was actually launched. I've recently taken the example course structures, run them through a pre-processor which updated the launch URL to point to a simulator that can be easily used to generate a set of statements that would otherwise appear to come from the course structure itself, but without having ever hit the expected remotely hosted resources.

**Comment by MrBillMcDonald** [comment]
Per May 6th Meeting:

> "extensions" {
> https://w3id.org/xapi/cmi5/context/extensions/launchURL":"example Launch URL"

> 9.6.3 extensions
> 9.6.3.4 launchURL
> 
> ID:	https://w3id.org/xapi/cmi5/context/extensions/launchURL
> Description:	Indicates the URL that was used to launch the AU by the LMS
> LMS Usage:	LMS Must write the URL is used launch the AU in context Extensions of the Launched Statement.
> AU Usage:	Not Applicable
> AU Obligation:	None
> LMS Obligation:	Required
> Data type:	string
> Value space:	URL
> Sample value:  "xxx.com?name=value...."

**Comment by MrBillMcDonald** [comment]
Per the may 13th Meeting,
1. Merge Pull Request.
2. Add the following clarification to section 9.6.3.4 launchURL

> **9.6.3.4 launchURL**
> **LMS usage:**
> A fully qualified URL equivalent to the one that the LMS used to launch the AU without the name/value pairs included as defined in section 8.1.

**Comment by cawerkenthin** [comment]
@MrBillMcDonald, 
I believe this change should go in the description, not the LMS usage.

**Comment by brianjmiller** [comment]
#470 includes this change as was discussed on the call because I hadn't seen @cawerkenthin's comment, if he is correct I can fix that up.

**Comment by cawerkenthin** [comment]
@brianjmiller ,
Seems like this is informative language, as opposed to what is being replaced:
_Previously:_
The LMS MUST put the URL used to launch the AU in the context extensions of the "Launched" statement.
_Proposed:_
A fully qualified URL equivalent to the one that the LMS used to launch the AU without the name/value pairs included as defined in section 8.1. 

Thus, I believe it goes in the Description.

**Comment by MrBillMcDonald** [comment]
Per may 20th meeting pull request needs additional changes....

**Comment by MrBillMcDonald** [comment]
Resolved - per pull request #470 - Add missing context extensions, clarify launchURL language
