### ISSUE TITLE
Can Completed and/or Passed be stored in a Registration for an AU that has been Waived?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#448]
I don't believe we have any language indicating that once an AU has been Waived it can't be attempted by the learner in a Normal launch mode allowing for Passed and/or Completed to be issued. Shouldn't we?

The closest I've seen is the following which appears to be some informative language:

> A "Waived" statement is used by the LMS to indicate that the AU may be skipped by the learner.

The above also implies that the learner may not skip it.

**Comment by cawerkenthin** [comment]
I don't see any reason the student cannot opt to take the material.

**Comment by brianjmiller** [comment]
We run into the same problem of allowing a failed after a passed essentially, but in a slightly different way, presumably we avoid an issue by just not re-processing moveOn criteria but that's the reason I brought it up. 

So should a Failed after a Waived be ignored/voided? (Don't believe we've stated that.)

We could also have a collision of scores based on what is decided in #449, for Passed. We don't allow multiple Passed, should we allow Passed after Waived?

**Comment by cawerkenthin** [comment]
With a Waived status, the LMS can choose not to allow the student to start the AU if that is the business rule that applies.  We can of course do the same thing for passed (and we do, allowing only a review mode).  Ideally, I'd like to leave this in the hands of the LMS Administrator.  If the LMS supports it and the Administrator chooses not to allow launching after a Waived status is set, then the LMS can enforce that.

**Comment by bscSCORM** [comment]
This seems like an appropriate decision to leave up to the LMS. As @cawerkenthin says, the LMS can decide to refuse to launch a `Waived` AU or only launch it in `Review` mode.

I suggest we close this issue with no change to the spec.

**Comment by MrBillMcDonald** [comment]
Per the May 13th meeting, The group agreed to close this issue pending the resolution of issue #449
