### ISSUE TITLE
Can Waived contain a Score?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#449]
One of the values of reason for waiver is "Tested Out" and I'm wondering if it would be common for a score to be present in the case that someone tested out of something? I don't believe we specify that score can be included with Waived, but we do say the following which would prevent it:

> A "cmi5 defined" statement MUST NOT use result properties not specified for that particular verb except in the case of result extensions.

**Comment by MrBillMcDonald** [comment]
As per may 13th meeting.  

Section "9.5.1 Score" needs to be updated to indicate which cmi5 defined verbs are allowed to use score.

**Comment by MrBillMcDonald** [comment]
Per May 20th Meeting will merge pull request #467 and add the following:

> **9.5.4 Duration**
>
> The duration property is an ISO 8601 formatted time value required in certain statements as defined in this section.  Other cmi defined statements MAY include the duration property.
> 

To fully resolve this issuePer May 20th Meeting will merge pull request #467 and add the following:

> **9.5.4 Duration**
>
> The duration property is an ISO 8601 formatted time value required in certain statements as defined in this section.  Other cmi defined statements MAY include the duration property.
> 

To fully resolve this issue

**Comment by MrBillMcDonald** [comment]
Closed per pull request #480 Changes to 9.5.4 per May 20 meeting
