### ISSUE TITLE
Satisfied references AU but is for Block and Course

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#450]
Section 9.3.9 says:

> The LMS SHOULD NOT issue multiple statements with "Satisfied" for the same AU within a given AU session or course registration for a given learner.

Satisfied statements are issued for Blocks and Courses not for AUs, and are limited at the course registration level only.

Related to #434.

**Comment by cawerkenthin** [comment]
:+1:

**Comment by cawerkenthin** [comment]
Associated pull request #459

**Comment by MrBillMcDonald** [comment]
Closed per May 6th Meeting
