### ISSUE TITLE
Redundant requirements?

### ISSUE THREAD

**Issue by bscSCORM** [AICC/CMI-5_Spec_Current#451]
The following requirements appear to be redundant (as they just reference other requirements in this spec)

* 4.1
 * An Assignable Unit MUST conform to all requirements listed in Section 7 – AU Requirements.
* 4.2
 * The LMS MUST conform to all requirements listed in Section 6 – LMS Requirements.
* 4.3
 * All JSON properties included with non-null values MUST be recorded in the LRS.

Regarding the last one, it seems to be on the one hand redundant (The LRS must conform to xAPI which dictates that it must record values as defined in xAPI), and on the other hand contradictory -- xAPI defines certain cases (mostly around malformed data) where values MUST NOT be recorded, and this would contradict those requirements.

**Comment by MrBillMcDonald** [comment]
Per the May 27th Meeting,

The group pretty much agreed to the following language to (partially) address the issue.  Remove redundant normative language and reference the requirements sections.

> **4.1 Assignable Unit (AU)**
> See Section 7 – AU Requirements.
> An Assignable Unit MUST conform to all requirements as specified in the xAPI specification (see References).
> 
> **4.2 Learning Management Systems (LMS)**
> See Section 6 – LMS Requirements.
> The LMS MUST conform to all LRS requirements as specified in the xAPI specification (see References).

However one the following statements regarding LMS reporting requirements (for all statements recorded), the group agreed that something was needed, but with different wording.

> **4.2 Learning Management Systems (LMS)**
> The LMS MUST provide the ability to retrieve and show all statements (including attachments and extensions) to a user (with the understanding of scaling permissions/authorization).
> 
> The LMS MUST decode the attachment and make it available as a file with the original MIME type.

Andy Johnson agreed to provide alternative wording for this requirement and pull request both sections.

**Comment by MrBillMcDonald** [comment]
Closed per June 3rd Meeting
