### ISSUE TITLE
We need to define termination here

### ISSUE THREAD

**Issue by bscSCORM** [AICC/CMI-5_Spec_Current#452]
* 7.1.3 Last Statement Call
 * The AU MUST issue a statement to the LRS prior to termination using the Terminated verb as described in Section 9.3.8.

We all probably know what "termination" means, but we need to say it, as it stands the requirement appears circular (if one reads "termination" as "sending a terminated verb")

**Comment by MrBillMcDonald** [comment]
Per May 27th Meeting, change as follows:


> **7.1.2 Last Statement Call**
> 
> The AU MUST issue a Terminated statement to the LRS as described in Section 9.3.8 as the last statement in a session.
> 
> Once the AU has determined that the session will end (e.g. by user action or some other means) the AU SHOULD issue a Terminated statement.
> 
> Circumstances under which the AU may determine that the session is ending could include:
> 
> - Monitoring for browser window or application close events
> - An AU defined user action for closing the AU session
> - Other AU defined events such as a timeout from user inactivity

**Comment by hallshouse** [comment]
+1

**Comment by MrBillMcDonald** [comment]
Closed per Pull Request #482
