### ISSUE TITLE
IRI Metadata Needed

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#473]
This is to replace the remaining part of #408. Metadata is needed for the following IRIs:

* https://w3id.org/xapi/cmi5/context/categories/cmi5
* https://w3id.org/xapi/cmi5/context/categories/moveon
* https://w3id.org/xapi/cmi5/activitytype/course
* https://w3id.org/xapi/cmi5/activitytype/block
* https://w3id.org/xapi/cmi5/result/extensions/reason
* https://w3id.org/xapi/cmi5/result/extensions/progress
* https://w3id.org/xapi/cmi5/context/extensions/sessionid
* https://w3id.org/xapi/cmi5/context/extensions/launchurl
* https://w3id.org/xapi/cmi5/context/extensions/launchmode
* https://w3id.org/xapi/cmi5/context/extensions/launchparameters
* https://w3id.org/xapi/cmi5/context/extensions/moveon
* https://w3id.org/xapi/cmi5/context/extensions/masteryscore

I thought some of them were already hosted, but they seem to be 404ing.

Also, do we as the working group want to define the JSON that should be hosted at the above?

**Comment by brianjmiller** [comment]
The verbs section defines a "display" property for the verbs, but it seems like the specification shouldn't be including this as it is really defined by the metadata for the IRI which may include translations, etc.

**Comment by MrBillMcDonald** [comment]
Per May 27th meeting:

1) Remove “Name” from verb descriptions
2) Andy will followup with Jason to update the above IRI's and ensure that there is an JSON language map per xAPI spec.

**Comment by MrBillMcDonald** [comment]
Per June 3rd Meeting,

cmi5 specification is now released. 

 IRI's  still need resolution (Pending

**Comment by MrBillMcDonald** [comment]
CLosed Per July 22nd meeting
