### ISSUE TITLE
Update LRS Retrieval and Display Requirement

### ISSUE THREAD

**Issue by andyjohnson** [AICC/CMI-5_Spec_Current#484]
I propose the following change (sorry my cmi5 repo was borked and I have to leave until tomorrow).  If no action is done on this by then, I'll make a PR.

-The LMS MUST include the ability to retrieve and show all statements (including attachments and extensions) to a user (with the understanding of scaling permissions/authorization).

 +The LMS MUST have an account which is able to retrieve all Resource data (from the Statement API, etc, including attachments and extensions) about another distinct user across multiple sessions for that user.

**Comment by brianjmiller** [comment]
See #451.
