### ISSUE TITLE
Course Structure Requirements - AU and Objective Activity Types

### ISSUE THREAD

**Issue by andyjohnson** [AICC/CMI-5_Spec_Current#487]
Section 13 details out the requirements for the Course Structure Format, but never gets to the ActivityTypes allowed within the spec.  

Section 9.3.9 does have https://w3id.org/xapi/cmi5/activitytype/block and https://w3id.org/xapi/cmi5/activitytype/course show up due to requirements on the "satisfied" verb, but we don't have requirements for https://w3id.org/xapi/cmi5/activitytype/au and https://w3id.org/xapi/cmi5/activitytype/objective, so within the confines of the spec, they don't exist.

I say this as I am putting together a cmi5 vocabulary and realize they should exist :)

**Comment by brianjmiller** [comment]
The AU's activity type is fluid depending on the type of AU. For instance, it might need to be simulation, etc. and is set via the metadata for the AU in the course structure. Yes, objective should probably be coined.

**Comment by andyjohnson** [comment]
I think we should say something like that in the spec as far as expectations for activity types for AUs, including recommending use against something generic like AU if that is not what we want.  This isn't a strong recommendation;no MUST/MUST NOT language will be a part of this.

**Comment by andyjohnson** [comment]
Recommendation per the 6/10/16 call - Descriptive language for the AU to not use the activity type "AU" as the activity type can have much more meaning.  Use of "AU" as the activity type broadly means that all types of activities are reduced to a common denominator.

**Comment by andyjohnson** [comment]
Recommendation per the 6/10/16 call - use the ADL activity type objective.  Meeting a "cmi5 objective" isn't really a thing - you meet an objective globally (per the activity IRI it has).

**Comment by MrBillMcDonald** [comment]
Per June 17th meeting:
Add language specifying not to use AU as an activity type.  (location to be determined)
Agreed to remove objectives from the vocabulary. (w3id page)

**Comment by brianjmiller** [comment]
I don't understand the logic behind:

> An IRI was considered for objectives but was deemed unnecessary until future versions of cmi5 reference objectives in statements.

Is there a reason we can't go ahead and coin the term, especially since it makes a lot of sense given the other components of the course structure and the natural inclination to treat objectives like an Activity? Just cause it isn't in a statement that is "cmi5 defined" doesn't mean implementers can't go ahead and start work around leveraging the objective information in place. The same argument could be applied to the whole objective thing in the specification since why bother having objective metadata at all if there are no statements using it?

**Comment by MrBillMcDonald** [comment]
Per August 5 meeting:

If using objectives in statements (as activityTypes) best practice is to use the #objective in ADL vocabulary. (Since Objectives usage outside of course structure is not defined)

Add to a best Practices document

**Comment by MrBillMcDonald** [comment]
Best practices document created - objectives added
