### ISSUE TITLE
emoji in reference link

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#499]
I'm not sure if this is an inherent issue with Github markdown and if it can be avoided, but one of the links in the reference section includes the string `:-1:` which is getting rendered as a :-1: emoji. 

https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#references

**Comment by MrBillMcDonald** [comment]
It is an "inherent issue" with github.  The groups resolved that the solution is worse than the issue at this time.
