### ISSUE TITLE
IRL definition last sentence hard to understand

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#500]
> Some communities of practice simply use "URL" even if they use IRIs, which is not as technically correct within the xAPI.

I don't know what this means. How are they using "URL" and what's wrong about that use?

**Comment by MrBillMcDonald** [comment]
What specific documents/reference need correction ?

**Comment by garemoko** [comment]
It's in this section: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#definitions

**Comment by fugu13** [comment]
Maybe "Many people use URL in a broader sense, even if what's being referred to is an IRI and not a URI. The xAPI standard uses URLs in reference to the URL specifications, which require they be URIs." ?

**Comment by garemoko** [comment]
That's definitely an improvement, especially the first sentence.

**Comment by MrBillMcDonald** [comment]
Per July 29th Meeting - remove last sentence as follows:

> **Internationalized Resource Locator (IRL):** According to the xAPI specification, an IRL is an IRI that, when translated into a URI (according to the IRI to URI rules), is a URL.
