### ISSUE TITLE
LMSs with external LRSs not supported by cmi5?

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#502]
"the LMS MUST implement an LRS"

This seems to seriously limit the scope of cmi5. Is there any reason why cmi5 can't be used with LMSs such as Moodle that utilize external LRSs?

**Comment by garemoko** [comment]
Also "The LMS MUST conform to all LRS requirements..." This concept seems to be deeply embedded throughout the specification document. There's also bunch of places where requirements that you'd expect should relate to the LRS are assigned to the LMS as though they are a single system. e.g. 'LMS SHOULD reject statements that...'

**Comment by garemoko** [comment]
Having read through the complete spec I haven't found anything that would require the LMS to implement the LRS. 

Sure, there will likely be some light integration between the LMS and LRS for the purposes of generating credentials (though even then, there's nothing in cmi5 that restricts the LMS providing the same credentials every time) but that's a long way off needing the LRS to be part of the LMS. 

Ignoring that requirement, it doesn't look like too much work to implement cmi5 as an alternative launch mechanism in the Moodle xAPI launch plugin. With that requirement, it's a **huge** amount of work and not something I would even think about taking on.

**Comment by davidpesce** [comment]
+1

**Comment by ChuckGriess** [comment]
+1

**Comment by MrBillMcDonald** [comment]
As per July 22 meeting.  The group agreed to clarify the definitions as follows:
- **Learning Management System (LMS):** A computer system that may include the capabilities to register learners, launch learning presentations, analyze and report learner performance, and track learners' progress. LMS launching, reporting, and tracking roles are the focus of the cmi5 specification. The LMS MUST be integrated with an LRS.  In the remainder of this document the term “LMS” shall refer to an integrated entity of LMS and LRS.
- **Learning Records Store (LRS):** As defined in the xAPI specification.
