### ISSUE TITLE
Is cmi5 just for courses?

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#504]
I watched a video from ADL saying that cmi5 can be used for things like games and simulations. Reading the spec, it seems to be just for courses. E.g. the reference to "course designer". Which is accurate?

**Comment by brianjmiller** [comment]
Presumably "course designer" is the person creating the "Course Structure" which is a cmi5 defined entity. A course structure itself is just a manifest file pointing to Assignable Units (AU), the game/simulation/e-learning course would generally be the AU or wrapped by an entity acting as the AU.

**Comment by garemoko** [comment]
There is a definition of course in the spec, which is different to my personal reading. Under that definition, it could easily include "games and simulations".
