### ISSUE TITLE
Best Practices - Running List

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#511]
This issue is a running list of Best Practices documented so far

**Comment by MrBillMcDonald** [comment]
**_Best Practice #1 – Use of Objectives_**

 (Since Objectives usage outside of course structure is not defined)

Objectives are defined course structure but there is no language in the spec concerning their usage in statements.  If using objectives in statements (as activityTypes) the best practice is to use the id (http://adlnet.gov/expapi/activities/objective) in ADL vocabulary.

The same Objective can be referenced by multiple AU or Blocks.  There are 2 ways to interpret meeting an Objective.  The two expected practices are:
1. All elements referencing the objective need to be satisfied (or met moveOn criteria)
2. Only one element referencing the objective needs be satisfied (or met moveOn criteria).

It recommended that the LMS developers document how they do this and provide an extension (in the course structure) to indicate what method should be used.

**Best Practice #2 – Resolvable IRI's**

All IRI’s must be unique in the cmi5 spec. However, 
The Best practice to ensure a unique IRI should include a valid domain/host name and be resolvable.

Per XAPI specification:

> Internationalized Resource Locator (IRL): In the context of this document, an IRL is an IRI that when translated into a URI (per the IRI to URI rules), is a URL. Some communities of practice simply use URL even if they use IRIs, which isn't as technically correct within xAPI.

The resolution of an IRI should return a description of the IRI’s purpose/origin.

**Best Practice #3 – LMS resolution of relative course ID IRI’s.**

If the LMS imports a course with relative IRI’s it should prepend a valid protocol (http://, ftp://, or relative protocol // etc. ), domain, and path.

If other course elements have relative IRI’s, the LMS should prepend the course IRI to the relative course element IRI

> (Course IRI)(AU relative IRI)

**Comment by brianjmiller** [comment]
While working on adding this page this language doesn't make a lot of sense to me:

> All IRI’s must be unique in the cmi5 spec.

IRIs by definition are unique.

Additionally, saying they must be a "valid domain/host name" and "resolvable" isn't really clear. "localhost" is a "valid host name" and could even be resolvable, and presumably we mean resolvable via HTTP?  `ftp://localhost/someFileToDownload` could meet both criteria but probably isn't remotely what we want.

Are we better off just pointing to the xAPI community recommendations around IRI resolution and metadata creation? This seems out of scope for cmi5.

**Comment by brianjmiller** [comment]
> If the LMS imports a course with relative IRI’s

There is no such thing as a "relative IRI". I don't think this is necessary as defined by the spec, and I think the recommendations are a **big** stretch.

For more about IRIs specifically from the xAPI community see https://github.com/adlnet/xAPI-Spec/issues/470 and linked https://github.com/adlnet/xAPI-Spec/pull/527.

**Comment by cawerkenthin** [comment]
I believe the correct term is "IRI reference" as opposed to "relative IRI".

**Comment by MrBillMcDonald** [comment]
Closed per Oct 28.  Resolved that IRI best practices not needed (xAPI spec covers it)
