### ISSUE TITLE
Best Practice – Launching apps on mobile devices.

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#521]
**Best Practice – Launching apps on mobile devices.**

The either of the following options should be used to launch AU's that are apps on mobile devices:

_Option 1_: Use an app protocol in the launch URL
- AU is an app
- AU has url with a protocol LMS launches App using URL with app protocol
- An App redirecting to browser is not useful. If an using app protocol to launch, don’t use returnURL.

_Option 2_: Use and HTML wrapper to launch the app AU is an HTML page (wrapper) that directs from the mobile browser to the app.

**Comment by brianjmiller** [comment]
I don't really follow: "AU has url with a protocol LMS launches App using URL with app protocol" the LMS doesn't really have a choice here, isn't this just "implement the spec"?

I'm also not sure I follow "An App redirecting to browser is not useful. If an using app protocol to launch, don’t use returnURL." If the AU has been launched into an app we can _probably_ assume that it came from the default browser, wouldn't the app then send the user back to the default browser (albeit possibly with a new tab/window)? I don't know that we can unilaterally say a "returnUrl" shouldn't be provided in that case. Perhaps we need to expand this to say indicate when the launching system itself is an app a return URL shouldn't be provided? Do mobile apps allow for communicating back? Do we need to add something to the spec to allow for this communication? Would we expect an "LMS" to then expect to implement it?

I'll have a PR up soon with basically the above wording, but I think it needs further discussion.
