### ISSUE TITLE
AU Best Practice for Mastery Score

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#522]
**AU Best Practice for Mastery score**

If the LMS issues a Mastery Score AND the AU does not have the notion of a SCORE then the AU should not issue Passed or Failed statements.

**Comment by brianjmiller** [comment]
See https://github.com/AICC/CMI-5_Spec_Current/wiki/CMI-5-Working-Group-Meeting-Minutes-%E2%80%93-November-4th%2C-2016 for updated wording?
