### ISSUE TITLE
LMS Best Practice for Mastery score

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#523]
**LMS Best Practice for Mastery score**

LMS should not add mastery scores to AU course structure entries if they are not present. (as the AU may not be designed to issue scores).

**Comment by brianjmiller** [comment]
See https://github.com/AICC/CMI-5_Spec_Current/wiki/CMI-5-Working-Group-Meeting-Minutes-%E2%80%93-November-4th%2C-2016 for updated wording?
