### ISSUE TITLE
Best Practices - moveOn criteria NotApplicable should not be used in a course structure

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#526]
Best Practices - moveOn criteria NotApplicable should not be used in a course structure unless the AU is strictly optional. (a known problem with the default moveOn value.)

**Comment by brianjmiller** [comment]
See https://github.com/AICC/CMI-5_Spec_Current/wiki/CMI-5-Working-Group-Meeting-Minutes-%E2%80%93-November-4th%2C-2016 for updated wording?
