### ISSUE TITLE
Clarifying the distinction between LRS and LMS

### ISSUE THREAD

**Issue by sdwarwick** [AICC/CMI-5_Spec_Current#534]
Hi - just wondering if the following be referring to LMS not LRS?

---

<a name="first_statement_au"></a> 
### 7.1.1 First Statement API Call
The AU MUST issue a statement to the LRS after being launched, initialized, and ready for learner interaction using the Initialized verb as described in Section 9.3.2.

<a name="last_statement_au"></a>  
### 7.1.2 Last Statement Call
The AU MUST issue a Terminated statement to the LRS as described in Section 9.3.8 as the last statement in a session.
 

---
---

<a name="first_statement_au"></a> 
### 7.1.1 First Statement API Call
The AU MUST issue a statement to the LMS after being launched, initialized, and ready for learner interaction using the Initialized verb as described in Section 9.3.2.

<a name="last_statement_au"></a>  
### 7.1.2 Last Statement Call
The AU MUST issue a Terminated statement to the LMS as described in Section 9.3.8 as the last statement in a session.

**Comment by brianjmiller** [comment]
No, the statements are issued to the LRS. The LMS is expected to do certain handling of them as part of the integration of the two, but the communications are via xAPI which is what defines the LRS.

**Comment by sdwarwick** [comment]
Thanks for you comment, Brian,  In reading through the document, it  seems to really push the concept that the LRS functionality sits "inside" the LMS in the cmi5 architecture.  This seems to be technically reinforced by the fact that there is only one termination point (URL) for xAPI/cmi5 messages - the LMS.     I've reproduced the critical concept sections below.   There are really lots of great reasons to maintain this "point to point" ( AU to LMS ) concept in the spec.   I'd be grateful to understand more why there needs to be a distinction between LMS/LRS in this case.


from the spec:

---

<a name="scope"></a>  
## 1.1 Scope

The scope of this specification is limited to the following:

* Launch by an LMS of AUs.
* Launch and runtime environment used by LMS and AUs.
* Runtime communication data and data transport between the LMS and AUs. 
* LMS course definition as it pertains to runtime data used by AUs.
* LMS Course Structure Import/Export  
* Reporting requirements for the LMS.

This specification references how to use the xAPI specification within this scope.

Other uses of the xAPI specification are outside of this scope.

Uses of activities not explicitly defined above are outside of the scope of this specification.

---

<a name="concept"></a> 
# 5.0 Conceptual Model: Informative  

Synopsis of the cmi5 model:
* An LMS imports a course structure, which may contain one or more AUs.
* An LMS administrative user assigns a course to a learner.
* A learner authenticates with an LMS or a related system.
* A learner launches an AU from the LMS or an associated launching system, using an interface.
* The LMS writes launch data to the integrated LRS.
* The AU sends a message to the LMS requesting launch parameters and previous state information.
* The learner views the AU content and performs the learning. During this time, the AU MAY request data from, and store data to, the LMS.
* The learner exits the AU.
* The AU reports the final tracking data to the LMS and issues a "terminate" statement.
* Administrative users create and view reports of the tracking data recorded by the AUs for individual learners.

Responsibilities of the Assignable Unit:
* Parse the parameters from the launching environment to determine where the LMS location is and initiate communication with the LMS.
* Acting as a "client", send and receive messages using the defined transport mechanism(s) and associated commands as prescribed in this specification.
* Format all data according to the defined data types and vocabularies that are defined in this specification.
* Send a "terminate" statement prior to terminating the AU's execution.

Responsibilities of the LMS:
* Create and maintain course structures.
* Acting as a "server", receive and reply to messages using the defined transport mechanism(s) and associated commands as prescribed in this specification.
* Format all data according to the defined data types and vocabularies that are defined in this specification.
* Launch the specified AU contained in the courses within the defined environment(s).

<a name="lms_requirements"></a>  
# 6.0 LMS Requirements

LMS requirements to conform to this specification are as follows:

* Implement an LRS as defined in the xAPI specification.
* Implement additional "State API" requirements to initialize the AU state as defined in Section 10.
* Implement the runtime launch interface as defined in Section 8.0 – Content Launch Mechanisms.
* Implement additional xAPI "Statement API" requirements as defined in Section 9.
* Implement additional xAPI "Agent Profile API" requirements as defined in Section 11.
* Implement course structures as defined in Section 6.1.

---

**Comment by brianjmiller** [comment]
I read it differently, based on your statement:

> This seems to be technically reinforced by the fact that there is only one termination point (URL) for xAPI/cmi5 messages - the LMS.

The only termination point for xAPI messages is the *LRS* and specifically because the LRS is defined by xAPI itself, and arbitrary endpoints provided by an LMS are not part of xAPI and can't be communicated with as such from the AU.

Additionally there is at least one resource that *must* be provided by the LMS and is outside of the xAPI scope, and that is the `fetchURL`. This is really important for people to understand that merely having an LRS does not provide 100% functionality for cmi5, and only having a library that can interface with an LRS is not sufficient to fully implement cmi5. Having said that, the LMS while *integrated* with the LRS, the LRS can be a separate, standalone system at an entirely different endpoint, domain, etc. which is part of the goal of using xAPI as the communications protocol.

The reason to maintain the use of language of LRS is to be specific that the type of requests and corresponding data model required is xAPI. If we were to use the term LMS then we would need to be very specific about calling out the xAPI protocol for every communication to it that we intend to go over that path. Otherwise we end up with ambiguity about what we mean by "statement" and/or the way in which it is captured and the format of the request to do that.

**Comment by sdwarwick** [comment]
I'm sorry,  it is still not clear.   The language in 5.0 and 6.0 seems to be very specific that cmi5 considers the xAPI termination point to be the LMS URL.   Further,  it doesn't seem that section 9 can be implemented unless the LMS acts as a gatekeeper for messages coming from the AU restricting access to the actual LRS.  ( section 9.3.6 as example )     It seems that cmi5 by design subsumes the xAPI termination.  

The concern you are expressing in the last paragraph regarding the xAPI data model requiring the LRS really is already addressed in the conceptual model paragraphs in the beginning.  

Please understand that this is driven by a strong desire to have cmi5 be successful and see wide uptake by keeping the conceptual model as clean as possible.

**Comment by cawerkenthin** [comment]
@sdwarwick,
The term "LMS" in the document is intended to represent some integration of an LMS and an LRS.  This is defined in Section 3.0 - Definitions.  How this is accomplished is intentionally not defined; the committee determined that it should not exclude vendors based on a particular type of integration.  It could be an LRS running inside an LMS (tight integration), or it could be a loose integration where the LMS and LRS are separate entities but have developed some mechanism for exchanging key statement information, or it could be the the LMS continually polls the LRS to see what cmi5 defined statements have been recorded (in which case the LMS may need to perform some action).  How this integration is handled is up to the LMS and LRS vendor, and is beyond the scope of the spec.

So when you see "LMS" in 5 and 6, the term refers to this integrated entity, not strictly to the LMS.  @brianjmiller is correct that the only endpoint for statements and State is the LRS.  The only "endpoint" provided by the LMS is the fetchUrl.

As an example, we are an LMS with built-in LRS.  However, we implemented the majority of the logic into a separate service that runs outside both the LRS and LMS.  The LRS simply calls it every time it receives a valid cmi5-defined statement.  Right now, because it was simple, we use the LMS database to store the parameters for this external call, but there is no reason the LRS could not pass a JSON object to our cmi5 statement processing service.

**Comment by sdwarwick** [comment]
This is very helpful, Art - Thanks!


 The problem is that there is essentially a single URL defined for communication of both statement and state information to/from the AU  all of that communication is presumed to be in xAPI messaging.   The fetchURL really only addresses initial authorization.  

Since  cmi5 calls out a range of cases where the AU messages have to be policed before being just added to the LRS datastore,  I don't see how this works without a "proxy" termination point as a required aspect of the cmi5 implementation.    Also, just as you said,  if the LMS doesn't act as a proxy and messages go straight to the LRS,  you end up doing some kind of LRS polling. This would create serious performance issues you would have to deal with to be real-time responsive to the user of the course.  

I see the following issues with the LRS being the primary termination point:
1 - policing the data coming from the AU as is required in section 9, (something not covered by LRS functional requirements)
2 - the need for polling or LRS event generation to create LMS control actions, (which are a major performance hit or require special functions in the LRS also outside of the LRS requirements.  )
3.  - injection of the lesson control messages from the LRS process

I am having a hard time understanding why cmi5 would support this architecture as it seems out of sync with the document's stated goals. It requires very specialized modifications to the LRS with potential major performance issues,  and creates confusion relative to the widely deployed SCORM model which cmi5 seems to be designed to replace.  

  I'm really worried that there will be very slow uptake in both the authoring tool and course development communities without a tight AU/LMS interaction model, and am just hoping to offer a perspective that might help to accelerate deployment of this much needed standard.

**Comment by brianjmiller** [comment]
1. Is covered in 2 ways in section 6.3. In the tight integration implementation the LRS is setup to reject statements that are non-conforming, and it can do so based on what could be considered a loop hole in the xAPI spec around requests for a given credential. Essentially an LRS can refuse a request based on a particular user not being authorized to make such a request. This as you point out means the LRS has capabilities specifically beyond those outlined in xAPI which is a normal and expected use case. Alternatively without tight integration that section allows the LMS to void any non-conforming statements after the fact, which is still within the xAPI spec.

2. Yep, again a common use case to have an LRS pushing messages to another system. Well within the expected architecture of an LRS. Polling while not performant is still acceptable and may be the best options in some scenarios (think remote cmi5 launching system). The specification shouldn't be trying to target performance, therein lies madness. It would be quite easy to implement a poorly performing tightly integrated LRS+LMS, or a well performing loosely integrated one.

3. I don't know what the lesson control messages are?

It does not *require* modifications to the LRS, though for optimal performance the LRS would likely need to understand the subset of cmi5 requests. I just don't see the potential major performance issues, this kind of service based architecture is *very* common. Have to remember even with disparate systems on different platforms you can have very good performance over local networks or even within the same hardware system, certainly such that the bottleneck would not be there. Saying that cmi5 is designed to replace SCORM is a bit of a stretch, and even if these were issues I don't think they'd scratch the surface of the capabilities provided by an extensible data model and use of a specified communications protocol and data format.

I can't speak to the speed of uptake, though I don't think whether the specification is using "LMS" or "LRS" in those few places is going to determine whether or not people adopt cmi5. The availability of platforms, tools, and reporting systems is far more likely to determine growth than the verbiage in a *very* technical document.

As Ben likes to say, running code trumps all theory, and there are at least two production level working platforms that have shown cmi5 can work end to end.

**Comment by cawerkenthin** [comment]
I would expect the LRS to be "cmi5 aware" in some way.  Either it has statement forwarding of cmi5 defined statements, or it has a tighter integration with an LMS.  While there is nothing to prevent polling by the LMS, it is likely not the most efficient.  

I had a discussion with some members of the DISC group (http://datainteroperability.org/) this past week and a long term goal of their work is to develop a mechanism to test conformance not only for xAPI, but also various xAPI profiles, of which cmi5 is the most defined.  This indicates to me that they expect LRS to either conform or not conform to various profiles.  To conform to the cmi5 profile, they will likely need to support cmi5 validation.  However, as pointed out by @brianjmiller,  the spec does allow voiding of invalid statements.  So it is possible for a polling method to work, with the LMS handling validation and voiding non-conformant statements.  We designed cmi5 to include queriable elements to find cmi5-defined statements with a minimal amount of data transfer.  So while it may not be as efficient as a push, it should be possible to make the performance acceptable.

**Comment by sdwarwick** [comment]
Having been involved with international standards bodies MPEG, DOCSIS Wimax, and 802.16 in the past,  I'm afraid the comment "The specification shouldn't be trying to target performance, therein lies madness." is probably not something we would want to be a characteristic of a modern interface standard.   

This is probably the first time I have seen a database vendor aggressively supporting a spec that requires modifying their products to run an application-level protocol.   This specification also requires the LMS to support the "authentication" header validation on each transaction.  Are the LRS/cmi5 implementing that as well?

I've learned a lot through this discussion and am grateful for the feedback.  

I still believe that there is opportunity in the spec to provide more clarity regarding the role of the LMS as a smart proxy for the LRS due to the needs of authentication and policing,  and that an LRS that chooses to provide those services is actually performing functions far beyond the LRS/xAPI specification.  AU's don't "naturally" terminate xAPI on the LRS. This really could be made more clear.

I could imagine DISC being interested in developing conformance with cmi5,  It would be interesting to know if they would be providing strategies to certify LMS ( and "LRS/cmi5" ) termination points  and cmi5 libraries for AUs independently.

**Comment by cawerkenthin** [comment]
> I still believe that there is opportunity in the spec to provide more clarity regarding the role of the LMS as a smart proxy for the LRS 

I still feel like you are confusing our spec defined term of "LMS = LRS + LMS integration" with the generic term LMS.  The LMS is not a proxy.  Statements go directly to the LRS, which makes some communication to the LMS.  The LRS  is really more of a proxy to the LMS, not the other way around.  

The endpoint to use is passed to the AU upon launch; I'm not sure why it should care what the endpoint represents as long as it knows that endpoint is xAPI conformant.  The authentication header, as an example, is validated by the LRS, essentially by asking the LMS if it is valid.

> This is probably the first time I have seen a database vendor aggressively supporting a spec that requires modifying their products to run an application-level protocol.

SCORM required the LMS to accept javascript calls, usually to web services, and update data.  cmi5 uses REST to communicate with the LRS.  The LRS can communicate with the LMS using whatever protocol they agree on; web service, REST or some other method.  Doesn't seem all that different to me.

> I still believe that there is opportunity in the spec to provide more clarity regarding the role of the LMS

There is always room for improvement.  It doesn't seem unclear to me but I've been working on this spec for 4 years, so I'm obviously not a good judge.  We are currently working on best practices and introduction to the spec documents, so this is a good time to look at the issue.

**Comment by sdwarwick** [comment]
Perhaps one reason we've had issue with how this spec is written is that,  throughout the data analytics industry, a database is considered a **stateless** system.   Things get written,  things are read.   Even the xAPI / LRS standard and conformance documents seem to capture this stateless concept.  Conformance is concerned with the form of the data that is being read/written, but I see no case in the LRS spec where reading/writing is somehow dependent on the state of the agent requesting service.

cmi5 doesn't fit the stateless LRS model, allowing certain statements only to be written at certain times, with stateful validation and filtering.   This is a separate logical function and I believe should be identified as such as a different entity than the stateless LRS.    If LRS vendors wish to include a cmi5 state processing engine,  they should call that out as a separate function with a separate "termination point" just as the LMS vendors will need to.   This doesn't prevent LRS vendors from marketing cmi5 solutions, but makes a clear distinction that this is a separate functionality that leverages the stateless LRS.     

It is for this reason I believe that the term LRS in the document really should be qualified or restated to refer to this stateful termination point.

**Comment by MrBillMcDonald** [comment]
We will Develop a best practice for error handling of invalid statements. 
(LRS/LRS)
