### ISSUE TITLE
Launch method with file protocol

### ISSUE THREAD

**Issue by s512** [AICC/CMI-5_Spec_Current#538]
This may or may not be classed as an "issue".  Is this spec designed to work with offline courses?  

We are building a course launcher in a mobile app, which needs to support offline learning and therefore uses the file protocol (file://) to launch a local version of the HTML xAPI based AU.

The launch method in this spec specifies the following:

```
<URL to AU>
?endpoint=<URL to LMS Listener>
&fetch=<Fetch URL for the Authorization Token>
&actor=<Actor>
&registration=<Registration ID>
&activityId=<AU activity ID>
```

However, this won't work when the file protocol is used, as GET parameters are only supported with HTTP. 

Allowing support for parameters in hash tags (#) could solve this issue, if this is something you wish to support.

Thanks in advance,
Sam

**Comment by MrBillMcDonald** [comment]
To my understanding, theses parameters can be retrieved from the JavaScript "window.location" variable.

Could you explain why can't do this?  What browser or app can not support grabbing the query string ?

**Comment by s512** [comment]
Apologies, we are using ionic and this was an error in testing or an error with the ionic framework. Closing issue.
