### ISSUE TITLE
Section 13 heading formatting

### ISSUE THREAD

**Issue by s512** [AICC/CMI-5_Spec_Current#539]
Hi all,

Just noticed section 13 isn't correctly formatted:

![screen shot 2017-03-24 at 16 18 04](https://cloud.githubusercontent.com/assets/10452969/24303347/9001e67c-10ad-11e7-81e9-c76acbf6a3cc.png)

**Comment by MrBillMcDonald** [comment]
Fixed per March 31 meeting
