### ISSUE TITLE
What is a "course registration"?

### ISSUE THREAD

**Issue by fugu13** [AICC/CMI-5_Spec_Current#546]
It doesn't seem to be defined, but doesn't seem to be used the same as "registration id" and is used several places that have normative impact where slightly different interpretations could require different behaviors.

**Comment by brianjmiller** [comment]
It'd be good to catalog those places. A cursory glance makes it seem like "registration id" is used specifically to mean a UUID value, where "registration" is used as a concept. A definition is probably in order.

**Comment by fugu13** [comment]
"registration" is also used quite a few places to mean the registration that goes in context, just like "registration id". I don't *think* any of the places "registration" is used without a clear qualification about a course or a class it means anything else... but it's often hard to tell.

This one has a lot of normative implications if it is ever wrong, because so many things are restricted within a "registration" but not within a "course registration".

**Comment by fugu13** [comment]
This includes a bunch of requirements stated (nearly?) equivalently with different (nearly?) equivalent restrictions. For example, there's:

> The AU MUST NOT issue multiple statements with "Completed" for the same AU within a given AU session or course registration for a given learner.

But there's also

> Only one "Completed" cmi5 defined statement is allowed per registration.

The first one uses "for the same AU within a given AU session or course registration", while the second uses "registration" in a way that means the registration in context, and that's always per AU, both because lots of the rules don't make sense otherwise and because this at least loosely implies it:

> A Registration ID corresponding to the learner's enrollment for the AU being launched.
