### ISSUE TITLE
Conflict of Satisfied Rules with Session Rules

### ISSUE THREAD

**Issue by fugu13** [AICC/CMI-5_Spec_Current#548]
The session rules include:

> Verbs MUST NOT be duplicated (in cmi5 defined statements).

But two satisfied statements must be issued if, in a session, the AU's moveOn criteria is met and it is the last AU for both a block and a course, and the satisfied statements are both required to be given the session id.

**Comment by brianjmiller** [comment]
Could certainly be more clear, but that line is under "AU Verb Ordering Rules within an AU session are as follows" but the Satisfied statement isn't an "AU Verb", it's an LMS verb.

**Comment by fugu13** [comment]
Okay, I can see that. I definitely agree with "Could certainly be more clear".

**Comment by fugu13** [comment]
If language tidying is considered currently I'd recommend that as one place to touch. If not, might as well close the issue or tag for the future.
