### ISSUE TITLE
Should no-fail-after-pass be per registration?

### ISSUE THREAD

**Issue by fugu13** [AICC/CMI-5_Spec_Current#550]
In https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#93-verbs, the introduction says it is talking about per-session rules. Some of the rules specify they are actually per-registration, but some do not, and the ones that do not (such as one of each verb) generally only make sense in a per-session context.

However, one of the rules is
> A "Failed" statement must not follow a "Passed" statement (in cmi5 defined statements).

Only one of passed or failed is allowed per session anyways, according to
> More than one of the set of {"Passed","Failed"} verbs MUST NOT be used (in cmi5 defined statements).

Because of that, I'm guessing that the no-fail-after-pass requirement is supposed to be per registration, though it is in the per-session rules and not qualified as being per registration?

**Comment by brianjmiller** [comment]
Yes that was the intention. I suspect it should include the "per registration" tag as you point out.

**Comment by MrBillMcDonald** [comment]
In today's meeting we discussed this issue and agree with Brian's assessment.  We will add clarifying language to indicate "per registration" for this case.

**Comment by fugu13** [comment]
Thanks :)
