### ISSUE TITLE
returnURL vs. returnUrl

### ISSUE THREAD

**Issue by cawerkenthin** [AICC/CMI-5_Spec_Current#553]
@brianjmiller, 
Section 10, State, defines a property of returnURL.  Samples, such as http://aicc.github.io/CMI-5_Spec_Current/samples/scenarios/01-typical-non_credit_session/, show returnUrl as the property.  I recommend that existing samples which show the State document should be fixed to reflect the spec property.

**Comment by MrBillMcDonald** [comment]
Corrected per June 16th meeting.
