### ISSUE TITLE
Section 8.1 AU usage for activityId inconsistent with 9.4

### ISSUE THREAD

**Issue by cawerkenthin** [AICC/CMI-5_Spec_Current#556]
The AU Usage section for activityId in 8.1 is not consistent with 9.4 Object.  In 9.4, the activityId is only required to be the value passed from the LMS when the Object is the AU itself.  In 8.1, the spec indicates that the activityId must be used in all statements.  Suggest revising AU Usage section in 8.1 to:

_The AU MUST get the activityId value from the query string. The AU MUST use the activityId value as the id property of the Object in all "cmi5 defined" statements._

**Comment by MrBillMcDonald** [comment]
Per Friday June 30 meeting.  

The language will  be clarified as follows:

> **8.1 Launch Method**
> **activityId**
> 
> AU Usage: The AU MUST get the activityId value from the query string. The AU MUST use the activityId value as the id property of the Object in all "cmi5 defined" statements.
