### ISSUE TITLE
Does it make sense to create a CMI 5 AU when not using a LMS?

### ISSUE THREAD

**Issue by rscharfer** [AICC/CMI-5_Spec_Current#566]
I have an application that requires users to log in to authenticate themselves, and with this information xAPI statements are sent to a LRS as the user works through the module.  The statements that my JS creates are not CMI5-conform statements.  Are there advantages to making every statement sent off by my AU CMI5-conform when I am not using a LMS to play the LMS "role".  It seems what the LMS is responsible for is a huge part in making CMI 5 work.

**Comment by MrBillMcDonald** [comment]
Correct.  You really need to have something performing the LMS role (A launching program of some kind) to fully utilize cmi5.

cmi5 statement structure "might" be useful for content development for consistency with other content.
