### ISSUE TITLE
CMI-5 spec questions

### ISSUE THREAD

**Issue by Getafix-hub** [AICC/CMI-5_Spec_Current#572]
hi, 

In https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#100-xapi-state-data-model
The document describes the State API PUT. 
Should a GET /activities/state return a JSON structure with activityId, agent, registration and stateId properties? 

In https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#xapi_agent_profile
**When reading or writing to the Agent Profile, the document name MUST be "cmi5LearnerPreferences"** and the format MUST be a JSON structure as shown below:
{
  "languagePreference": "<values for languages>",
  "audioPreference": "<on or off>"
}

What does "document name" mean and how does it relate to **reading** the agent profile via GET /agents/profile?

Thanks

**Comment by brianjmiller** [comment]
1) A GET /activities/state MUST return the document that is described by the properties of the `LMS.LaunchData`, IOW "contextTemplate", "launchMode", etc. The 4 values you mentioned form the key to the request and go in the request parameters, see State requests in xAPI.  `LMS.LaunchData` is the `stateId`. You can see a sample of the LMS launch data document in the JSON samples on the website, ref: http://aicc.github.io/CMI-5_Spec_Current/samples/scenarios/03-completed_or_passed-passed/#lms-launch-data

2) `cmi5LearnerPreferences` is the value of the `profileId` parameter. It is passed via the query string when storing/requesting the document.

**Comment by Getafix-hub** [comment]
Thank you.  In http://aicc.github.io/CMI-5_Spec_Current/samples/scenarios/03-completed_or_passed-passed/04-passed_statement.json, i believe the verb should be "passed" instead of "initialized".

**Comment by brianjmiller** [comment]
Correct, that is not a passed statement as it is missing the `result` as well.

**Comment by Getafix-hub** [comment]
With respect to  LMS launch data: what is the recommended way to store/retrieve the document in MongoDB given that "extensions" contains dotted fields that are not valid for storage:
    "extensions": {
      "https://w3id.org/xapi/cmi5/context/extensions/sessionid": "c7b6f0a9-482c-4c03-acc1-548289126963"
    }

**Comment by brianjmiller** [comment]
An implementation detail like that is really outside of the scope of the spec, though someone here might be able to answer. You may get better/quicker responses in a MongoDB forum.

**Comment by Getafix-hub** [comment]
Thank you. Is it fair to say that the LRS solely performs storage and retrieval of these documents based on the associated keys (without accessing document elements or attributes) so the documents encoding/decoding format is irrelevant?

**Comment by brianjmiller** [comment]
In *this* case, yes. To be xAPI spec conformant the more general State API that the LRS exposes (used by LMS.LaunchData) has to provide for `application/json` POST requests that do document merging, but it is still based on a lookup using the associated keys from the query parameters rather than the document contents.

**Comment by Getafix-hub** [comment]
Thanks

**Comment by ssimo3lsuhsc** [comment]
> 1. A GET /activities/state MUST return the document that is described by the properties of the `LMS.LaunchData`, IOW "contextTemplate", "launchMode", etc. The 4 values you mentioned form the key to the request and go in the request parameters, see State requests in xAPI.  `LMS.LaunchData` is the `stateId`. You can see a sample of the LMS launch data document in the JSON samples on the website, ref: http://aicc.github.io/CMI-5_Spec_Current/samples/scenarios/03-completed_or_passed-passed/#lms-launch-data
> 2. `cmi5LearnerPreferences` is the value of the `profileId` parameter. It is passed via the query string when storing/requesting the document.

I'm confused with what the value of `stateId`. Is it the string literal `"LMS.LaunchData"`? If so, the documentation should make that clear by enclosing the value in double quotes. Thank you!
