### ISSUE TITLE
Considering ADA 508/Personal Needs Profile (PNP)/“Access For All Specification” 

### ISSUE THREAD

**Issue by nphoenix** [AICC/CMI-5_Spec_Current#58]
This issue thread was started to consider what may be required in CMI5 for a Personal Needs Profile (PNP)

I found the IMS has an “Access For All Specification” with detail on
a)       Display: how resources are to be presented and structured;
b)       Control: how resources are to be controlled and operated; and,
c)       Content: what supplementary or alternative resources are to be supplied.

Which is based on:

ISO/IEC 24751-1 Information technology -- Individualized adaptability and
accessibility in e-learning, education and training -- Part 1: Framework and
reference model

ISO/IEC 24751-2 Information technology -- Individualized adaptability and
accessibility in e-learning, education and training -- Part 2: "Access for all" personal needs and preferences for digital delivery

This is the link to the IMS document:
http://www.imsglobal.org/accessibility/accpnpv2p0/spec/ISO_ACCPNPinfoModelv2p0.html 
It was interesting that they had Needs and Preferences  tagged as “required”, “preferred” , “Optionally use” and “prohibited”.  The example for “prohibited” were animations which flash and can cause seizure.

The IMS Class “Access_For_All_User” puts the Language attribute under this parent container. It also has a ‘Speech Rate’ which I recall Boeing used in the courseware. The link above can be scrolled through to see parameters accounted for.

**Comment by MrBillMcDonald** [comment]
Support for ADA 508 standards are vendor supported.
