### ISSUE TITLE
Is SCORM extensible?

### ISSUE THREAD

**Issue by cawerkenthin** [AICC/CMI-5_Spec_Current#588]
The SCORM/cmi5 comparison document includes this sentence:

"Like SCORM, cmi5 is also extensible."

Is that correct?  Or should it be "Unlike SCORM, cmi5 is extensible."?

**Comment by MrBillMcDonald** [comment]
The SCORM Run-Time Environment Data Model itself shall not be extended.

**Comment by MrBillMcDonald** [comment]
The SCORM Data Model is not extensible (per the spec), but cmi5 is extensible and has defined capability for extensions.
