### ISSUE TITLE
Definition of "Block" missing from cmi5_spec.md

### ISSUE THREAD

**Issue by dennisvang** [AICC/CMI-5_Spec_Current#590]
Looking through [section 3.0](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#30-definitions) of the cmi5 spec, I do not see a definition for `Block`. 

I suppose it would be helpful if `Block` were also defined, especially in relation to the `AU` and `Course`.

There is a partial definition in [section 13.1.2](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#1312-block-metadata), but that does not mention its relation with a `Course`.

I would submit a pull request if I knew what the proper definition was, but I'm no expert on the subject.

**Comment by MrBillMcDonald** [comment]
Dennis,

A course is made of up of Blocks and AU's.  Blocks are groupings of AU's that can be nested.  (e.g. blocks are like file folders and with AU's being the "files").  The XSD (CourseStructure.xsd) referenced in the spec does define this relationship as the course structure is represented as an XML file.

Based on your feedback we will expand the Conceptual description of a course and blocks to better explain this.

> 
> **3.0 Definitions**
> 
> Block - A grouping which contains AU's and other Blocks (nesting).
> 
> **5.0 Conceptual Model: Informative**
> 
> Synopsis of the cmi5 model:
> An LMS imports a course structure, which may contain one or more AUs.  Optionally, the course structure may include one or more blocks, which consist of 1 or more AUs or nested blocks.

Thank you for your feedback !

cmi5 Working group
