### ISSUE TITLE
AU requests from state info, how?

### ISSUE THREAD

**Issue by ap-prog** [AICC/CMI-5_Spec_Current#592]
Conceptually, when the spec says

"The AU sends a message to the LMS requesting launch parameters and previous state information."

How is the AU meant to send a message? Sorry, if this is so much of a noob question. My understanding is that all communication after getting the auth-token is by sending statements and none of the verbs from 'abandoned' to 'waived" appear to allow a request.

**Comment by brianjmiller** [comment]
The "Conceptual Model" section is a bit loose in its language and I can see how that would be confusing. The operative word here is "state". Effectively you need to be familiar with the document handling portions of the xAPI specification to make the leap to what that means, essentially it has a set of document resources one of which is "state". cmi5 leaves itself open to making any xAPI request that the LRS can handle, it isn't just statements, the "profile" (or document) requests are also used.

During launch the LMS stores a JSON document in the LRS state profile resource, the AU after receiving its LRS credentials must retrieve that JSON document to be able to properly form the statements that it will save later. See https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#100-xapi-state-data-model for specifics about the document. And section 11.0 and 12.0 about additional possible profile requests. See the website JSON examples (http://aicc.github.io/CMI-5_Spec_Current/samples/scenarios/03-completed_or_passed-passed/#lmslaunchdata) for examples of the `LMS.LaunchData` document.

**Comment by MrBillMcDonald** [comment]
In general the LMS creates a state document (using the State API) that the AU has to read.  It creates this document just prior to launching the AU.  To be clear, this is NOT a Statement. 

Please look at LMS.LaunchData (State Document) in the examples on our website.    Here is a direct link to the example:

- http://aicc.github.io/CMI-5_Spec_Current/samples/scenarios/04-completed_or_passed-completed/#lmslaunchdata

 Also please see Section 10 of the cmi5 spec:

- https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#xapi_state

If you would like to see an example in JavaScript, please see our cmi5 client library currently under development:

- https://github.com/adlnet/cmi5-Client-Library

**Comment by ap-prog** [comment]
Thanks for your help. A GET is sent to the endpoint with "activities/state" appended and the parameters set out in the xAPI spec and

https://github.com/LearningLocker/learninglocker/issues/1342

**Comment by ssimo3lsuhsc** [comment]
Can somebody please explain to me what property of the State, if any, determines whether or not a request will be made to the FetchUrl? If somebody is viewing a course for the first time, then the FetchURL should succeed. If the player decides to return later, the FetchURL will fail.

**Comment by brianjmiller** [comment]
The `fetchURL` is provided via the launch query string and must be retrieved for every launch so that the AU can communicate with the LMS (LRS) as it provides the authentication credentials to do so. An AU can't be considered initialized (successful launch) until it has retrieved the fetch URL and used the response from it to retrieve other data and sent a statement. The URL itself is only to be used once (and so needs to be unique per session).
