### ISSUE TITLE
Best Practice around actor and security token

### ISSUE THREAD

**Issue by cawerkenthin** [AICC/CMI-5_Spec_Current#593]
I believe we need a best practice that the LMS/LRS validate that the actor in any allowed or defined statement is the actor that was originally sent to the content.  This would be an additional security check that one actor is not sending statements for another.

**Comment by MrBillMcDonald** [comment]
As per last meeting (4-05-2019)  we agreed that the LMS should use the Session ID and Auth Token to validate actor (to detect modification of actors in statements).

**Comment by MrBillMcDonald** [comment]
Best practice added 

Best Practice #15 – LMS should use the Session ID and authentication token to validate actor
