### ISSUE TITLE
Security In CMI-5 authentification 

### ISSUE THREAD

**Issue by jeansebbaklouti** [AICC/CMI-5_Spec_Current#596]
Hello,

thanks for this wonderful work. I have a question about the authentification of the AU.
https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#definition_auth_token

The Token is not checked with private/public key mechanism(or other mechanism), so AU cannot confirm that the LMS is trusted. So everybody can have access freely at the resource from AU. Am i right ?  I did not find anything else in the specification about security.

Best Regards,

**Comment by MrBillMcDonald** [comment]
Jean-Sébastien,

We do have a mechanism that addresses LMS trust (and controlling access to content) 

It is called "entitlementKey" - this is created by the AU developer and it is the AU's responsibility to validate the that the correct key is provided by the LMS.  (This is passed to the AU in a State document)

See entitlementKey in the following Sections:

- 10.0 xAPI State Data Model
- 13.1.4 AU Metadata

Sincerely,

cmi5 Working Group
