### ISSUE TITLE
Relocate moveOn to contextActivities.other[]

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#600]
Currently the cmi5 spec requires all Passed and Completed statements to include the following object in contextActivities.categories[]:

>           "objectType": "Activity",
>           "id": "https://w3id.org/xapi/cmi5/context/categories/moveon"

Providing the moveon object in contextActivities is important to leverage the xAPI query capability  to filter for moveOn related statements. ("related_activities" Statement Get query parameter).

While this is not in violation with the xAPI spec it violates the best practice for identifying xAPI profiles using the xAPI profile server.   The current version of cmi5 (quartz) still can have a profile definition that will work with the xAPI profile server but this is not optimal.   In order to better align with the xAPI profile server, the object should be moved to **_contextActivities.other[_**] in the next cmi5 release.

(Agreed per cmi5 working group meeting March 6th, 2020)

**Comment by brianjmiller** [comment]
Would be good to add the `Defer Until Next Major Release` label to this issue.

**Comment by MrBillMcDonald** [comment]
Per Feb 9th meeting -  our usage of contextActivities predated the profile spec and is aligned to the defined to the definition of how contextActivities is used in the xAPI specification.
