### ISSUE TITLE
Clarification of masteryScore in the context of section 10.0.

### ISSUE THREAD

**Issue by MattyKahler** [AICC/CMI-5_Spec_Current#603]
Hi all,

Just a quick issue regarding the below details. Hopefully this can help provide additional clarity around `masteryScore` so others don't run into the confusion I did! Thanks for giving this a look.

### Description of issue
The wording in [section 10.0][001] regarding `masteryScore` is slightly confusing, and it also looks like it's referencing incorrect sections. The documentation regarding masteryScore for AU usage currently states:
> If the AU issues "Passed" or "Failed" statements they MUST be based on the masteryScore provided. (See Sections 9.3.6 and 9.3.7)

From an AU logic handling perspective, the above statement can be interpreted to state that `masteryScore` will always be provided, and so an AU must always check against `masteryScore`. 

However, in my tests and parsing of the documentation I found that since `masteryScore` is optional for inclusion in the manifest, this means that `masteryScore` is not always provided to the AU. And so an AU does not in all circumstances need to check against `masteryScore`.

### Suggested corrections

- Modify section reference from [9.3.6  - Abandoned][002] to [9.3.4 - Passed][004]
- Modify section reference from [9.3.7  - Waived][003] to [9.3.5 - Failed][005]
- Slight modification to documentation text to give context that `masteryScore` may not always be provided. Example of such a suggestion with all suggestions included:
> If the AU issues "Passed" or "Failed" statements they MUST be based on the masteryScore if provided. (See Sections 9.3.4 and 9.3.5)

[001]: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#100-xapi-state-data-model
[002]: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#936-abandoned
[003]: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#937-waived
[004]: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#934-passed
[005]: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#935-failed

**Comment by MrBillMcDonald** [comment]
Review per May 22, 2020 cmi5 working group meeting. 

Clarfying changes applied per the following commit:

https://github.com/AICC/CMI-5_Spec_Current/commit/25e8ef100ee872b30e4987d6f4598ad9e6f90522
