### ISSUE TITLE
Update of client library?

### ISSUE THREAD

**Issue by timofeysie** [AICC/CMI-5_Spec_Current#606]
Since there are no issues tracker on the [client library](https://github.com/adlnet/cmi5-Client-Library) project, I'm asking this here.

I would like to use the cmi5Controller in a moder React app using TypeScript.  The library is over five years old now.  There are no issues tracked on that repo.  Are there any npm packages that could be used in a modern React app using TypeScript?

I can use the [React wrapper](https://www.npmjs.com/package/react-cmi5) but would also like to use the cmi5Controller  as demonstrated in [this article](https://aicc.github.io/CMI-5_Spec_Current/client/)

Are there any options to update the client library, put it on npm or has this already been done?

Thanks in advance for any help with this.

**Comment by MrBillMcDonald** [comment]
Timothy,

Thanks for bringing this to our attention.  An issue tracker has been added.

- https://github.com/adlnet/cmi5-Client-Library/issues 

We have no plans for React/TypeScript/npm at this time.  (However we are open to contributions !)

Sincerely,

The cmi5 Working Group
