### ISSUE TITLE
Working with CMI5

### ISSUE THREAD

**Issue by JPCannonNew** [AICC/CMI-5_Spec_Current#608]
Hi everybody.

My company is working on the PC learning app. We are creating it with Unity 3D. Our client prefere to have CMI5 profile LRS project to get raport's To their LMS. So we created some simple cmi5.xml file, and we are sending xApi statements to Scorm Cloud. We don't know how to merge this to CMI5 solution. I don't realy understand how does the CMI5 solution work.

We have cmi5.xml file. There we have some course ID and Activity ID created from link to some our site? And then we must to send statement's with the same activityID and courseID in some statement section? Or there are some another rules to set up this to work, and change some course state on Scorm Cloud.

I was even duplicate statement's from LRS Viewer from working "cmi5: AU Simulator (1.4.0) - Simple - AU" project. But even when thay was almoust the same (Id, sessionId, and autority was different) still status change to "passed" dosen't work in my version, but it work in "cmi5: AU Simulator (1.4.0) - Simple - AU" example. I realy don't understand the difference.

Thank you for any help

**Comment by MrBillMcDonald** [comment]
closed per Feb 9th meeting
