### ISSUE TITLE
cmi5 Adopter

### ISSUE THREAD

**Issue by barellano** [AICC/CMI-5_Spec_Current#612]
The [WP Courseware learning management system](https://flyplugins.com/wp-courseware) has adopted support for cmi5 via [Grassblade integration](https://www.nextsoftwaresolutions.com/experience-api-for-wp-courseware/)

**Comment by MrBillMcDonald** [comment]
Ben,

Thank you for you interest in cmi5  !

WP Courseware learning management system has been added to the cmi5 adopters list:
 
    https://aicc.github.io/CMI-5_Spec_Current/adoption/

Please let me know if you have questions.

Sincerely,

Bill McDonald
