### ISSUE TITLE
cmi5 Adopter

### ISSUE THREAD

**Issue by CookieCookson** [AICC/CMI-5_Spec_Current#613]
I have recently authored a JavaScript library ([xAPI.js - cmi5 profile](https://www.xapijs.dev)) to work with cmi5 in modern frontend tooling. I would love to have it added to the cmi5 adopters page within the Content Authoring Products.

**Comment by thomasturrell** [comment]
I've taken a look at the work that you have done, it looks excellent. I will consider using it in future projects. I am not aware of any other open source TypeScript xAPI libraries.

I suggest that you follow the [adoption instructions](http://aicc.github.io/CMI-5_Spec_Current/adoption/) on the cmi5 website. You may also wish to consider joining the [weekly meetings](https://github.com/AICC/CMI-5_Spec_Current/wiki/Weekly-cmi5-Working-Group-Meeting---Conferencing-Instructions).

**Comment by CookieCookson** [comment]
Hey @thomasturrell thanks for responding. As an outsider I am unable to add any labels myself, so following the adoption instructions I titled the issue with the tag instead. Would you like me to write a more extended description to meet the instructions on the cmi5 website? (They're pretty light on whats needed)

**Comment by thomasturrell** [comment]
@CookieCookson sorry, I didn't realise that it wasn't possible to follow the adoption instructions unless you had special privileges. I'm just a contributor to this repository, I have no additional rights.  @brianjmiller might be able to help you.

In the meantime perhaps you could create a pull request for the [adopters page](https://github.com/AICC/CMI-5_Spec_Current/blob/gh-pages/adoption/index.md) with the changes that you had in mind. I have no idea it will be accepted but its worth a try. Open pull requests are discussed during the weekly meetings.

**Comment by brianjmiller** [comment]
I have no special privileges either :-), probably best to submit a PR as Thomas mentioned. Note that the PR should target the `gh-pages` branch rather than `quartz` or any of the others. FWIW, our team has investigated the libraries and we are considering their use for the Catapult project, though it is a less than standard use case so it may or may not leverage them longer term. (We've found in the past that using a library that does things correctly can be more of a burden when trying to intentionally do things incorrectly.)

**Comment by CookieCookson** [comment]
Great shout! I've put together a PR at https://github.com/AICC/CMI-5_Spec_Current/pull/700.

That's exciting news to hear you are considering it's use for the Catapult project, let me know if there is anything I can do to support.

**Comment by thomasturrell** [comment]
@CookieCookson congratulations your pull request was merged. 

If everything is to your satisfaction, could you close this issue?

**Comment by CookieCookson** [comment]
Of course!
