### ISSUE TITLE
3.0 Definition of LMS two requirements for LRS?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#616]
The definition for "LMS" seemingly has two requirements around the LRS.

> The LMS MUST have an LRS as part of its implementation. The LMS MUST be integrated with an LRS.

Is there a reason for stating it two different ways?

It looks like the inclusion of the first part was supposed to be stricken when https://github.com/AICC/CMI-5_Spec_Current/issues/502 was done via https://github.com/AICC/CMI-5_Spec_Current/commit/91a4d3a184862188fdb084944729d9d1c7b8c714

**Comment by brianjmiller** [comment]
A more general question arising from this is whether "requirements" should be included in the definitions of terms.

**Comment by brianjmiller** [comment]
This "requirement" is loosely indicated again in section 6.0.

**Comment by MrBillMcDonald** [comment]
In the definition of terms, "LMS" has conformance language (MUST, shall)  - this section of the document  (section 3) does not cover conformance and such language is redundant.  (see below)

> **Learning Management System (LMS):** A computer system that may include the capabilities to register learners, launch learning presentations, analyze and report learner performance, and track learners' progress. LMS launching, reporting, and tracking roles are the focus of the cmi5 specification. The LMS MUST have an LRS as part of its implementation. The LMS MUST be integrated with an LRS. In the remainder of this document the term “LMS” shall refer to an integrated entity of LMS and LRS.

To correct this issue and clarify the proposed changed was agreed to by the group.

Replace:

> The LMS MUST have an LRS as part of its implementation. The LMS MUST be integrated with an LRS. In the remainder of this document the term “LMS” shall refer to an integrated entity of LMS and LRS.

With this:

> The LMS is integrated with an LRS. In the remainder of this document the term “LMS” refers to an integrated entity of LMS and LRS.
