### ISSUE TITLE
4.3 Optional JSON Values

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#617]
This section includes the requirement:

> All JSON properties included with non-null values MUST be recorded in the LRS.

But this is really a requirement from xAPI, is there another reason to include it here?

**Comment by MrBillMcDonald** [comment]
In this section, their is conformance language requiring that all JSON properties must be recorded.  This blanket statement is redundant as the other sections in the specification (and the xAPI specification) define which JSON properties are required,

> **4.3 Optional JSON Values**
> If JSON properties are indicated as "optional", you MAY leave such properties out of the JSON structure being described. All JSON properties included with non-null values MUST be recorded in the LRS.

The group agreed to strike the following sentence:

> All JSON properties included with non-null values MUST be recorded in the LRS.
