### ISSUE TITLE
6.0/7.0

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#618]
These sections are titled "Requirements" but the language used in them does not abide by the conventions listed in section 4.0. Should the individual bullet points be reworded to use the MUST language?

**Comment by MrBillMcDonald** [comment]
The group agreed to clarify the conformance language in sections 6.0 and 7.0 as follows:

Change: 


From: 

> **6.0 LMS Requirements**
> LMS requirements to conform to this specification are as follows:
> 

To:

> **6.0 LMS Requirements**
> The LMS MUST:
> 

From: 


> **7.0 AU Requirements**
> AU's requirements to conform to this specification are as follows:


To:

>**7.0 AU Requirements**
> An AU MUST:

The group agreed to clarify the conformance language in sections 6.0 / 6.1 as follows:

Change:
> * Implement course structures as defined in Section 6.1.
> **6.1 Course Structures**

To: 
> * Implement course handling as defined in Section 6.1.
> **6.1 Course Handling**
