### ISSUE TITLE
7.1.3/9.6.2.1 cmi5 defined statements

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#619]
From 7.1.3:

> "cmi5 defined" - Statements using cmi5 defined verbs, category id as defined in section 9.6.2.1, and context template.

This bullet point isn't really written as a requirement (i.e. using "MUST") but should it be? The following is in the testing requirements under 9.6.2.1_1: 

> The LMS must include An Activity object with an "id" of "https://w3id.org/xapi/cmi5/context/categories/cmi5" in the "category" context activities for all cmi5 defined statements it issues.

But that section is about the Activity but doesn't include the above as a MUST. As a reference it reads as:

> 9.6.2.1 cmi5 Category Activity
> An Activity object with an "id" of "https://w3id.org/xapi/cmi5/context/categories/cmi5" in the "category" context activities list to be used in cmi5 defined statements as described in section 7.1.3.

Probably one of the two of these needs to become an "official" requirement

**Comment by MrBillMcDonald** [comment]
The group reviewed section 9.6 which has a blanket MUST requirement for all subsections, but this section is the only one without a MUST requirement. To be consistent, the group agreed to add a MUST statement as follows:

> **9.6.2.1 cmi5 Category Activity**
> An Activity object with an "id" of "https://w3id.org/xapi/cmi5/context/categories/cmi5" in the "category" context activities list to be used in cmi5 defined statements as described in section 7.1.3.

Change to:

> **9.6.2.1 cmi5 Category Activity**
> An Activity object with an "id" of "https://w3id.org/xapi/cmi5/context/categories/cmi5" in the "category" context activities list MUST be used in cmi5 defined statements as described in section 7.1.3.

**Comment by brianjmiller** [comment]
Closed by #664.
