### ISSUE TITLE
8.2.1 fetch return structure

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#621]
There isn't really a requirement listed here about the structure of the response. The section indicates that the structure has to be JSON, and it then says there is an example.

Recommendation: Propose to add a new requirement(s) stating that the value of the JSON response MUST be an object and that the object MUST contain a property called `auth-token` which MUST have a value that is the authorization token needed to authorize xAPI requests made by the AU.

**Comment by brianjmiller** [comment]
This is somewhat covered in the 8.2.2 section that follows it, but it is seemingly specifically about the `auth-token` property itself.

**Comment by liveaspankaj** [comment]
Makes sense as long as it's clear that this is specifically about the
success case where the access is granted. In case of error or second access
to same url, the response object will be different.

**Comment by MrBillMcDonald** [comment]
The group agreed that clarification was needed to ensure the JSON structure is required as intended.  The group agreed to the following change:

Change the following from:

> **8.2.1 Overview**
> 
> The fetch URL MUST return a JSON structure using a Content-Type of "application/json". An example JSON structure is shown below:
> 

To:

> **8.2.1 Overview**
> 
> The fetch URL MUST return a JSON structure using a Content-Type of "application/json".   The structure MUST be an object with the property "auth-token".  An example JSON structure is shown below:
>
