### ISSUE TITLE
Fetch URL as single use is problematic in how the requirements read

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#623]
The fetch URL is intended to be single use only, but the requirements are generally conflicted to make that the case.

> The LMS MUST place the value for auth-token in a JSON structure, as shown in Section 8.2.1, in its response to a fetch URL request.

Indicates that the response *must* include the `auth-token` but doesn't indicate that it is only required (allowed) to do so in response to the first request. The other statements are SHOULDs, such as:

> The fetch URL is a "one-time use" URL and only the first request SHOULD return the auth-token. Subsequent requests made to the fetch URL during the session SHOULD generate an error.

Additionally the following statement is unnecessary (or in conflict):

> The error SHOULD be returned in the form of a JSON structure using Content-Type "application/json".

Because previous requirements indicate that the response MUST be a JSON structure.

**Comment by brianjmiller** [comment]
See #559

**Comment by MrBillMcDonald** [comment]
The following language proposed to be added:

> The fetch URL is a "one-time use" and MUST not return an auth-token more than once
