### ISSUE TITLE
9.1 Should the LMS be required to set the statement id

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#625]
> The AU MUST assign a statement id property in UUID format (as defined in the xAPI specification) for all statements it issues.

This indicates that the AU is required to do so, is it expected that the LMS "MUST" too?

**Comment by thomasturrell** [comment]
Out of interest, what is the rational for requiring that AU MUST set a statement id?  The same rational might apply to statements issued by the LMS.

**Comment by thomasturrell** [comment]
> Out of interest, what is the rational for requiring that AU MUST set a statement id? The same rational might apply to statements issued by the LMS.

I guess, one rational might be off loading the generation of the UUID to the AU from the LRS saves server processing time.

**Comment by MrBillMcDonald** [comment]
The intent was that the LMS "owns" the LRS (i.e. it is component of the LMS) and the xAPI spec requires an LRS to provide Statement ID's for incoming statements without statement ids.
