### ISSUE TITLE
9.3 Multiple Satisfied statements per Registration

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#627]
> LMS SHOULD NOT issue multiple satisfied statements (in a registration).

I think this is intended to include something along the lines of "per object (Block or Course)". As it is intended, I believe, that each block could have a satisfied statement recorded as well as the course. Those statements would be for the same registration.

**Comment by brianjmiller** [comment]
Related to #630

**Comment by MrBillMcDonald** [comment]
Recommend changing to a MUST NOT (from SHOULD NOT) in next release
