### ISSUE TITLE
9.3 Verbs

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#628]
> Regardless of the verbs the AUs use in statements, the LMS MUST record and provide reporting for all statements.

Presumably this isn't intended to apply to statements that are considered to break another requirement? For instance language in 6.3:

> The LMS MUST Void statements that are NOT rejected AND conflict with the "Statement API" requirements as defined in Section 9.

Which indicates that some statements may be rejected.

**Comment by MrBillMcDonald** [comment]
The group proposed the following verbiage for section 9.3:

> The LMS MUST record and provide reporting for all cmi5 defined and allowed statements that have not been rejected regardless of the verbs used in statements sent by AUs.

This will be reviewed again in follow-up meetings
