### ISSUE TITLE
9.3.9 Satisfied - Block/Course id generation wording should be improved

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#629]
> In this statement the LMS MUST use the LMS generated block id as the Object id (Section 9.4 - Object) and use "https://w3id.org/xapi/cmi5/activitytype/block" as the value of the "type" property in the Object's Definition.

> In this statement the LMS MUST use the LMS generated course id as the Object id (Section 9.4 - Object) and use "https://w3id.org/xapi/cmi5/activitytype/course" as the value of the "type" property in the Object's Definition.

The wording as it is currently suggests that a unique id be created each time the Satisfied statement is stored.

Should consider adding language similar to that which is included in Section 8.1 for `activityId`:

> The LMS MUST use the same generated activityId on all subsequent launches (for the same AU) within the same registration. The LMS SHOULD use the same generated activityId (for the same AU) for all registrations.

Alternatively the Section 9.4 about the Object could be beefed up to include the various requirements around the creation of ids and remove them from the other parts of the spec.

**Comment by brianjmiller** [comment]
Additionally the word "unique" should be determined to see if it needs to be more heavily specified.

**Comment by MrBillMcDonald** [comment]
Per May 28th meeting - draft PR for central reference (in Section 9.4 Object) for these Block and Course ID requirements:

**Comment by brianjmiller** [comment]
Satisfied via PR.
