### ISSUE TITLE
9.6.2.3 - Unclear need for requirement

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#633]
> The LMS MUST also include the publisher id Activity in the "grouping" context activities list for all "cmi5 defined" and "cmi5 allowed" statements it makes directly in the LRS.

Including the above requirement implies that the LMS statements don't have to include the regular context template fully, as otherwise there is no reason to include this as a requirement. Since the requirement for `contextActivities` reads as:

> All cmi5 defined statements must include all properties and values defined in the the contextActivites [sic] of the context template (see section 10 - xAPI State Data Model).

**Comment by MrBillMcDonald** [comment]
Per the May 28th meeting - discussed the following language:

> The LMS MUST include the publisher id Activity (associated with the object activity) for Satisfied and Waived statements in the "grouping" context activities list 

More discussion required

**Comment by MrBillMcDonald** [comment]
Reviewed per the June 24, 2022 meeting.

This was addressed the following update (may 2022):

https://github.com/AICC/CMI-5_Spec_Current/commit/ff3d18bef56bc1d6b465249210a937f624651782
