### ISSUE TITLE
Question about cmi5 spec

### ISSUE THREAD

**Issue by ahmadichsan** [AICC/CMI-5_Spec_Current#641]
Dear contributors, thank you for create this useful information about cmi5 spec.

A bit introduction, I'm trying to create a LMS that will launch cmi5 course. But, I've trouble in understanding about cmi5 package and some other terms. Here I would like to ask/clarify several points to make it clear.

I've seen TinCan/xAPI sample course/spec (I saw it [here](https://github.com/RusticiSoftware/TinCan_Prototypes)) and cmi5 spec [here](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md). I found out that they need different query string to launch the content.

To be precised, in TinCan, for the authentication, we could pass ```auth``` query string and the ```Basic {encoded username:password}``` as the value ([here](https://github.com/RusticiSoftware/launch/blob/master/lms_lrs.md) is the reference). The ```auth``` then processed by the TinCanJS package (I'm using Javascript). But, in the cmi5 spec, it said to get the token, we could pass ```fetch``` query string and the value is our lms that return one time token only. The ```fetch``` url will called with ```POST``` method.

But, I couldn't found "where is the ```fetch``` value being processed in the cmi5 course?" in the AU? I'm still confused with the terms of AU.
1. Who will create it?
2. How it looks like?
3. is it included in the cmi5 course or do I have (as the creator of LMS) to create the AU?

Thank you in advance.

**Comment by brianjmiller** [comment]
This was cross posted to StackOverflow and I happened to see it there first. See https://stackoverflow.com/questions/67239334/what-is-assignable-unit-in-cmi5-spec/67267679

**Comment by ahmadichsan** [comment]
thank you @brianjmiller for your response. I'll close the issue and continue the discussion on StackOverflow.
