### ISSUE TITLE
Possible re-heading of parameters in Section 8.1 and Section 10.0

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#693]
Right now the entire section 8.1 and section 10.0 falls under the single heading, and all of the individual parameters which are a table onto themselves don't have a separate sub-heading. But if you look at section 9.3 Verbs each verb which is effectively a separate table has the verb name pulled out and gets its own sub-heading. Proposing this for two reasons, a) I think it is nice to have the sub-headings and be in the TOC, b) sub-dividing the section is how I'm numbering the requirements in the test suite, so this will effectively make the requirement ids a bit better.

If the group agrees to this suggestion I can do the PR.

**Comment by MrBillMcDonald** [comment]
The group discussed and and agreed this change - PR pending
