### ISSUE TITLE
What are the best practices for the LMS implementing a means to edit course structures?

### ISSUE THREAD

**Issue by thomasturrell** [AICC/CMI-5_Spec_Current#708]
I am interested in best practices for the LMS implementing a [means to edit course structures](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#61-course-handling-requirements) 

I am concerned that it is possible to edit the course structure in such a way that makes it impossible to satisfy the course.

I believe that the [AU metadata](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#1314-au-metadata) for the following can only be changed with detailed knowledge of the AU behaviour:

* move on criteria (see #707)
* objectives
* launchParameters
* launchMethod

I believe that the AU metadata for the following must not be changed:

* activityType
* id
* entitlementKey

I see no negative side effects in changing the following:

* masteryScore
* title
* description

**Comment by thomasturrell** [comment]
I have noticed that the [Best Practices](http://aicc.github.io/CMI-5_Spec_Current/best_practices/) section on the website already covers some of these points.

> The AU may not have the capability of sending statements required by any moveOn value that was not in the original course structure. It is recommended that all changes to course structures after import be tested prior to learner assignment.

> LMS should use caution when adding Mastery Scores to AU course structure entries if they are not present in the original course structure. (As the AU may not be designed to handle scores). It is recommended that such changes be tested prior to enrolling learners.

**Comment by brianjmiller** [comment]
Related to #707

**Comment by MrBillMcDonald** [comment]
Reviewed per June 10th Meeting.

* Will monitor customer adoption/feedback of course structure / moveOn
* Will study possible extensions/best practices for course structure

**Comment by MrBillMcDonald** [comment]
Per Feb 16th meeting - no best practice or industry feedback has surfaced to date regarding this.  Closing this issue
