### ISSUE TITLE
What is the best practice for terminated statement?

### ISSUE THREAD

**Issue by thomasturrell** [AICC/CMI-5_Spec_Current#714]
The spec suggests monitoring the browser window for close (AKA unload) events, this is reasonable however it is not guaranteed. 

I believe that the spec or best practice section should emphasise that sending the terminated statement on close unreliable.

Ref:
MDN Web Docs [Window: unload event](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event)

**Comment by brianjmiller** [comment]
Is there something not covered by:

> Circumstances under which the AU may determine that the session is ending could include:
> 
> * Monitoring for browser window or application close events
> * An AU defined user action for closing the AU session
> * Other AU defined events such as a timeout from user inactivity

There is a certain point where basic development practices (like testing) can't all be enumerated by cmi5 best practices. There is just a point at which the level of fidelity of a given implementation is an acceptable differentiating factor (so long as they are still conforming to the **requirements** of the spec).

**Comment by thomasturrell** [comment]
> Is there something not covered by:

Not that I can think of but maybe the order could be changed to put greater emphasis on `An AU defined user action for closing the AU session` (presumable using the returnURL).

In the wild, I'm seeing almost zero terminated statements, but I'm mindful of the fact that I do not have a huge sample.

**Comment by andyjohnson** [comment]
Per the 6/25/2021 call, could consider removing the paragraph that has the bad "best practice" in 7.1.2 of listening for close events as a recommendation for sending a Terminated statement.

**Comment by MrBillMcDonald** [comment]
(Review per June 3, 20220 meeting)
