### ISSUE TITLE
Is resuming a session an implied LMS and AU requirement? 

### ISSUE THREAD

**Issue by thomasturrell** [AICC/CMI-5_Spec_Current#721]
There is no mention of resuming a session in the specification however I believe that it is an implied feature because an LMS is not required to mark a session as abandoned if the learner attempts to launch an AU that has an existing session (A learner could attempt to resume a session by navigating back to the LMS).

Resuming a session would seem to have multiple implications for the LMS and the AU. The LMS would not send an additional  launched statement, nor would it store or overwrite the launch data, nor would it generate a new fetch token. The AU would see that the session has been resumed and use the token as a key to look up the authorisation for this session.

The alternative that I can see is that the LMS marks a session as abandoned if the learner attempts to launch an AU that has an existing session.

Is there a favoured approach?

**Comment by brianjmiller** [comment]
I imagine this mostly depends on what you mean by "resuming" a session. You can only have one launched/initialized combination per session, can only get the authorization token once per session, and can only terminate/abandon once per session. So if you need to do any of those things more than once then there are necessarily multiple sessions. If the AU hasn't sent terminated and still has the authorization token (or a way to get it via means other than the fetch URL), and the LMS hasn't abandoned the session then the session is still open (so isn't really being resumed). Note that there can only be one active session *per registration* based on the requirements for determining abandoned, see:

> In the absence of a "Terminated" statement, the LMS MUST make the determination if an AU abnormally terminated a session by monitoring new statement or state API requests made for the same learner/course registration for a different AU.
(ref: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#936-abandoned)

Our implementation (and what Catapult will do once I get to it) is to mark a session abandoned if another session is being created (IOW a launch), based on the above requirement.

**Comment by thomasturrell** [comment]
My definition of resuming a session is:

the learner launches a course from the LMS
the LMS redirects the current window to the course URL
the learner presses back in their browser which takes them back the LMS
the learner launches the course again

If I understand you correctly, given the above scenario it would be ok for the LMS to terminate the session and create a new one.

I really appreciate your input. I know your a very busy man, I must owe you several beers!

**Comment by brianjmiller** [comment]
Generally this won't involve an interaction with the LMS (unless you were doing something with a proxied set of content) because the launch URL for the AU is the AU itself (either via a remote URL or via a content loading URL). Because of that it would be up to the AU to be able to handle the situation because a new session wouldn't be created. This is related to the best practice (17) about storing the authorization token, etc. in a local storage so that the AU can be re-entrant.

> Best Practice # 17 – Persist AU Session State
> There are certain situations, such as browser window refresh, that may inadvertently cause cmi5 errors related to operations that must occur only once in a session. To prevent such issues, AU’s should be designed to use non-volatile storage (local to AU) to preserve the state of following operations that have been performed during the session:
> 
> * Fetch URL token retrieval (which can only be called once in session)
> * All cmi5 defined statements that can only be sent once in a session.

Alternatively the AU would likely try to re-fetch the authorization token via the fetch URL and it will fail because that URL will have expired.

So in this case the LMS is completely outside of the handling (other than it may be providing the content) so it is just considered part of the session. If you consider that the definition of "resuming" the session then that makes sense, but there isn't really anything requirement related for that needed in the spec.

**Comment by andyjohnson** [comment]
Per the group on June 25, 2021 - Will revisit the Section 9.3.7 text as well as the notion of not allowing two simultaneous sessions for the same AU or same registration (however, it seems you could have simultaneous sessions for the same learner).  Multiple "open" sessions on the same AU or registration would lead to potential conflicting Statements or moveOn criteria (and cheating).

**Comment by MrBillMcDonald** [comment]
Per the July 9th meeting, the group agreeded to the following lanaguage:

> **9.3.6 Abandoned**
> 
> **LMS Obligations**	
> 
> If an LMS launches an AU with the same registration as an active session, the previous session with that registration MUST be abandoned.
> 
> In the absence of a "Terminated" statement, the LMS MUST make the determination if an AU abnormally terminated a session by monitoring new statement or state API requests made for the same learner/course registration for a different AU. 
> 
> The LMS MUST record an "Abandoned" statement on behalf of the AU indicating an abnormal session termination. The LMS MUST NOT allow any statements to be recorded for a session after recording an "Abandoned" statement.

**Comment by thomasturrell** [comment]
Agreed language resolves issue.
