### ISSUE TITLE
Unclear Requirements 

### ISSUE THREAD

**Issue by SaraSherif1** [AICC/CMI-5_Spec_Current#722]
1. Regarding to Session Id in State Document: In case that the learner opens the material for the second time whatever normal mode to complete the material or review mode, in this case there will be a state document for this user with this AU in LRS and this State document will contain a session Id, will we generate a new session id and update the value of session id in state document or use the same session id in existing state document?

2. In case of abnormal termination and AU has external URL (URL refer to material in external domain), will the AU send any notification for termination to LMS in this scenario?

3. regarding to Abandoned Verb : What I understand is this verb will be used to skip AU is this right?

**Comment by thomasturrell** [comment]
>  In case that the learner opens the material for the second time

I have the same / similar question myself, see #721

> In case of abnormal termination and AU has external URL (URL refer to material in external domain), will the AU send any notification for termination to LMS in this scenario?

In normal circumstances the AU will send a Terminated statement to terminate an LMS session. If for some reason the AU does not send a Terminated statement then the LMS should send an Abandoned statement.  How the LMS determines that the session was abandoned is implementation specific, it is not defined in the specification. The AU must not send Abandoned statements.

> Regarding to Abandoned Verb : What I understand is this verb will be used to skip AU is this right?

No, this is not the purpose of the Abandoned verb. You might want to take a look at the Waived verb.

**Comment by SaraSherif1** [comment]
> > In case that the learner opens the material for the second time
> 
> I have the same / similar question myself, see #721
>
> Hope we can find more explanation for this part

> > In case of abnormal termination and AU has external URL (URL refer to material in external domain), will the AU send any notification for termination to LMS in this scenario?
> 
> In normal circumstances the AU will send a Terminated statement to terminate an LMS session. If for some reason the AU does not send a Terminated statement then the LMS should send an Abandoned statement. How the LMS determines that the session was abandoned is implementation specific, it is not defined in the specification. The AU must not send Abandoned statements.
>
> Yes, if the AU will not send terminating statement I think we can set terminate the session if we didn't receive any statement within specific time
 
> > Regarding to Abandoned Verb : What I understand is this verb will be used to skip AU is this right?
> 
> No, this is not the purpose of the Abandoned verb. You might want to take a look at the Waived verb.
>
>Sorry it's a typo, I mean Waived Verb, is it mean to skip action?

**Comment by thomasturrell** [comment]
> I mean Waived Verb, is it mean to skip action?

Yes (if by action you mean AU).

The spec says:

> The LMS MUST also use the "Satisfied" statement when the learner has met the moveOn criteria for all AU's in a course

However an LMS may want to implement a way of allowing a learner to satisfy a course (or block) without the requiring the learner to fulfil the moveOn criteria for any number of AU's in a course. This is what the waived verb is for.

So for instance, if a learner is registered for a course but they have already completed one of the AU's in a different course, the learner could request that a privileged user (tutor, administrator, etc) waives their requirement to fulfil the moveOn criteria for this AU. However please keep in mind that is no requirement that an LMS has this functionality.

I would encourage you to validate what I have said by reading the relevant sections in the spec. The spec is the single point of truth.

**Comment by thomasturrell** [comment]
@SaraSherif1 Could you please close this issue if you are satisfied with my answer?

If you have any other issues please open a new issue.

**Comment by MrBillMcDonald** [comment]
Per the July 9th meeting , thee group agrees with Thomas' assessment

**Comment by SaraSherif1** [comment]
@thomasturrell , @MrBillMcDonald Thanks for your reply, but I still don't get a clear answer for the first question:
"Regarding to Session Id in State Document: In case that the learner opens the material for the second time whatever normal mode to complete the material or review mode, in this case there will be a state document for this user with this AU in LRS and this State document will contain a session Id, will we generate a new session id and update the value of session id in state document,  generate a new session id and create new state document, or use the same session id in existing state document?"
