### ISSUE TITLE
8.1.3 - actor requirement is likely problematic

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#726]
The requirement reads as:

> The AU MUST use the actor value in xAPI requests that require an "actor" property.

Unfortunately I think what we really meant was "agent" (or "agent or actor") because "actor" is specifically a thing limited to statements (and specifically in the payload). In other words requests like the State API and Agents Profile API resources take an `agent` query string parameter which we would expect to contain the actor as its value, but it is named `agent` not `actor`. Don't know if this is clear enough of a mistake to allow us to change it in this release.

**Comment by thomasturrell** [comment]
I believe that it should be changed because it is clearly a mistake. 

In practice I think it's a harmless, because as you point out there is no requirement to follow.

Is it analogous to saying "the AU must use green as a value in xAPI requests that require a 'color' property"?

**Comment by MrBillMcDonald** [comment]
Per the July 2nd meeting, The group agreed on the following clarifying language to address this issue: 

> The AU MUST use the _actor_ value in xAPI requests that require an "actor" property or that require an agent parameter.

A pull request will be created for this change
