### ISSUE TITLE
`audioPreference` value space not defined in requirement

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#728]
The closest the spec has is the following:

> The audioPreference value indicates whether the audio SHOULD be "on" or "off". 

But there isn't anything for `audioPreference` like there is for `languagePreference` where there is:

> The languagePreference MUST be a comma-separated list of RFC 5646 Language Tags as indicated in the xAPI specification (Section 5.2).

Since this isn't in there as a MUST this probably becomes an issue to fix for the next major release, but should probably be something like:

> The `audioPreference` value MUST be `"on"` or `"off"`.

I'm open to someone producing evidence that we can include this in the current release but I couldn't locate any.

**Comment by thomasturrell** [comment]
> Since this isn't in there as a MUST this probably becomes an issue to fix for the next major release

I agree.

**Comment by thomasturrell** [comment]
On July 2nd meeting, the group discussed captions and audio levels in a future version of the spec.

**Comment by MrBillMcDonald** [comment]
The group agreed to the following clarification (for the current spec):

> The audioPreference value SHOULD be either "on" or "off".  The AU MUST turn the audio on if the value is "on" and MUST turn the audio off if the value is "off".  Other values MAY be used.

(This is not a testable feature at this time)

The group also agreed that this property be expanded in a future spec version to address things like volume, captions, etc.

A pull request will be created for this.
