### ISSUE TITLE
9.6.3 - Clarify extension conflict requirement

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#729]
The requirement reads:

> Statements MUST NOT include extensions that conflict with or duplicate the ones specified here.

What is this trying to prevent?

"Duplicate" values aren't really a thing in JSON so does "duplicate" here mean within the same statement? 

What is "conflict" intended to mean? The best I could come up with is that something like `launchURL` or `moveOn` shouldn't be included in non-launched statements.

**Comment by MrBillMcDonald** [comment]
Per the July 2nd meeting, the group agreed that this this statement is a redundant and other more specific (testable) requirements already exist to adequately meeting the intent.  

A PR will be created to remove.
