### ISSUE TITLE
languagePreference refers to the wrong xAPI spec section

### ISSUE THREAD

**Issue by gavbaa** [AICC/CMI-5_Spec_Current#734]
(promoted from a conversation on #731)

As it stands, the language preference requirement is referring to the wrong place in the xAPI spec (currently it should be pointed to 4.2, and in the future it should be pointed to 4.2.7 for LRSes or 5.2.7 for Content), but both of those are actually "Language Maps", which is a dictionary, not an array. At very least even if we don't change anything else, I think we should remove the reference to the xAPI spec completely and just say they are RFC5646 language tags.

xAPI 1.0.3 Language Maps: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#42-language-maps
xAPI 2.0 (for LRSes) Language Maps: https://gitlab.com/IEEE-SA/xapi/9274.1.1/xapi-base-standard-documentation/-/blob/master/9274.1.1%20xAPI%20Base%20Standard%20for%20LRSs.md#427-additional-requirements-for-data-types
xAPI 2.0 (for Content) Language Maps: https://gitlab.com/IEEE-SA/xapi/9274.1.1/xapi-base-standard-documentation/-/blob/master/9274.1.1%20xAPI%20Base%20Standard%20for%20Content.md#527-additional-requirements-for-data-types

**Comment by thomasturrell** [comment]
> I think we should remove the reference to the xAPI spec completely and just say they are RFC5646 language tags.

I agree with this.

**Comment by MrBillMcDonald** [comment]
Per the July 16th meeting, the group agreed to clarify languagePreference as follows:

> 
> **11.1 languagePreference**
> 
> The languagePreference MUST be a comma-separated list of RFC 5646 Language Tags. In the list, languages MUST be specified in order of user preference. In the example below, the user's first preference for language is en-US. The user's second preference for language is fr-FR and the third preference is fr-BE.

**Comment by MrBillMcDonald** [comment]
pull request applied
