### ISSUE TITLE
Best Practice 1: why `parent`?

### ISSUE THREAD

**Issue by brianjmiller** [AICC/CMI-5_Spec_Current#740]
From the website: 

> Best Practice #1 – Use of Objectives
> (Since Objectives usage outside of course structure is not defined.)
> 
> Objectives are defined for the course structure, but there is no language in the specification concerning their usage in statements. If an AU is using Objectives in statements, the best practice is to add the objective (with the same objective id provided in the course structure) to the context activities “parent” property as an activity type of (http://adlnet.gov/expapi/activities/objective) from the ADL vocabulary.

Why is `parent` the suggested property to use here? I would not think of an objective as a parent, as a block or course would be for instance? AFAIK there is no hierarchical nature to objectives, so I'd think a better practice would be to include them in `grouping` (or less good `other`).

**Comment by cawerkenthin** [comment]
I am not opposed to changing it, but I have seen some content that is using it now.   Since it is a best practice, maybe that is not such a big deal.

**Comment by MrBillMcDonald** [comment]
This was previously discussed in multiple meetings and no better alternatives for "Parent" where found.
