### ISSUE TITLE
Section 5.0 refers to terminate without initialize

### ISSUE THREAD

**Issue by gavbaa** [AICC/CMI-5_Spec_Current#745]
The Conceptual Model section of the spec goes into some detail about the AU workflow, including a reference to sending a statement with a terminate verb.  However, you can't send a terminate without an initialize, and nowhere in the conceptual model do we point out where that should be.  I suggest that we introduce a bit on this to the conceptual model section.

**Comment by cawerkenthin** [comment]
:+1:
