### ISSUE TITLE
Launching AU

### ISSUE THREAD

**Issue by SaraSherif1** [AICC/CMI-5_Spec_Current#752]
There are two questions regarding launching AU:

1. As mention in issue #721

> "If an LMS launches an AU with the same registration as an active session, the previous session with that registration MUST be abandoned.
> 
> In the absence of a "Terminated" statement, the LMS MUST make the determination if an AU abnormally terminated a session by monitoring new statement or state API requests made for the same learner/course registration for a different AU.
> 
> The LMS MUST record an "Abandoned" statement on behalf of the AU indicating an abnormal session termination. The LMS MUST NOT allow any statements to be recorded for a session after recording an "Abandoned" statement."

- Is this mean that the "Abandoned" statement will be send in case when the learner opens any other AU in the same course in the existing of an active session for another AU, in another word if learner opens **AU1**  then opens **AU2** without closing **AU1** "AU1 has active session for this learner" will LMS send  "Abandoned" statement for **AU1** before launching **AU2**?

2. Regarding to Session Id in State Document: In case that the learner opens the AU for the second time whatever the launchMode is normal mode to complete the material or review mode, in this case there will be a state document for this user with this AU in LRS and this State document contains a session Id, which one of the below scenarios will be applied?
- LMS will generate a new session id and update the value of session id in old state document 
- LMS will generate a new session id and create new state document 
- LMS will use the same session id with the existing state document

**Comment by brianjmiller** [comment]
> Is this mean that the "Abandoned" statement will be send in case when the learner opens any other AU in the same course in the existing of an active session for another AU, in another word if learner opens AU1 then opens AU2 without closing AU1 "AU1 has active session for this learner" will LMS send "Abandoned" statement for AU1 before launching AU2?

Yes, as long as it is the **same registration**.

For 2, I believe the intention is (1) but there really isn't any meaningful distinction between (1) and (2) if the rest of the document isn't changing via some other influence. Either way it is expected that the AU retrieves the State document during initialization, so regardless of whether it is a new document or a changed document should be irrelevant to the AU.  (3) is the only scenario that is never intended to be the case.
