### ISSUE TITLE
Sending Satisfied Statement (CMI5)

### ISSUE THREAD

**Issue by JoYacoub22** [AICC/CMI-5_Spec_Current#753]
As mentioned in CMI5 Documentation that **"The LMS MUST use the "Satisfied" statement when the learner has met the moveOn criteria of all AU's in a block."** which means if the AU material has "Passed" in "MoveOn" criteria and the student successes to pass it, the LMS will send satisfied statement to LRS.

In this scenario, what if the AU has been sent "Failed" statement, LMS Should send "Satisfied" statement?

The meaning of my question is that if any AU material is sent "Passed" or "Failed" statement, means that the student has viewed all material content to the end so the "Satisfied" statement should be sent in both cases.

**Comment by gavbaa** [comment]
If you look here: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#moveon , you'll see an exact list of what `moveOn` criteria go with what statements.  In the case of a "Failed", there are no `moveOn` criteria that would satisfy as "NotApplicable" would have already satisfied the AU long before the learner got there, and the other criteria require some combination of a "Passed" or "Completed" statement to trigger satisfaction on the AU. 

To directly answer your question:

> In this scenario, what if the AU has been sent "Failed" statement, LMS Should send "Satisfied" statement?

None.

> The meaning of my question is that if any AU material is sent "Passed" or "Failed" statement, means that the student has viewed all material content to the end so the "Satisfied" statement should be sent in both cases.

In this case, you should use the `moveOn` criteria of "Completed" and have the course send a "Completed" verb when they've reached completion of the material.
