### ISSUE TITLE
Define RDF terms for CourseStructure elements and relationships

### ISSUE THREAD

**Issue by phtyson** [AICC/CMI-5_Spec_Current#755]
Being able to express a cmi5 course structure in a standard RDF or JSON-LD vocabulary would facilitate interoperability with other components of an xAPI ecosystem and enterprise ontology. Many of the CourseStructure elements are already represented in cmi5.ttl, but some are not (for example, au). Nor are there predicates to state the relationship of course to block or au, or block to au. Is there any interest in extending cmi5.ttl to cover CourseStructure ontology?

**Comment by MrBillMcDonald** [comment]
xAPI Profile Specification changes have been proposed to better fit cmi5. 

The group plans to use xAPI Profile server once updated

(Review per June 3, 20220 meeting)
