### ISSUE TITLE
cmi5 course registration vs xapi context.registration

### ISSUE THREAD

**Issue by phtyson** [AICC/CMI-5_Spec_Current#756]
The xapi specs 1.0.3 and 2.0.0 define "registration" as "An instance of an Actor experiencing a particular Activity."
The cmi5 quartz spec defines it as "An enrollment instance of a learner in a course. (a registration ID uniquely identifies this). The registration ID persists throughout the course progress to completion and during review of a completed course. A new registration is created for new enrollment instances (such as recurrent courses or re-taking courses)."
Throughout the cmi5 spec, "registration" is sometimes mentioned with respect to an AU, and other times as "course registration"
Should cmi5 LRPs put the cmi5 course registration in the context.registration for all statements for all AUs in the course? That, along with the AU id in context.contextActivities.grouping[] array, should support reporting on a complex course learning record.
In any case, it would be good to add an explanatory note with the cmi5 "registration" definition to clarify that it is an extension and refinement of the xAPI "registration", and also to clarify the text where "registration" is used.

**Comment by thomasturrell** [comment]
> Should cmi5 LRPs put the cmi5 course registration in the context.registration for all statements for all AUs in the course? 

Yes the registration is required in the [context](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#96-context).

> That, along with the AU id in context.contextActivities.grouping[] array, should support reporting on a complex course learning record.

In my experience the contextActivities statement property is less useful than it might appear; however, your use case might be different to mine.  It's important to note that it is the Publisher ID is used in the grouping list, the publisher ID for an AU might not be globally unique, i.e. it could appear in other courses on the same LMS.

> In any case, it would be good to add an explanatory note with the cmi5 "registration" definition to clarify that it is an extension and refinement of the xAPI "registration", and also to clarify the text where "registration" is used.

The registration referred to in the cmi5 spec is the xAPI registration, it is not an extension. The concept of registering for a course is not defined in cmi5 or xAPI, vendors are free to implement the concept however they think best.

**Comment by MrBillMcDonald** [comment]
The Purpose of requiring registration is to enable sorting of data and identify all activities associated with course enrollment regardless of AU.  (Review in June 3, 2022 meeting)
