### ISSUE TITLE
Clarify that a moveOn of "NotApplicable" means that the LRS has to satisfy the block/course BEFORE launching

### ISSUE THREAD

**Issue by cars10** [AICC/CMI-5_Spec_Current#757]
The spec only says the following about `NotApplicable` (in 13.1.4):

> moveOn Value = "NotApplicable": The LMS will consider the AU satisfied.

But the CATAPULT LTS includes a test that checks that an LMS has to satisfy a block/course before the AU is even launched: https://github.com/adlnet/CATAPULT/blob/main/lts/__tests__/runtime.js#L351

I cannot find a single sentence in the spec that specifically states that you have to satisfy the block/course BEFORE launch. This is only mentioned on the website under [best practices #6](https://aicc.github.io/CMI-5_Spec_Current/best_practices/) : 

> When failing to specify moveOn criteria or specifying “NotApplicable” as the moveOn criteria for all AU’s in a course, the course will automatically being marked satisfied **immediately upon registration** of the learner (before the learner launches a single AU).

**Comment by gavbaa** [comment]
It's addressed in 9.6.1: https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#961-registration

```The LMS MUST evaluate MoveOn criteria in the course structure at the time of registration. For example, AUs with MoveOn criteria of "Not Applicable" in the course structure would be evaluated and could generate Satisfied statements at this time.```

The MUST here means that the "could" in the next sentence is implicitly a MUST as well.

**Comment by cars10** [comment]
> The MUST here means that the "could" in the next sentence is implicitly a MUST as well.

Good to know. I would propose to change "Not Applicable" to "NotApplicable" here, thats why i did not find it (only searched for "NotApplicable").
