### ISSUE TITLE
xAPI Profile Rules - Composable Templates and Statement Template Satisfaction (via Statement Template Validator)

### ISSUE THREAD

**Issue by MrBillMcDonald** [AICC/CMI-5_Spec_Current#760]
Per the Dec 3 Meeting.  

Continue discussion of how cmi5 can be expressed as an xAPI Profile per the spec (and identify xAPI profile spec deficiencies) 

Discuss cmi5 Use case for Composable Templates and Statement Template Satisfaction (via Statement Template Validator)

**cmi5 Example (to enable composability):**
• One statement template for (base) cmi5 statements
• One statement Template for cmi5 allowed statements
• One statement Template for cmi5 defined statements

**Comment by gavbaa** [comment]
I've put together a set of statement templates that shows how you could potentially compose these, as well as one additional verb statement template (initialized) to show what you would want to additionally compose (as each cmi5 defined verb has rules specific to them):

```
    "templates": [
        {
            "id": "https://w3id.org/xapi/cmi5#baserestrictions",
            "type": "StatementTemplate",
            "inScheme": "https://w3id.org/xapi/cmi5/v1.0",
            "prefLabel": {
                "en": "Base Restrictions"
            },
            "definition": {
                "en": "Base restrictions for all cmi5 Statements (allowed or defined)"
            },
            "rules": [
                {
                    "location": "$.id",
                    "presence": "included"
                },
                {
                    "location": "$.timestamp",
                    "presence": "included"
                },
                {
                    "location": "$.context.contextActivities.grouping[*]",
                    "presence": "included",
                    "scopeNote": {"en": "An Activity object with an 'id' property whose value is the unaltered value of the AU's id attribute from the course structure (See Section 13.1.4 AU Metadata – id) MUST be included in the 'grouping' context activities."}
                },
                {
                    "location": "$.context.extensions['https://w3id.org/xapi/cmi5/context/extensions/sessionid']",
                    "presence": "included"
                }
            ]
        }, 
        {
            "id": "https://w3id.org/xapi/cmi5#definedrestrictions",
            "type": "StatementTemplate",
            "inScheme": "https://w3id.org/xapi/cmi5/v1.0",
            "prefLabel": {
                "en": "cmi5 Defined Restrictions"
            },
            "definition": {
                "en": "Restrictions for all cmi5 Defined Statements"
            },
            "rules": [
                {
                    "location": "$.context.contextActivities.grouping[*]",
                    "presence": "included",
                    "scopeNote": {"en": "An Activity object with an 'id' property whose value is the unaltered value of the AU's id attribute from the course structure (See Section 13.1.4 AU Metadata – id) MUST be included in the 'grouping' context activities."}
                }
            ]
        },
        {
            "id": "https://w3id.org/xapi/cmi5#allowedrestrictions",
            "type": "StatementTemplate",
            "inScheme": "https://w3id.org/xapi/cmi5/v1.0",
            "prefLabel": {
                "en": "cmi5 Allowed Restrictions"
            },
            "definition": {
                "en": "Restrictions for all cmi5 Allowed Statements"
            },
            "rules": [
                {
                    "location": "$.context.contextActivities.grouping[*]",
                    "presence": "excluded",
                }
            ]
        },
        {
            "id": "https://w3id.org/xapi/cmi5#initialized",
            "type": "StatementTemplate",
            "prefLabel": {
                "en": "Initialized"
            },
            "definition": {
                "en": "Initialized some event"
            },
            "inScheme": "https://w3id.org/xapi/cmi5/v1.0",
            "verb": "http://adlnet.gov/expapi/verbs/initialized",
            "rules": [
                {
                    "location": "$.result.score",
                    "presence": "excluded"
                },
                {
                    "location": "$.result.success",
                    "presence": "excluded"
                },
                {
                    "location": "$.result.completion",
                    "presence": "excluded"
                },
                {
                    "location": "$.context.contextActivities.category[*].id",
                    "none": ["https://w3id.org/xapi/cmi5/context/categories/moveon"]
                }
            ]
        }
    ]
```

In practice, what we would want is a way to say: xAPI Profile Validator, do we have a valid cmi5 statement?  To do so, we would need to match one of the following collections of templates:

* ["https://w3id.org/xapi/cmi5#baserestrictions", "https://w3id.org/xapi/cmi5#definedrestrictions", "https://w3id.org/xapi/cmi5#initialized"]
* ["https://w3id.org/xapi/cmi5#baserestrictions", "https://w3id.org/xapi/cmi5#allowedrestrictions"]

You have to match all the statement templates in a given array for the statement to be valid cmi5.  Matching #baserestrictions but not matching #definedrestrictions or #allowedrestrictions would be an invalid cmi5 statement.

In a full cmi5 definition, we would need a pairing for each verb most likely.  We might be able to lump a few together as they have some additional shared rules.

The questions that fall out from this:

* Using the xAPI Profile Statement Template Validation, is there a way we can ask the question: "do we have a valid cmi5 statement?"
* Given that matching only one template does not mean we have a valid cmi5 statement in the definitions above, we're really asking, "can we use the Statement Template Validation to match one set of templates at once, out of a set of sets of templates?"
* Besides either of the above questions, can we build a pattern that would allow us to match more than one Statement Template within a single `sequence` slot?

If the xAPI Profile Algorithms don't currently support this sort of DRY composition of Statement Templates, why not?   Is this something that should change/be supported?

**Comment by gavbaa** [comment]
@andyjohnson Where should we take the above writeup to have the xAPI Profile folks weight in?

**Comment by MrBillMcDonald** [comment]
xAPI Profile Specification changes have been proposed to better fit cmi5. (Review per June 3, 20220 meeting)
