### ISSUE TITLE
cmi5 Adopter

### ISSUE THREAD

**Issue by Adam-Reynolds** [AICC/CMI-5_Spec_Current#762]
dominKnow ONE is dominKnows flagship authoring tool and has supported xAPI since tincan 0.8 days and adopted CMI5 last year - https://www.dominknow.com/blog/our-seven-favorite-new-features-in-the-dominknow-one-summer-2021-feature-release

**Comment by MrBillMcDonald** [comment]
Adam,

Added  to the Adopters list.

 Sorry for the delay

Sincerely,

Bill McDonald
