### ISSUE TITLE
cmi5 Adopter

### ISSUE THREAD

**Issue by scottwmatthews** [AICC/CMI-5_Spec_Current#768]
Greetings - We'd like to list our LMS. The elli LMS from Learning Evolution that uses the Rustici Software SCORM Cloud (LMS/LRS) on the backend. Thank you, Scott Matthews, CEO.  contact email; smatthews@learningevolution.com - office # (619) 342 7877

**Comment by MrBillMcDonald** [comment]
Scott,

Excellent news !   Please Provide/Verify the following:

- A link to product page/website
- The Title of the Product as you would like it displayed  (e.g. "Learning Evolution - elli LMS")
- Type of product (LMS or Content Authoring Tool) (e.g. "LMS")

If you have not already done so, see the cmi5 Adoption Page for examples of the other cmi5 enabled product listings:
- https://aicc.github.io/CMI-5_Spec_Current/adoption/

**Comment by scottwmatthews** [comment]
Hi Bill - Thank you. I have included the information requested below. Let me know if this works ok.

Also, please note that we are in the process of updating our website LMS pages to provide all new and current information.

Thanks, Scott
Email, call or text at 314-614-3998


  *   A link to product page/website - https://www.learningevolution.com/hosted-learning-solutions?hsLang=en
  *   The Title of the Product as you would like it displayed. "elli LMS powered by Learning Evolution"
  *   Type of product (LMS or Content Authoring Tool) - "LMS"

**Comment by MrBillMcDonald** [comment]
Scott, 

very sorry for the delay, it is posted now  

https://aicc.github.io/CMI-5_Spec_Current/adoption/

**Comment by scottwmatthews** [comment]
Thank you!
