### ISSUE TITLE
cmi5 Adopter

### ISSUE THREAD

**Issue by bretweinraub** [AICC/CMI-5_Spec_Current#769]
* A link to product page/website

https://bright.aura-software.com

* The Title of the Product as you would like it displayed (e.g. "Learning Evolution - elli LMS")

Bright Platform for WordPress

* Type of product (LMS or Content Authoring Tool) (e.g. "LMS")

LMS/LMS Middleware

**Comment by MrBillMcDonald** [comment]
Bret,  

Sorry for delay, the adopters page is updated.  

see https://aicc.github.io/CMI-5_Spec_Current/adoption/
