### ISSUE TITLE
update Section 1.2 adding <code></code> tag html markup in addition to md backticks

### ISSUE THREAD

**Issue by MartinKoob** [AICC/CMI-5_Spec_Current#789]
Section 1.2 only mentions Back Ticks (`) as a way of marking up  terms to be rendered as code.  

>  Style Conventions
> This document uses the following style conventions:
> 
> Back Ticks ( ` ) – (rendered as "inline code depending on document rendering”) for all literal names of verbs and properties.

Within the document there are html formatted blocks within which any you have to use <code></code> tags to get the same rendering.

**Comment by MrBillMcDonald** [comment]
Per May 5th meeting add:

Inline code - All literal names of verbs and properties will be rendered as “inline code” (using markdown back ticks (\` )  or \<code\> tags within HTML blocks)`

**Comment by MrBillMcDonald** [comment]
closed per 6/30 meeting
