### ISSUE TITLE
'Section' should be capitalized when it is a reference to a specific section

### ISSUE THREAD

**Issue by MartinKoob** [AICC/CMI-5_Spec_Current#790]
In most instances in the document if there is a reference to a specific section it is capitaliezed:

e.g. 

> See Section 9.3.1 Launched

There are a few places where 'section' is not capitalized.

**Line   |   To be capitalized**
458   |   section 9.6.2.1

459   |   section 9.6.2.1

528   |   section 8.1.2

529   |   section 8.2.2

592   |   section 8.2.3

920   |   section 10

924   |   section 7.1.3

993   |   section 8.1

1005   |   section 9.6.2.3

**Comment by MrBillMcDonald** [comment]
Per May  5th Meeting - Capitalize **_Section_**
