### ISSUE TITLE
Punctuation and grammatical edits for text in table fields “Description”, “LMS Usage”, and “Value Space”

### ISSUE THREAD

**Issue by MartinKoob** [AICC/CMI-5_Spec_Current#799]
_**NOTE: This issue description is a work in progress.   Especially the formatting.**_

## Fields “Description” & “LMS Usage”

The “Description”, “LMS Usage” fields in the tables is usually written as a full sentence with a period. E.g.

   8.1
   8.2
    9.3

The following “**Description**” or “**LMS Usage**” fields have incomplete sentences for two possible reasons:
	
*- missing a period at the end of the text, or  *
*- missing an article at the beginning of the text i.e. ‘A’, 'An', or ‘The’.*
	
**9.5.5.2 reason**
     **Description:**	Indicates the reason why an AU was waived (marked complete by an alternative means)

*- missing period*
*-    Incomplete sentence. *   
*(add ‘This’ to beginning of sentence)*
	
**9.6.3.1 session ID**
     **Description:**	A unique identifier for a single AU launch session based on actor and course registration

*- missing period*
	
**9.6.3.2 masteryScore**
     **Description:**	masteryScore as provided in the LMS.LaunchData document for the AU and is used to determine the pass/fail result based on score  - missing period - Sentence incomplete 

*- add ‘The’ at the beginning of the sentence.  (Compare with 10.2.4 masteryScore)*
	
**9.6.3.3 launchMode**
     **Description:**	Indicates what launch mode an AU was launched with by the LMS  

*- missing period *
	
**9.6.3.4 launchURL**
     **Description:**	The URL used by the LMS to launch the AU

*- missing period *

**9.6.3.6 moveOn**
     **Description:**	The moveOn value as provided in the LMS.LaunchData document for the AU  

*- missing period*
	
**9.6.3.7 launchParameters**
     **Description:**	launchParameters as provided in the LMS.LaunchData document for the AU

*- missing period*
_- Sentence incomplete_
        - *add ‘The’ at the beginning of the sentence.  (Compare with 9.6.3.6 moveOn) *
	
**10.2.1 contextTemplate**
     **Description:**	contextTemplate for the AU being launched.  

*- Sentence incomplete *
    *- add ‘The’ at the beginning of the sentence. (Compare with 10.2.3 launchParameters)*
	
**10.2.1 contextTemplate**
     **LMS Usage:** The LMS MUST include a contextTemplate object and MUST include the following values:

- The value for session id placed in an extensions object with the ID as defined in Section 9.6.3.1.
- The publisher ID Activity as defined in Section 9.6.2.3 in the contextActivities.grouping list
    
*- missing period after second bullet point. * 
    *(or should list be formatted with ‘:’ with a comma after line 1 and  period after line 2.)*
	
**13.1.2 Block Metadata**
     **title**
 
          **Description:**  A descriptive title for the Block of AUs

*- missing period*

**13.1.4 AU Metadata**
    **url**

         **Description:**  To accommodate "non-browser" applications, an application specific protocol MAY be used in the url: `<application>://<URL to content> `

*- missing period*

## Punctuation and grammatical edits for text in table field “Value Space”: Multi word 

“Value Space” fields in some cases are written as a sentence or a phrase. To be consistent they should all be written as a sentence with a period.

**13.1.2 Block Metadata**
**id** 

**Value space:** Values defined by course designer

*- missing period *
          
In the following section there is a list of items in the Value space.  The values are formatted as one blockquote and the values are quoted.

**13.1.3 Objective Metadata** 
**moveOn** 

     **Value** space:
```
     <blockquote>
          "Passed" 
          "Completed" 
          "CompletedAndPassed" 
          "CompletedOrPassed" 
          "NotApplicable" 
     </blockquote>
```
In other sections Value Space fields that have a list  of a limited set of allowed values formats them as a quoted list separated by commas.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;E.g.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**10.2.2 launchMode**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Value Space:** "Normal", "Browse", or "Review"

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**13.1.4 AU Metadata**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Launch Method**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     **Value Space:** "OwnWindow", "AnyWindow"
	
So should this be formatted as follows?
**13.1.3 Objective Metadata** 
**moveOn** 

     **Value** space: "Passed”,” Completed”, ”CompletedAndPassed”, “CompletedOrPassed”, "NotApplicable" 

## Punctuation and grammatical edits for text in table field “Value Space”: Single word

There are also some value spaces that are one word such as 'URL'.  In other spaces it has a value that can be expressed as one word but it formats them as a short sentence e.g. 'Any URL'.  What should a consistent way to write these?
e.g.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**8.1.5 activityId**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Value space:** IRI

Should they be written in the Value Space as a single word with no punctuation,
e.g. 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**9.6.3.4 launchURL**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Value Space:** URL

OR, should they be written as a sentence with an article and a period.
eg. 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**10.2.6 returnURL**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Value Space:** Any URL.

## Punctuation and grammatical edits for text in other sections

The following section at the beginning of the document has a mix of punctuation for the bullet points.

&nbsp;&nbsp;&nbsp;&nbsp;**Revision History**
&nbsp;&nbsp;&nbsp;&nbsp;Versioning in the cmi5 specification is managed in the following manner:

&nbsp;&nbsp;&nbsp;&nbsp;- Major Version – Stones (Sandstone, Quartz, etc.) – Major changes in functionality
&nbsp;&nbsp;&nbsp;&nbsp;- Minor Version – Editions (1st edition, 2nd edition, etc.) – Minor changes in functionality.
&nbsp;&nbsp;&nbsp;&nbsp;- Errata – Minor corrections that do not affect functionality are not versioned. 
&nbsp;&nbsp;&nbsp;&nbsp;(See GitHub repository for specific revision history)

 *- missing period in Lines 1 & 3 — it is present in Line 2. So should have all end with a period.*

Thanks for any feedback on this.

Martin Koob

**Comment by MrBillMcDonald** [comment]
Changes agreed for this Issue (Per 7-14-2023) Meeting.

- Apply periods
- Change value space to list
- Value Space: URL

**Comment by MartinKoob** [comment]
Hi Bill

I will make the changes from the issue #799 https://github.com/AICC/CMI-5_Spec_Current/issues/799 and I will try to close the issue by including the ‘close #[issue number]’ syntax in the Pull Request comment.  Last week someone said doing that would automatically close the PR.  We will see if that works.

For the items in issue #799 that are not addressed in this pull request I will create a new issue  and copy them over.

See you next week.

Martin

**Comment by MartinKoob** [comment]
This issue was discussed at the working group meeting on Aug 4, 2023.  A few more revisions were made and then merged into the main branch.  So this issue is now closed. 

Close issue #800
