### ISSUE TITLE
References to ‘xAPI Specification’ in Sections 8.1.2, 8.2.2  and 8.3 are awkward and inconsistent.

### ISSUE THREAD

**Issue by MartinKoob** [AICC/CMI-5_Spec_Current#803]
There are three instances where the the xAPI specification is referred to in a way that is not consistent with other parts of the document and that appear either awkward or as an incomplete sentence.

### [Section 8.1.2 fetch](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#812-fetch)

> **AU Usage:**
> The AU MUST get the fetch value from the query string. The AU MUST make an HTTP POST to the fetch URL to retrieve the authorization token as defined in Section 8.2. The AU MUST place the authorization token in the Authorization headers of all HTTP requests made to the endpoint **using the xAPI.** The AU SHOULD NOT make more than one post to the fetch URL.

In the field "AU Usage" above the following phrase,

> ’using the xAPI.’ 

sounds awkward but is a complete sentence if you expand the acronym.
E.g.

> '… using the Experience API.' 

Alternately the following sounds better with the acronym 

> ’…using xAPI.’ 

but sounds awkward and appears to be an incomplete sentence with the acronym expanded.

> ‘… using Experience API.” 

### [Section 8.2.2 Definition: auth-token](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#822-definition-auth-token)

> AU Usage:	

> The AU MUST get the auth-token value using an HTTP POST to the fetch URL. The AU MUST then place the authorization token in the Authorization headers of all HTTP requests made to the endpoint **using the xAPI.**

### [8.3 Other Launch Environments](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#83-other-launch-environments)

> Other launch environments are not currently implemented in this specification. cmi5 implementations for LMS's and AU's in these other environments will use the same REST communication interface as specified in **xAPI specification**. The xAPI specification does not specify launch mechanisms.

In this section above both the acronym and the expanded acronym sound awkward.  
	- ‘as specified in xAPI Specification.
	- ‘as specified in Experience API Specification.

### Suggested revisions

In other places in the document that use ‘the xAPI’ it is always followed by another term.
E.g.
	- ‘the xAPI specification’
	- ‘an xAPI statement’
	- ’in xAPI requests’

**Sections 8.1.2 & 8.2.2**  would read better as:

	…using the xAPI Specification.

**Sections 8.3** would read better as: 

 	as specified in the xAPI specification.

**Comment by MrBillMcDonald** [comment]
Per the August 18, Meeting - the following was agreed:

1. Update xAPI definition in definitions
2. Update references to xAPI specification (both ADL and IEEE)
3. Replace “xAPI specification” as “xAPI” (and make associated grammar changes)

**Update Definition as follows:**

* **Experience API (xAPI):** The IEEE 9274.1.1 xAPI 2.0 Standard. A runtime data communication specification for learning content (AU) to send and receive data to a Learning Record Store (LRS).  xAPI is used to define the data transport and the data model. As far as requirements found in this document (other than the requirement of xAPI usage), the xAPI Specification 1.0.x is equivalent.

**Update References as follows:**

* Experience API (xAPI), version 1.0.3
         https://github.com/adlnet/xAPI-Spec
* Experience API (xAPI) Standard (IEEE 9274.1.1 xAPI 2.0)   
        https://opensource.ieee.org/xapi
