### ISSUE TITLE
In Section 9.6.3.3 launchMode Description field could be made more succinct and accurate

### ISSUE THREAD

**Issue by MartinKoob** [AICC/CMI-5_Spec_Current#804]
### [9.6.3.3 launchMode ](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#9633-launchmode)

> Description:	Indicates what launch mode an AU was launched with by the LMS 
> 

The above sentence is awkward.

**Suggestions:**
- use ‘**which**’ instead of ‘**what**’ since there are a limited number of modes that can be used to launch an AU
(According to **Section 10.2.2 launchMode** in this specification  the permitted modes are “Normal”, Browse” and “Review”)
- rearrange the sentence to make it more succinct and accurate.  

Here are a couple of ways it could be reworded.

`Description:	Indicates which launch mode was used by the LMS when an AU was launched.`

OR

`Description:	Indicates the launchMode used by the LMS to launch an AU.`

**Comment by MrBillMcDonald** [comment]
Per Aug 18th meeting - Use this verbiage: 

Indicates the launchMode that was used by the LMS to launch an AU.
