### ISSUE TITLE
References in one section to another section of this standard are not consistent

### ISSUE THREAD

**Issue by MartinKoob** [AICC/CMI-5_Spec_Current#806]
References in one section to another section of this standard are not consistent

There are various ways used to refer to other sections of the document:
- “State API requirements to … as defined in Section 10”*	
     - 6.0 LMS Requirements
          - Implement additional State API requirements to initialize the AU state as defined in Section 10.  		

     This form also used in the following sections:
     - 6.2 LMS State API Requirements
     - 7.0 AU Requirements

-  the State API (See Section 10)
     - 9.6.3.1 session ID
          ⁃ LMS Usage: The value for session ID MUST be generated by the LMS. The LMS MUST record the session ID in the State API (See Section 10) prior to launching an AU. The LMS MUST provide the session ID in the context as an extension for all cmi5 defined and cmi5 allowed statements it makes directly in the LRS.  

- xAPI State Data Model, Section 10.0
     - 9.3.3 Completed
     LMS Obligations: The LMS MUST use "completed" statements based on the "moveOn" criteria for the AU as provided in the LMS Launch Data. (See xAPI State Data Model, Section 10.0 - moveOn) 	9.3.4 Passed
     AU Obligations: The AU MUST send a statement containing the "passed" verb when the learner has attempted and passed the AU. If the "passed" statement contains a "scaled" score, the scaled value MUST be equal to or greater than the masteryScore indicated in the LMS Launch Data. (See xAPI State Data Model, Section 10.0 - masteryScore). The AU MUST NOT issue multiple "passed" statements for the same AU within a given course registration for a given learner. 
 		
     - 9.3.4 Passed
     AU Obligations: The AU MUST send a statement containing the "passed" verb when the learner has attempted and passed the AU. If the "passed" statement contains a "scaled" score, the scaled value MUST be equal to or greater than the masteryScore indicated in the LMS Launch Data. (See xAPI State Data Model, Section 10.0 - masteryScore). The AU MUST NOT issue multiple "passed" statements for the same AU within a given course registration for a given learner. 
 	
     - 9.3.5 Failed 	
     AU Obligations: The AU MUST send a statement containing the "Failed" verb when the learner has attempted and failed the AU. If the "Failed" statement contains a (scaled) score, the (scaled) score MUST be less than the "masteryScore" indicated in the LMS.LaunchData document. (See xAPI State Data Model, Section 10.0 - masteryScore).

**Comment by MrBillMcDonald** [comment]
Reviewed in AUg 18th meeting - pull request pending... 

Explicit Number (e.g. 10.0) and Title for all section references (e.g. “10.0 xAPI State Data Model”)
