### ISSUE TITLE
Standardized approach to "expected" AU duration

### ISSUE THREAD

**Issue by ETMayberry** [AICC/CMI-5_Spec_Current#810]
Hi, I am working on a fairly large project implementing the Total Learning Architecture and pushing adoption of cmi5 standards for a community of content developers. One challenge I have encountered is how to import a cmi5 package into a course catalog and publish the expected duration of each course based upon AUs. 

For now I set up an API where uploaded course bundles may be accompanied by form data including expected durations for each AU, but it really feels like I should be able to have developers submit something like `expectedDuration="PT2H"` (as an ISO 8601 duration) alongside of similar metadata like `masteryScore` and `moveOn`.

My question is basically whether there is an accepted (or proposed) way of expressing the expected AU durations within `cmi5.xml` that I am missing? I only found one relevant comment from another (very old) thread here, but it did not seem to have any responses or references:
https://github.com/AICC/CMI-5_Spec_Current/issues/32#issuecomment-17719440

**Comment by MrBillMcDonald** [comment]
Thank you for your raising this issue!

Current, there is not concept of expected duration in the cmi spec.  However the course structure file (cmi5.xml) is extensible, so you could create your own extension (but this would not be necessary interoperable with other system that do not implement "expectedDuration")

The IEEE cmi5 working group will consider this as it works on the next version.  Please consider participating in this effort !    

Please send a message to: stds-p9274-3-1@listserv.ieee.org

**Comment by ETMayberry** [comment]
Thanks!
