### ISSUE TITLE
Possible mis-reference in section 10.2.1 contextTemplate referring to 9.6.3.2 masteryScore instead of 9.6.2.3 Publisher ID Grouping Activity

### ISSUE THREAD

**Issue by ETMayberry** [AICC/CMI-5_Spec_Current#815]
[This paragraph](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/cmi5_spec.md#1021-contexttemplate) located in the Quartz spec currently reads:

> The LMS MUST include a `contextTemplate` object and MUST include the following values:
> * The value for session id placed in an `extensions` object with the ID as defined in Section 9.6.3.1 session ID.
> * The publisher ID Activity as defined in Section 9.6.3.2 masteryScore in the `contextActivities.grouping` list.
>
> The LMS MAY place additional values in the contextTemplate.

Based on my reading I believe the second bullet in this section should be referencing 9.6.2.3 Publisher ID Grouping Activity (probably used to be the now-deprecated 9.6.3.5 publisherId).

**Comment by MrBillMcDonald** [comment]
ETMayberry, Thank you for bringing this to our attention.

We will correct this defect.
