### ISSUE TITLE
Completed/passed statements in the event of catastrophic failure

### ISSUE THREAD

**Issue by garemoko** [AICC/CMI-5_Spec_Current#96]
In CMI5 we say ``` The AU must not issue multiple statements with "Completed" for the same AU within a given AU session or course registration for a given learner. ``` We say the same about passed. 

I think this is sensible, but do we need to add more detail about how this will be achieved in the scenario where something goes wrong? 

See this comment on the xAPI spec: https://github.com/adlnet/xAPI-Spec/issues/497#issuecomment-67309147

**Comment by MrBillMcDonald** [comment]
In the scenario that you described - the AU would be non-conformant and the LMS actions to deal with the error condition would be vendor-defined.  (including possible actions such as voiding statements or rejecting statements)

**Comment by fugu13** [comment]
At the very least we should prescribe precise interpretations of illegal sequences (which *are* going to happen), so that vendors can be sure whatever cleanup they do doesn't lead to a different interpretation. We might even include a recommended clean up procedure, since that'll usually be a straightforward "void all statements like this after this point in the sequence".

**Comment by garemoko** [comment]
Is voiding appropriate? We're talking about a scenario where a learner loses internet connection or closes their browser - we're just going to void the whole session? Or am I misunderstanding?

**Comment by fugu13** [comment]
I'm thinking of impossible sequences, where definitionally the later statements were not allowed, and are thus mistaken and voiding-appropriate

**Comment by bscSCORM** [comment]
@fugu13 Voiding does seems appropriate (of specific bad statements as you say), but we didn't want to mandate it, as we'd then have the LMS polling the LRS periodically for statements to void. It seems unreasonable to put much of a mandated behavior burden on a system to deal with forbidden behavior by another system. In the case of tightly integrated systems, rejecting these statements with a HTTP 403 seems better.

I think it's a big can of worms to try to preserve interoperability once one participant stops following the spec. I agree this will happen, but that doesn't mean we need to mandate a recovery mechanism, as always LMSs will vary in how they handle bad content.

@garemoko I don't think it would be _good_ behavior, but I don't think an LMS should be considered non-conforming if it voids out the entire session upon receiving an invalid sequence. Again, I just don't think preserving interoperability is reasonable once one side starts misbehaving (given we can't mandate blocking that misbehavior as it occurs), so I stand by "vendor-defined" and by that we really mean *anything* goes, void individual statements, start responding with 403 to specific requests, void the whole session, void every statement ever made by content from that vendor, send a strongly worded letter, anything. Some of these actions would obviously be better than others.

**Comment by garemoko** [comment]
Just to check I'm on the same page, is this in line with what you are saying @bscSCORM?

In the event of a statement going missing (breaking the required statement order) due to some internet weirdness in a small number of launches from an otherwise conformant AU, it's up to the LMS how it handles this, whether that's filling in the gaps as best it can or voiding the record of entire launch and the learner's progress. 

If so, should we add a recommendation at least that the LMS should consider this scenario and how it will respond?

**Comment by MrBillMcDonald** [comment]
LMS defined behavior for AU's that don't comply CMI-5 statement rules (or unsuccessful statements).  PR pending for this statement.

**Comment by bscSCORM** [comment]
After more discussion at our April 16th mtg. and with @fugu13 on the phone, it looks like we need to at a minimum define some actions that the LMS is prohibited from taking upon receiving invalid sequences, most importantly it should be prohibited from carrying on as if nothing went wrong.

**Comment by MrBillMcDonald** [comment]
Tabled until after Sandstone release.
