### ISSUE TITLE
Clarification on State Document

### ISSUE THREAD

**Issue by andyjohnson** [AICC/CMI-5_Spec_Current#97]
The spec, in 10.0 says that ONLY one State document for the combination of activityid, agent, registration, and stateid can exist. It says the Document Name (State ID) must be  "LMSLaunchData".  Is this the same stateid?  If so, we need to clarify it by calling it out in the ONLY requirement and by using syntax consistently (State ID vs stateid).  Finally, the State API PUT Properties calls the stateid LMS.LaunchData (notice the extra period).

**Comment by MrBillMcDonald** [comment]
Will Develop a pull request to address this per Feb 13 Meeting.
