### ISSUE TITLE
Build in terminate with suspend? 

### ISSUE THREAD

**Issue by andyjohnson** [AICC/CMI-5_Spec_Current#98]
So in looking through the requirements, suspend has a requirement to be tightly coupled with terminate.  If this is the case, do we need two Statements?  Can't suspend indicate that the session is terminated on its own?  This way "terminated" could actually mean the logical end of an attempt without the intention to resume (and therefore if summary data were placed only in terminates, it would also make more sense with the knowledge that this really means the learner is done).  It would make querying cleaner too.  Abandoned would have to look for both suspended and terminate in its behavior, but I think this is the only detriment.

**Comment by MrBillMcDonald** [comment]
As per meeting Feb 13  discussion - closing as terminate is necessary for robust session management
