### ISSUE TITLE
The combination of failed and completed cannot exist

### ISSUE THREAD

**Issue by andyjohnson** [AICC/CMI-5_Spec_Current#99]
With the way the spec is currently set up, the possibility of an activity being both failed and completed cannot exist.  I think we should at least justify this in the spec.  I believe the line of thinking is that if you failed something, it can't be considered that you did it to a point of completion and you'd need remediation.

**Comment by cawerkenthin** [comment]
I'm not sure where you are getting that from.  What precludes both failed and completed.

**Comment by MrBillMcDonald** [comment]
Per Feb 13 meeting -  will remove **Completed** from Section "9.5.2 Success" and will remove **Passed** from section "9.5.3 Completion"
